### PR TITLE
add grant scope API to Dynamic Client Registration Collection

### PR DESCRIPTION
**Pull request by jennaxue-okta**
## Description:
- **What's changed?**  add grant scope API to "Dynamic Client Registration" Collection
- **Is this PR related to a Monolith release?** 
image

### Resolves:

* [OKTA-460167]

[OKTA-460167]: https://oktainc.atlassian.net/browse/OKTA-460167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by luishernandezcruz-okta** [comment]
The grants endpoint is part of the `apps` namespace. Should this be included in the Apps postman collection rather than dynamic client registration one? The API docs for this endpoint also live within the Apps API docs.

**Review by vanngo-okta — COMMENTED** [review]
I agree with @luishernandezcruz-okta. The endpoint is documented in the Apps API : https://developer.okta.com/docs/reference/api/apps/#grant-consent-to-scope-for-application.
Also, does it make sense to use a variable for "issuer" instead? Maybe "{{yourOktaDomain}}" or "{{url}}" (to match the Environment variable used in the other collections?):
`"issuer": "{{yourOktaDomain}}"`

**Comment by jennaxue-okta** [comment]
@luishernandezcruz-okta @vanngo-okta since I'm adding this for Multi-Org OAuth provisioning, and this grant scope operation is right after dynamic client creation according to the guide: https://developer.okta.com/docs/guides/secure-oauth-between-orgs/main/#create-an-oauth-2-0-service-app-in-the-hub-org, I put it in this Collection. Do you think we can move it to "Dynamic Client Registration" => "Apps API"?
image

**Review by vanngo-okta — COMMENTED** [review]
Ahh, I see. The MultiOrg Auth doc uses the Apps API to create the Org2Org app, but the Dynamic Client Registration API to create the Service app. This is taken from the spec. Perhaps we need to use the Dynamic Client API to set the `client_credentials` grant type? Not sure. Please let me know if I need to update any process in the doc. As for the Postman Collection, do you want to move the `POST Grant Scope to Client` request to the Apps API Collection?

Screen Shot 2022-03-02 at 11 04 39 PM
Screen Shot 2022-03-02 at 11 04 39 PM

**Comment by jennaxue-okta** [comment]
@vanngo-okta `grant_type: client_credentials` is set when creating the dynamic client, the doc is good. I'll move the grant scope API to Apps Collection.

**Comment by jennaxue-okta** [comment]
moved to Apps Collection
image

**Review by vanngo-okta — APPROVED** [review]
LGTM! 🚀

**Review by luishernandezcruz-okta — APPROVED** [review]
LGTM 👍

**Pull request merged**
