### PR TITLE
OKTA-690935 Fix OIN Wizard doc issues

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Fix anchor link issues, remove $, and oin limitation
- **Is this PR related to a Monolith release?** No

### Preview:
https://65cd4567ecf95f1f71347267--reverent-murdock-829d24.netlify.app/docs/guides/submit-oin-app/openidconnect/main/

### Resolves:

* [OKTA-690935](https://oktainc.atlassian.net/browse/OKTA-690935)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/7b3ec339a0c32377500b5884002f5c864eb43d59/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/98df6383-0c1b-4589-a7b2-57384a193aeb) | 74  | 74  | 75  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/7b3ec339a0c32377500b5884002f5c864eb43d59/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/240d405c-2a1f-4bbd-9aeb-8ea3fefd4c80) | 80  | 87  | 79  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md](https://github.com/okta/okta-developer-docs/blob/7b3ec339a0c32377500b5884002f5c864eb43d59/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Fprotocol-properties.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5732186f-cd2f-4b63-93b0-194531438541) | 100  | 71  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md](https://github.com/okta/okta-developer-docs/blob/7b3ec339a0c32377500b5884002f5c864eb43d59/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Ftest-instance.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1aa93abb-3b13-4471-aaf6-fc5a2d8ac954) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md](https://github.com/okta/okta-developer-docs/blob/7b3ec339a0c32377500b5884002f5c864eb43d59/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Fvariable-desc.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cee41ee5-1c72-48fa-a3e5-a2971b4c2de9) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b2575cde-e0de-498f-ac3b-2fc588fd5a1b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/2dfc7d2b22f318c0d6ee35a53053443d3c0223e3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0756eae1-f38b-46f9-b980-fffcccb70ca9) | 74  | 74  | 75  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/2dfc7d2b22f318c0d6ee35a53053443d3c0223e3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3c8fffe8-0cda-4ede-95e9-237c2cbd9141) | 80  | 87  | 79  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md](https://github.com/okta/okta-developer-docs/blob/2dfc7d2b22f318c0d6ee35a53053443d3c0223e3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Fprotocol-properties.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/10252b95-add9-4cf0-93d2-dccc57d3838c) | 100  | 71  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md](https://github.com/okta/okta-developer-docs/blob/2dfc7d2b22f318c0d6ee35a53053443d3c0223e3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Ftest-instance.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7973e4b1-8479-461d-a7ac-4aea23a375f9) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md](https://github.com/okta/okta-developer-docs/blob/2dfc7d2b22f318c0d6ee35a53053443d3c0223e3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Fvariable-desc.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/77360e81-92b8-4134-a630-11aa7bced72f) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.231152ad-253b-48eb-a15b-aaee35b2bf6e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-private-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-private-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/95ef5089-415c-4cae-8417-4ca89b1f2667) | 61  | 82  | 90  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fc6e4e53-21ad-4b5a-b3f4-90592ae75ab5) | 74  | 90  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1a5db4be-0ef7-46c4-8b5d-1f1175dcf95b) | 91  | 95  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/58d11c4c-7b17-4d0e-a03f-1b7ca3a120aa) | 74  | 74  | 75  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6e5f423d-e8f6-45a2-93d7-a64c0081d6b0) | 80  | 87  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/protocol-properties.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Fprotocol-properties.md) | [91](https://okta.acrolinx.cloud/api/v1/checking/scorecards/14df4986-f1e3-44a7-8908-347c35bd465d) | 100  | 71  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Ftest-instance.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e6d7222d-07d5-4983-8221-723e0880bbbc) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md](https://github.com/okta/okta-developer-docs/blob/d472138f48ffbcb1c5adbb449817da8d5661f72d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Fvariable-desc.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1ec902a3-4f76-4988-a55a-4f379340b3e0) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.335b5ec7-b7e0-48f4-a639-9554e8e7db92?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by ykrestyanov-okta — APPROVED** [review]
lgtm

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
