### PR TITLE
OKTA-553793 Event hook health checking

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Added note in Event Hooks concepts: https://developer.okta.com/docs/concepts/event-hooks/#timeout-and-retry
- **Is this PR related to a Monolith release?** Yes - 2023.05.0

### Resolves:

* [OKTA-553793](https://oktainc.atlassian.net/browse/OKTA-553793)

### CODE REVIEW

**Comment by brianduffield-okta** [comment]
Closing this PR as "No longer required" - after discussion in standup. See the ticket for details.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md](https://github.com/okta/okta-developer-docs/blob/2820c7ff78e1a8d4f2aa050c2034cf9e1bef7bc2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fevent-hooks%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e4cdbe96-455a-4aef-9e41-12472189b83e) | 71  | 56  | 36  | 91  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.54453b55-1e38-432d-8a49-d4192387241d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md](https://github.com/okta/okta-developer-docs/blob/fb36e531f9b20f77301b9671d1256b8b1e158770/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fevent-hooks%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d21bf3a4-c02f-45a2-b369-a580c0bf1b89) | 68  | 70  | 55  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.2934d8df-a00f-4b5a-80e1-9432098e1124?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by brianduffield-okta** [comment]
Re-opening PR as per engineering. Acrolinx score update will come from another branch.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md](https://github.com/okta/okta-developer-docs/blob/069d38660adcbbca2abdec8c78ec06c20a267826/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fevent-hooks%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/809207b4-3c10-4cc5-93a6-33ad7f85087d) | 68  | 68  | 53  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.f4383e44-8e9f-4d0e-b0f0-f60e9d81bde6?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Pull request merged**
