### PR TITLE
OKTA-617748 Release 2023.06.0

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Release notes and developer documentation updates for the June Monthly release
- **Is this PR related to a Monolith release?** 2023.06.0

### Resolves:

* [OKTA-617748](https://oktainc.atlassian.net/browse/OKTA-617748)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-email%2Fmain%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/143e1fec-4e69-43d2-b574-b928b0982fea) | 66  | 96  | 93  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-error-pages%2Fmain%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/deab3f69-2962-443d-93f2-42532f20c917) | 53  | 85  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-url-domain%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1ad4bf6d-b818-4a7d-98e4-d12ee91ac2c2) | 86  | 84  | 54  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-widget%2Fmain%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/33c1d06e-9f36-4d1a-8d78-0e536c625cd5) | 61  | 76  | 61  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/18ccd544-17a0-4944-9743-c623b1faeeda) | 41  | 53  | 74  | 85  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foie-upgrade-sign-in-widget%2Fmain%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6fd09ada-7e61-44a5-9264-9bd3f35a99f8) | 31  | 89  | 82  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/policy-simulation/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fpolicy-simulation%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/20eaeeda-db14-42d5-b82b-ced715431862) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fpolicy-simulation%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d55d7ebb-1a18-47c7-aee9-92cbfd74a712) | 88  | 79  | 88  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fauthenticators-admin%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1a15f033-4afc-4c1d-a756-078263a89382) | 57  | 83  | 77  | 62  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/oidc/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Foidc%2Findex.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/453489cd-92db-43e1-b1db-7063ce0af49c) | 73  | 66  | 58  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/policy/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fpolicy%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d6407d85-b350-4a13-8ffe-93fbd97e385c) | 64  | 80  | 61  | 84  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/push-providers/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fpush-providers%2Findex.md) | [65](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3412f3b7-d5fc-49c6-bb18-80b2734ccf56) | 73  | 49  | 78  | 50  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023-okta-identity-engine%2Findex.md) | [73](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c131de05-d6c3-49a4-b6a9-c84250bc9377) | 67  | 83  | 48  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023/index.md](https://github.com/okta/okta-developer-docs/blob/fd9e32dd1eb540b55f6882560a07810679d414cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023%2Findex.md) | [75](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5ba1e444-df5c-4077-8ddf-cc7cf61744da) | 82  | 85  | 45  | 99  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.c6136132-fd1e-4aa0-bad4-6d1007e702de?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by vanngo-okta — APPROVED** [review]
LGTM !🚢

**Comment by brianduffield-okta** [comment]
oktapreview.com:1:home is now running 2023.06.0 as of 10:15 EST

**Pull request merged**
