### PR TITLE
added table row

### PR DESCRIPTION
**Pull request by christinechoy-okta**
## Description:
- **What's changed?** Add to rate limit authentication table
- **Is this PR related to a Monolith release?** Yes Release 2021.03.0

### CODE REVIEW

**Review by IanHakes-okta — APPROVED** [review]
LGTM - are all the numbers signed off by your technical owner?

**Comment by jakubvul-okta** [comment]
Yea I'd like SME sign off on any rate limit updates

**Comment by susanharper-okta** [comment]
it's for the march monthly release. Christine is having Joe Castellanos review it. He doesn't have an account in here yet.

**Comment by christinechoy-okta** [comment]
> it's for the march monthly release. Christine is having Joe Castellanos review it. He doesn't have an account in here yet.

Joe Castellanos has reviewed it and has approved via Slack.

**Pull request merged**
