### PR TITLE
OKTA-752881 Org creator concept

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Add Org creator concept to support Org Creator API
- **Is this PR related to a Monolith release?** Yes, it needs to be synchronized with oas3 PR733 (which might be published in 2024.09.0)

### Resolves:

* [OKTA-752881](https://oktainc.atlassian.net/browse/OKTA-752881)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/org-creator/index.md](https://github.com/okta/okta-developer-docs/blob/fe30c184d599c89dbed52b25e685e62aaabb3d80/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Forg-creator%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ddac4dcb-6530-43ac-9462-377c2064271d) | 100  | 68  | 81  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f89750f2-6540-43a1-8242-dcaee756e68f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/org-creator/index.md](https://github.com/okta/okta-developer-docs/blob/ea51db881bc88a53669c7710776b7e7d28c57982/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Forg-creator%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0d2b3309-252c-4bb0-855e-291e9491667b) | 100  | 81  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c3095c33-a28e-4a44-87a0-b0051e43d09d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/org-creator/index.md](https://github.com/okta/okta-developer-docs/blob/eb307c9401322290bffc51bf76d635cced4601bc/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Forg-creator%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c6a96d97-039b-4187-9f3e-c2517b0a5995) | 100  | 80  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.777255e6-ae54-4a31-9576-02feb4382aea?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/org-creator/index.md](https://github.com/okta/okta-developer-docs/blob/6ba06a7bdaa9cda71c5e915cb3a1f7c1e91c90e2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Forg-creator%2Findex.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3d56a22f-6899-44ee-8448-148ed68a76e9) | 100  | 80  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b3297e61-4e82-4f6f-9b6d-87000c8d2617?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/org-creator/index.md](https://github.com/okta/okta-developer-docs/blob/4c99a324bf814d77cccb3608e8a87b98911e4205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Forg-creator%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ce2fe74b-6c29-4c1d-8ee1-a4e85bca105e) | 100  | 80  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.1b021630-39ca-4b61-81d4-12aa28f674df?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by grahamsmith-okta — APPROVED** [review]

**Comment by vanngo-okta** [comment]
Publishing this early since the corresponding API was already published.

**Pull request merged**
