### PR TITLE
Add new styling code to platform for image sizing

### PR DESCRIPTION
**Pull request by chrisdmills-okta**
## Description:
- **What's changed?** In the new dev.okta image guidelines and process (to be published imminently), we outline four new classes to be added to a `<div>` surrounding an embedded content image, in this kind of structure:
  ```
  <div class=”classnames”>

  ![Your Alt Text](/img/filename.png)

  </div>
  ```
  The four classes added in this PR are:
    - `full`: make the image span the full width of the content column
    - `half`: make the image span half the full width of the content column (full width on narrow screen view)
    - `quarter`: make the image span a quarter of the full width of the content column (half the width on narrow screen view)
    - `border`: used in addition to one of the other three, gives the image a thin gray border
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-505426](https://oktainc.atlassian.net/browse/OKTA-505426)

## Instructions for testing

1. Build the branch locally with `yarn dev`.
2. Load up http://localhost:8080/docs/guides/authenticators-okta-email/aspnet/main/#discover-the-convenience-of-magic-links in your browser. This page section contains the image we'll test the CSS classes on.
3. Find the main `index.md` source file for this guide (`guides/authenticators-okta-email/main/index.md`).
4. Find the source code for this image:
  ```
  <div class="common-image-format">

  ![Simple diagram illustrating magic links](/img/authenticators/authenticators-email-magic-link-summary-simple-overview.png)

  </div>
  ```
5. Change the `common-image-format` format classname to `quarter`, `half`, then `full`, and in each case test whether the image resizes to the expected width.
6. Also in each case, change the browser window size to check whether the image is sized differently when the browser window is narrow (`half` should be `100%` width, `quarter` should be 50% width).
7. Update the `class` attribute to contain an extra classname, `border`, e.g. `class="full border"`, and test whether this causes a gray border to appear round the images. Test whether it works along with `quarter`, `half`, and `full`.
8. For bonus points, test whether this all works on a real mobile device or emulator. I've tested it in responsive design mode in Firefox, but not in a real mobile browser.

### CODE REVIEW

**Review by brentschaus-okta — APPROVED** [review]
LGTM!

Everything works as expected. Didn't get to test on mobile, though.

**Review by danielmaharry-okta — CHANGES_REQUESTED** [review]
The sizing styles seem to work fine. However the border needs rounded corners to match the graphics corners. It's much easier to see in dark mode. For reference, the current CSS style is

```
  .bordered-image > p > img {
    border: 1px solid cv('gray', '200');
    border-radius: 46px;
  }
```

**Comment by chrisdmills-okta** [comment]
Updated to use a rounded corner for the borders; the same CSS as yours exactly to be precise, @danielmaharry-okta . That work for you?

**Review by danielmaharry-okta — APPROVED** [review]
Looks good to me!

**Pull request merged**
