### PR TITLE
Reference TOC updates

### PR DESCRIPTION
**Pull request by annejuan-okta**
## Description:
- **What's changed?**  VuePress TOC updated
- **Is this PR related to a Monolith release?**  Nope

### Resolves:

* [OKTA-744084](https://oktainc.atlassian.net/browse/OKTA-744084)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/classic-engine/index.md](https://github.com/okta/okta-developer-docs/blob/229d1a7ba68e34e104baa6874fb9d192a5c8e9e3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fclassic-engine%2Findex.md) | [60](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b37e723b-75b1-47cd-a961-7ef64e41ba68) | 52  | 52  | 35  | 68  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.cdc46330-b065-4042-b099-d0e7add82b46?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/classic-engine/index.md](https://github.com/okta/okta-developer-docs/blob/e993d9b75573ab25385b88f3f536ac0452e06e97/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fclassic-engine%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/441e9bb1-bad7-4a26-a801-dcd3db993fef) | 100  | 100  | 100  | 70  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.fd878b50-7225-4997-add7-d44a6207c698?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/classic-engine/index.md](https://github.com/okta/okta-developer-docs/blob/ecdf55507edb4da9b70202b5dbc21759491d4395/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fclassic-engine%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9da956a6-3723-44a2-98c7-4c46f97daacc) | 100  | 100  | 100  | 69  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.1e6b5c9b-79b8-4291-81c1-55a064128eff?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/classic-engine/index.md](https://github.com/okta/okta-developer-docs/blob/b11686d7a69d0656e1c1a38c25bdf63969c75293/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fclassic-engine%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/52cd121a-fa44-4c0e-b0c0-0bd0561e5ba6) | 100  | 100  | 100  | 69  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f73251f9-8256-48fd-8f7e-cadb88dfeb4b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by grahamsmith-okta — DISMISSED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/classic-engine/index.md](https://github.com/okta/okta-developer-docs/blob/25f7d25db5bd23cec1ce454cfdd84d198b9126e0/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fclassic-engine%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/46e086f1-5b3a-4329-864f-aef82bee885d) | 100  | 100  | 100  | 69  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a85f644d-2be9-44f8-bcd0-0ca6938e682b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/classic-engine/index.md](https://github.com/okta/okta-developer-docs/blob/d89bba91f5cc64bb4ee4586303cc8e18f0dd907d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fclassic-engine%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/275286b4-698c-4e12-a0ee-920e49e6aa74) | 100  | 100  | 100  | 69  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.1583cfe6-3956-46b7-b7e5-1eb98e24b51a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
