### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
fix invalid json. 

there were several errors. have all of these been tested?

also, i got an error on `okta.users.profile.manage`. is this valid?

### CODE REVIEW

**Review by alifatolahi-okta — COMMENTED** [review]
thanks for creating this. I confirm we need to change
`okta.users.profile.manage` to `okta.users.userprofile.manage`

in the following places:
https://github.com/okta/okta-developer-docs/blob/master/packages/@okta/vuepress-site/docs/reference/api/roles/index.md?plain=1#L59
https://github.com/okta/okta-developer-docs/blob/master/packages/@okta/vuepress-site/docs/reference/api/roles/index.md?plain=1#L333
https://github.com/okta/okta-developer-docs/blob/master/packages/@okta/vuepress-site/docs/reference/api/roles/index.md?plain=1#L325

**Comment by susanharper-okta** [comment]
> thanks for creating this. I confirm we need to change `okta.users.profile.manage` to `okta.users.userprofile.manage`
> 
> in the following places: https://github.com/okta/okta-developer-docs/blob/master/packages/@okta/vuepress-site/docs/reference/api/roles/index.md?plain=1#L59 https://github.com/okta/okta-developer-docs/blob/master/packages/@okta/vuepress-site/docs/reference/api/roles/index.md?plain=1#L333 https://github.com/okta/okta-developer-docs/blob/master/packages/@okta/vuepress-site/docs/reference/api/roles/index.md?plain=1#L325

@alifatolahi-okta - is someone going to make these changes? Thanks!

**Comment by alifatolahi-okta** [comment]
thanks @gabrielsroka for pointing out those discrepancies.

@susanharper-okta DDA will take care of these suggestions, here's the tracking JIRA: https://oktainc.atlassian.net/browse/OKTA-451288

**Comment by gabrielsroka** [comment]
it looks like these 4 particular changes have been made

have all the examples been tested?

**Comment by alifatolahi-okta** [comment]
> 

@gabrielsroka almost, we're still fixing a few other minor things next week.

**Comment by susanharper-okta** [comment]
Closing - checked with Ali and all of the fixes that pertained to this are now in.

**Pull request closed without merging**
