### PR TITLE
Added entries for okta.directories.manage and okta.directories.read.

### PR DESCRIPTION
**Pull request by timhowie-okta**
## Description:
- **What's changed?** Added entries for okta.directories.manage and okta.directories.read
- **Is this PR related to a Monolith release?** Yes 2023.10.1

Netlify Link:
https://65298685f65326071af2c1e9--reverent-murdock-829d24.netlify.app/docs/reference/api/roles/#permission-types

### Resolves:

* [OKTA-600493](https://oktainc.atlassian.net/browse/OKTA-600493)

### CODE REVIEW

**Comment by susanharper-okta** [comment]
This PR has been approved by the Directories team

**Review by brianduffield-okta — APPROVED** [review]
LGTM

**Pull request merged**
