### PR TITLE
Fixit'22 - Replace drop shadow images

### PR DESCRIPTION
**Pull request by danielmaharry-okta**
## Description:
- **What's changed?** Updated ~100 images to remove drop shadows.  Fixed several broken links to six of those images.
- **Is this PR related to a Monolith release?** No

### CODE REVIEW

**Review by robertnicolo-okta — CHANGES_REQUESTED** [review]
Without any borders, the contents of the screenshots and modal windows just merge within the surrounding page. I think we are going to need to add some sort of thin border around those images.

**Review by robertnicolo-okta — CHANGES_REQUESTED** [review]
Looking good Dan. See my comments in the below video:
https://drive.google.com/file/d/185Ff-6ZRrD4nyGMzZ5DPwTJJ9sx5oezr/view?usp=sharing

For reference that stripe link is: https://stripe.com/docs/connect/enable-payment-acceptance-guide.  And the CSS (note the color) on that page that makes that border is:

.BorderImage {
    box-shadow: 0 0 0 1px #e3e8ee;
}

###UPDATE: Actually, I noticed chris had recommended Gray 200 and Gray 700 is currently being used.

**Comment by danielmaharry-okta** [comment]
@robertnicolo-okta Fixed the issue - please review and approve.

**Review by robertnicolo-okta — APPROVED** [review]
updates look good - lgtm

**Pull request merged**
