### PR TITLE
fix(guides): Adds Breadcrumbs, fixes SSR for guides w/o StackSelector

### PR DESCRIPTION
**Pull request by swiftone**
## Description:
- **What's changed?** 
  - Adds Breadcrumbs to Guides
  - Fixes SSR for guides w/o StackSelector
  - removes bash/sed-specific build of guides on startup
- **Is this PR related to a Monolith release?** 
  - No

### Resolves:

* [OKTA-218631](https://oktainc.atlassian.net/browse/OKTA-218631)

### CODE REVIEW

**Comment by nbarbettini** [comment]
Want to get some quick UX input @alexdahl-okta:

image

What do you think the ideal place to end the breadcrumb "trail" is?
1. Guides > Sign Users in to Your Web Apps
2. Guides > Sign Users in to Your Web Apps > Before You Begin
3. Guides > Sign Users in to Your Web Apps > Before You Begin >

**Comment by nbarbettini** [comment]
Lgtm @swiftone! I'd like to get Alex's design opinion on the above before merging.

**Comment by nbarbettini** [comment]
@swiftone Can you look at this link: https://github.com/okta/okta-developer-docs/blame/guides-breadcrumb/packages/%40okta/vuepress-site/guides/sign-into-web-app/define-callback/aspnet/define-route.md#L3

I tried different syntax but couldn't get it to reliably go to the correct section and preserve the current stack. I might be doing something wrong.

**Comment by alexdahl-okta** [comment]
@nbarbettini I'd say something pretty different: `Docs > Guides >`

Thinking there is that it communicates that you're in the Guides section, and everything in the tree nav is a child of guides (and the breadcrumbs have a relationship with responsive tree nav behavior). But that's a little different from traditional breadcrumbs.

If we want the full path, I'd say 2: `Guides > Sign Users in to Your Web Apps > Before You Begin`

**Pull request merged**
