### PR TITLE
[OKTA-707143] Part 2, additional fixes

### PR DESCRIPTION
**Pull request by annejuan-okta**
## Description:
- **What's changed?**  Straight quote fix, nav bar fix, and added H1 back in. Continuation of PR#4731
- **Is this PR related to a Monolith release?**  No

### Resolves:

* [OKTA-707143](https://oktainc.atlassian.net/browse/OKTA-707143)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/22ee5578b818a6e5479ee9e18ceb4c80607de940/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e5600f95-85df-4fb6-89c3-1c2a752039dc) | 68  | 81  | 93  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b1b09bbb-234e-443c-8e3b-927f41b35a32?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/a646dd2fd48fbf5b5c2b75d128eab01733c9cf6f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8856feb8-429e-4daf-8afd-628b7667a3e8) | 68  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c2e36ba1-357e-44c7-b270-b76a70f414c9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/d7250129e60e919ff18811016c62e0d5da504a9e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/195d2fb8-e7b5-4882-8906-7dc5921dd27e) | 68  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7ecfecf1-b087-40a0-97b7-82a2a109a680?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/89e54f2ab7c5de00b4d92ea062415445cc9ffd8c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2518a552-c891-435d-84ec-24c5e416ed7a) | 68  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.705f3c21-bd9e-4412-9c32-6ad1ab746383?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/aeb353e68c317139c2ebcf15f15c751c1467bc1d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1fd06ecc-27ff-4a50-b383-a4ff243d133f) | 69  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b7d88964-110e-468a-bcd8-a731c54f8962?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/38ab903f48c53f6ff6651af87dcc56817f6a68fd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5fcdb094-01d5-4343-9432-103449f835e1) | 69  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.4373b299-683a-4383-9fbf-17c4d291e02b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/b022f262dcca2667c3ac28d700589df5152800a1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0ca565af-8df1-49eb-8bfb-3889f84b4745) | 69  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e1445c85-f82a-458d-bb35-bdc7c817cc05?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/780d204c8b171557bc111c92ca1e08c36714a13d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6d3ba61a-4b23-45e1-b080-7d0ec31678a6) | 69  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.46d23c7c-9dde-4838-af38-e9eae0b7e622?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md](https://github.com/okta/okta-developer-docs/blob/07f84dee4c9cd5f03fae2fd042ff6214520e99a0/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Freleases-at-okta%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/df7372d3-8e8e-4697-85a3-59f2a459614b) | 69  | 81  | 93  | 96  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.beeedb0d-56b7-4241-84f7-5ecd6e61b764?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
