### PR TITLE
updating date per Karthick

### PR DESCRIPTION
**Pull request by susanharper-okta**
## Description:
- **What's changed?** updated date for workflow
- **Is this PR related to a Monolith release?**

### CODE REVIEW

**Review by karthicksolaimalai-okta — APPROVED** [review]
lgtm. thanks!

**Review by christinechoy-okta — COMMENTED** [review]
Maybe change to "Workforce orgs created after...".

**Comment by susanharper-okta** [comment]
> Maybe change to "Workforce orgs created after...".

"that are" is used to resolve translation issues to other languages.

**Review by christinechoy-okta — APPROVED** [review]

**Review by simranbrar-okta — APPROVED** [review]
LGTM

**Pull request merged**
