### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
fix PKCE example

### CODE REVIEW

**Comment by brianduffield-okta** [comment]
Thanks for the PR, @gabrielsroka ! Will confirm fix with the team.

**Comment by gabrielsroka** [comment]
@brianduffield-okta any news?

**Comment by brianduffield-okta** [comment]
> 

Thanks for the note. Will ping the team again.

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Pull request merged**
