### PR TITLE
Update step num during google social login setup

### PR DESCRIPTION
**Pull request by santoshmale-okta**
## Description:
- **What's changed?** 
Update step num during google social login setup

- **Is this PR related to a Monolith release?** 
No

### Resolves:

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by nbarbettini** [comment]
Thanks for catching this nit @santoshmale-okta! 🎉

**Comment by santoshmale-okta** [comment]
Thanks guys! How do i merge this? i don't seem to have permissions? @jakubvul @nbarbettini

**Comment by nbarbettini** [comment]
GitHub was having an outage earlier, I'll check this again soon.

Nate B.

________________________________

**Comment by nbarbettini** [comment]
Merged!

**Pull request merged**
