### PR TITLE
OKTA-612241 Move Classic SSR guide to Archive area.

### PR DESCRIPTION
**Pull request by danielmaharry-okta**
## Description:
- **What's changed?** 
- Moved Classic SSR guide to the archive area
- Updated navbar, in article links, and conductor file.
- Tidied up some text to improve Acrolinx score

- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-612241](https://oktainc.atlassian.net/browse/OKTA-612241)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-configure-signon-policy/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-configure-signon-policy%2Fmain%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/acea3624-5882-4cc5-964a-58fd372a6c38) | 49  | 78  | 44  | 93  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-overview%2Fmain%2Findex.md) | [67](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4cb29682-6632-4fd1-83bb-0199179bb394) | 31  | 78  | 20  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-registration-inline-hook%2Fmain%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f232c162-cd49-4315-9a3c-5e24a7b1dcf5) | 65  | 62  | 85  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-set-up-self-service-registration/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-set-up-self-service-registration%2Fmain%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5ec2549a-d6b3-45d8-bab0-807134b7c5c1) | 58  | 79  | 49  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/deployment-checklist/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fdeployment-checklist%2Fmain%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cd448096-1897-4847-9662-0b039b978ed6) | 68  | 76  | 47  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/flow-diagram.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcode%2Fflow-diagram.md) | [73](https://okta.acrolinx.cloud/api/v1/checking/scorecards/39d061f2-34f2-410b-83b9-269064ed1e1f) | 50  | 50  | 60  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcode%2Fnextsteps.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a6d95dc8-503a-4e7c-a119-e3ad3a06426d) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/flow-diagram.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcodepkce%2Fflow-diagram.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/81c060cb-daca-4930-bd0d-47b72d68479e) | 53  | 53  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcodepkce%2Fnextsteps.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e0e98fdd-f67b-4d9c-93d4-2a7afbfcdcd5) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/flow-diagram.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fimplicit%2Fflow-diagram.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bc09fc92-cdc8-4143-be88-a7f1531f79eb) | 100  | 75  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fimplicit%2Fnextsteps.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7bb757d7-2dd6-4c9c-8600-03425e8bcae1) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fropassword%2Fnextsteps.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/da6afdbf-fc23-4e12-9034-4a78fe097ec4) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1b8f89e7-ffa8-4994-9edb-422f286c268c) | 41  | 53  | 74  | 85  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-users-out/main/index.md](https://github.com/okta/okta-developer-docs/blob/e8908c1da303c459ff0430b700ab3ca7d7224205/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-users-out%2Fmain%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/96954431-8e55-40d3-a78c-d9bc86cdfb5d) | 70  | 88  | 64  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.e2311886-24ef-48e3-a76e-7ddcdd7c993b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by brianduffield-okta** [comment]
Everything looks good, Dan. But I didn't see an update to the `conductor.yml` file for the redirects.

**Comment by danielmaharry-okta** [comment]
@brianduffield-okta  Good spot. For some reason, my changes to the conductor file weren't committed. Have done so now.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/conductor.yml](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fconductor.yml) |   |   | [→]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [packages/@okta/vuepress-site/docs/guides/archive-configure-signon-policy/main/index.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-configure-signon-policy%2Fmain%2Findex.md) | 68 | 111 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f0c252c2-b426-4a7a-9db5-98862eeab373) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/archive-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-overview%2Fmain%2Findex.md) | 67 | 33 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c62f56d0-6e41-425f-a1d3-033e8ad2479f) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-registration-inline-hook%2Fmain%2Findex.md) | 76 | 40 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6658a7f5-d987-4b44-90cc-4c58b76dfa01) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/archive-set-up-self-service-registration/main/index.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-set-up-self-service-registration%2Fmain%2Findex.md) | 74 | 75 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a5d16896-d645-4ebe-97d3-0d982b71c9d7) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/deployment-checklist/main/index.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fdeployment-checklist%2Fmain%2Findex.md) | 76 | 26 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d2ffaeea-02da-448d-b401-58b7440ab424) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/flow-diagram.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcode%2Fflow-diagram.md) | 73 | 16 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e668285e-bdc2-4d23-9dc2-a6e316207ef2) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcode%2Fnextsteps.md) | 100 | 6 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b7ee496-f158-4a95-8928-9f1339799077) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/flow-diagram.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcodepkce%2Fflow-diagram.md) | 82 | 14 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9f3eb27a-6499-40e6-8aae-cecb2fd08974) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fauthcodepkce%2Fnextsteps.md) | 92 | 7 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/888b5726-1db8-479a-823b-5163ce74694c) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/flow-diagram.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fimplicit%2Fflow-diagram.md) | 86 | 15 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f55aabd4-2a35-452b-b19d-56376adf9caa) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fimplicit%2Fnextsteps.md) | 92 | 7 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5d4f9406-f594-4a52-8f6b-6563c515393a) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/nextsteps.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-grant-type%2Fmain%2Fropassword%2Fnextsteps.md) | 92 | 7 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/78c8a2b2-068c-46b7-a491-92aff11a1e60) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | 67 | 38 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d189e75f-e801-4c61-8949-4e28658b89a5) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/sign-users-out/main/index.md](https://github.com/okta/okta-developer-docs/blob/ec6ad90f2b7323134b486086defd1e407da3a08b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-users-out%2Fmain%2Findex.md) | 75 | 30 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a2598a41-6182-4abe-986f-c89a50b34482) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 14 of 15 documents.
See summary in [Content Analysis Dashboard]()

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by brianduffield-okta — APPROVED** [review]
LGTM. Thanks, Dan.

**Pull request merged**
