### PR TITLE
Update telephony inline hook docs to use Twilio Verify

### PR DESCRIPTION
**Pull request by robinske**
## Description:
Hey folks - I work on technical content focusing on authentication over at Twilio. We just published a blog post for [how to BYOT with our Verify API](https://www.twilio.com/en-us/blog/okta-byot-verify). The changes here reflect our updated guidance to use the Verify API over messaging/voice separately for simpler and faster integration (using Verify avoids 10DLC and other regulatory registration).

We've previously worked with you to republish tutorials like this for [Auth0](https://auth0.com/blog/enable-mfa-with-twilio-and-auth0/) so was hoping we could do the same for the Okta side of things.

I also updated the Glitch project which you can see here: https://glitch.com/edit/#!/dune-resilient-aragosaurus

Happy to make any additional updates if needed. Let me know what you think!

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/4ceaba8f1d016601e1b5e94995df3306733d5ea6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftelephony-inline-hook%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7c6ac83c-6a28-492b-b318-5d62f508a2c9) | 92  | 74  | 79  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/nodejs/sendotp.md](https://github.com/okta/okta-developer-docs/blob/4ceaba8f1d016601e1b5e94995df3306733d5ea6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftelephony-inline-hook%2Fmain%2Fnodejs%2Fsendotp.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bcded1eb-b796-4c7a-98d7-8f07df9aa59e) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.fd5b9e3e-4bc0-4b30-903b-79833bac5471?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by susanharper-okta** [comment]
@robinske Thank you. I'll take a look at this and update accordingly.

**Comment by susanharper-okta** [comment]
Sorry, the requirement of opening a support ticket to use Twilio Verify isn't ideal for a tutorial that someone is trying to do right then. The Auth0 link you provided still uses the same process that this guide does. We'll stick with this until one can use Twilio Verify without opening a support ticket. Thank you.

**Comment by robinske** [comment]
thanks @susanharper-okta ! I'll reopen when the custom code feature is self service.

**Pull request closed without merging**
