### PR TITLE
Update basic-sign-in.md

### PR DESCRIPTION
**Pull request by tk-425**
Should this `<h3 id="protected">Protected</h3>` in line 98 be included in the return statement?

## Description:
- **What's changed?** 
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/basic-sign-in.md](https://github.com/okta/okta-developer-docs/blob/e849be89477da94b6d41ea1bbf1007d8627bea02/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Freact%2Fbasic-sign-in.md) | 78 | 19 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/19e18dd6-ac51-42ca-9c1b-668fa4a09f44) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.805d6136-e528-4836-a8ce-bf70ed73ad9d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by brianduffield-okta** [comment]
@tk-425 Thanks for catching this. I suspect no,  but will confirm.

**Review by alisaduncan — APPROVED** [review]

**Review by brianduffield-okta — APPROVED** [review]
LGTM

**Comment by brianduffield-okta** [comment]
Closing this PR. This update addressed in https://github.com/okta/okta-developer-docs/pull/4150

**Pull request closed without merging**
