### PR TITLE
OKTA-706467 Update References TOC to have external links for net-new APIs

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Update References TOC to have external links for net-new APIs, and remove them from Reference index page
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-706467](https://oktainc.atlassian.net/browse/OKTA-706467)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/b7f11d2ecbb189c9213fdcd591b3b3a5e7def2d9/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/94264260-a4ef-469f-83fd-f06c51b67c76) | 64  | 78  | 100  | 88  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e00dc396-0b94-471d-853a-a983aaa0bb36?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by isaacdurham-okta — APPROVED** [review]

**Review by susanharper-okta — DISMISSED** [review]
LGTM - you'll need to bring that page up to 80 - we can't block all content in the Reference folder, unfortunately - just the api folder.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/84a9959ff5ccd08e2a6ca6ca35410d30ea6fc136/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b6d8174-99e7-4a15-ba42-9ac6326f89ea) | 78  | 100  | 100  | 88  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.d4ce3ff7-ebe0-4db9-85c8-7180a1950109?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Pull request merged**
