### PR TITLE
OKTA-332527: Tree nav responsive issues

### PR DESCRIPTION
**Pull request by oleksandrpravosudko-okta**
## Description:
- **What's changed?** 
  * pass tree-nav state and viewport type through appContext
  * hide content area whenever mobile tree-nav is displayed
  * set static position for mobile tree-nav

- **Is this PR related to a Monolith release?** 
No

- **Netlify build**
https://5f902d332c16b94c9c6a272e--reverent-murdock-829d24.netlify.app/
### Resolves:

* [OKTA-332527](https://oktainc.atlassian.net/browse/OKTA-332527)

### CODE REVIEW

**Comment by oleksandrpravosudko-okta** [comment]
@alexdahl-okta, @albertchen-okta, would appreciate feedback on this change ([netlify build](https://5f902d332c16b94c9c6a272e--reverent-murdock-829d24.netlify.app/))

**Comment by alexdahl-okta** [comment]
Thanks @oleksandrpravosudko-okta, this is looking pretty good in Chrome! (I trust that someone else is doing cross-browser and on-device testing.)

I think the only thing I'd add is that in this state – when the viewport is narrow and the tree nav is toggled to be visible – it should fill all the width available to it:
5f902d332c16b94c9c6a272e--reverent-murdock-829d24 netlify app_docs_guides_sign-into-web-app_aspnet_before-you-begin_

**Review by AndriiDovhopolov-okta — APPROVED** [review]
Looks fine to me. I will need to edit tests for tree-nav after finishing working with styling.

**Comment by oleksandrpravosudko-okta** [comment]
@alexdahl-okta thanks for the feedback - updates are available [here](https://5f98e3f64eb4b785f5629f6d--reverent-murdock-829d24.netlify.app/)
I have dev-tested this on desktop Safari/Firefox/Chrome and on iOS Safari/Chrome

**Review by alexdahl-okta — APPROVED** [review]
Awesome, looks great to me!

**Pull request merged**
