### PR TITLE
OKTA-642005 Global Session Policy default rule properties read-only

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Updated the Policy API and one guide with details on the `maxSessionLifetimeMinutes` and `usePersistentCookie` properties being read-only for the default policy's default rule
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* [OKTA-642005](https://oktainc.atlassian.net/browse/OKTA-642005)

### CODE REVIEW

**Review by brentschaus-okta — APPROVED** [review]
LGTM

**Comment by brianduffield-okta** [comment]
@petermiller-okta approved via Slack

**Pull request merged**
