### PR TITLE
Fix font weight

### PR DESCRIPTION
**Pull request by konstantin-sh-ram**

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/77d3c489762a63d1ccd97d8c1d276818950c4dd8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Femail-magic-links-overview%2Fmain%2Findex.md) | 73 | 97 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/44f36171-a152-4eef-9ee4-b19dfdbfbe26) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.f564c0ec-ff76-445d-9abd-7eea70a0611d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/e1ffa86f3c3d3174a01d612223754e4d13023398/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Femail-magic-links-overview%2Fmain%2Findex.md) | 73 | 97 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4db70bad-b855-472d-911d-bf7b850cf296) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.420a63c9-54f0-4206-9ed2-15c680224f3f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/67bdc2a515e96b3f9d6a5414b75031cd0ece8e1f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Femail-magic-links-overview%2Fmain%2Findex.md) | 73 | 97 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c23402b6-9d56-4cc7-b832-b9517656f99e) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.b5bd951d-9cc3-4b0c-aea5-c2bd5486acb7?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by shawyu-okta — APPROVED** [review]

**Pull request merged**
