### PR TITLE
testing new filter

### PR DESCRIPTION
**Pull request by susanharper-okta**
## Description:
- **What's changed?** testing new filter
- **Is this PR related to a Monolith release?** no

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024/index.md](https://github.com/okta/okta-developer-docs/blob/cb72cecc1cae7d32d5fd0636a7427573022382b2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/46106c79-c490-41d3-b954-b015d94f4735) | 62  | 51  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f67b0902-4a69-4cc2-b690-7e665282d192?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024/index.md](https://github.com/okta/okta-developer-docs/blob/0646f66f3737dbb18a9c724e095494aad4b78096/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/46684b6b-bead-4415-a455-2d80b00a65b8) | 62  | 51  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.75bc4713-ccb2-45a8-8b0c-b0a3811177d5?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024/index.md](https://github.com/okta/okta-developer-docs/blob/7ffbb364c64c2d0534c02880e4bf9ff2e6127eea/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7abb4fe9-200a-4dda-a319-e2ff645d1d83) | 62  | 51  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.307f63b7-52bf-442d-9871-502ed8fd0ecd?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024/index.md](https://github.com/okta/okta-developer-docs/blob/65b7829a046168f9db395726793c78906c34f664/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a115c5be-1387-4714-9be6-649958a6a308) | 62  | 51  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.be7988b9-70b4-4eee-b0f2-9d86b7a755a1?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024/index.md](https://github.com/okta/okta-developer-docs/blob/b029eee50833df2757ac7fd7a67001d050c76ff9/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a81a373d-00c7-43fb-9c7f-1771735f08f1) | 62  | 51  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7f4b09de-a2c4-4ad5-8a1b-eee3dae52973?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024/index.md](https://github.com/okta/okta-developer-docs/blob/9d7b007c76df4945fff2a5281cfc0ee0701982df/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fcee6130-cc22-4e44-88ea-18f9504b24ae) | 62  | 51  | 63  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.024c3057-5d0d-4715-b666-08c7332cd30e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by janethu-okta — APPROVED** [review]

**Review by janethu-okta — APPROVED** [review]

**Pull request merged**
