### PR TITLE
Update addconfigpkg.md

### PR DESCRIPTION
**Pull request by AndriiMaliuta**
* 'okta-spring-boot-starter' version upgrade
* Gradle example added

## Description:
Update addconfigpkg.md
* 'okta-spring-boot-starter' version upgrade
* Gradle example added

### CODE REVIEW

**Review by AndriiMaliuta — COMMENTED** [review]
Thanks for the updates

**Review by AndriiMaliuta — COMMENTED** [review]
Thanks for corrections

**Review by AndriiMaliuta — COMMENTED** [review]
Reviewed

**Comment by AndriiMaliuta** [comment]
> FYI @AndriiMaliuta ... just a few formatting updates; the snippet file was not building with the issues. Any issues, let me know.

Hi @brianduffield-okta ,
I submitted the suggested changes to branch patch-2

**Comment by brianduffield-okta** [comment]
Closing this PR. These additions were merged with https://github.com/okta/okta-developer-docs/pull/2818  Thank you, @AndriiMaliuta

**Pull request closed without merging**
