### PR TITLE
2024.04.0 - Release branch

### PR DESCRIPTION
**Pull request by brentschaus-okta**
## Description:
- **What's changed?** Adding release notes and docs for 2024.04.0
- **Is this PR related to a Monolith release?** Yes. 2024.04.0

### Resolves:

* [OKTA-713906](https://oktainc.atlassian.net/browse/OKTA-713906)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/955930b50cfb4a48232c209be27977ff10976ef0/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/de93318d-4ce6-4bec-aa1d-85ce86e6a8a2) | 68  | 84  | 66  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.deec03c4-ead9-4b30-9608-48ef2440f954?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/16860fc8399718db1c9654e8841b28e7a4becba4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/92460108-6a9d-4320-9d25-3f3bf03ef155) | 68  | 84  | 66  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.882a9714-c23b-47c7-9c44-3f4cfaca1823?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/2e971e6461bf5592c636e55e8856472e60f57e2a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b279e2da-8d97-4be7-94fa-36d525106e70) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/2e971e6461bf5592c636e55e8856472e60f57e2a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2daae4c6-e05d-42fa-9346-dc2dcecc7385) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.90bb937d-3523-4297-8b30-c079f95bb64c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/0b28df906e55c616da6981cf768a726b756236af/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a4e56a68-3dbe-421f-a3d4-32f3b24e4c28) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/0b28df906e55c616da6981cf768a726b756236af/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ed9dd263-c19b-4812-9c9b-170c5328b542) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5d7bdbc1-b288-4bd7-927f-4171967d66bc?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/4b093c808bfe788152f39f0e58df20d2f02f16d3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/eaa06dc5-bc5f-44da-a566-c9037cf7a09a) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/4b093c808bfe788152f39f0e58df20d2f02f16d3/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/97b557c6-bf58-4e3e-8514-f127a289392b) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c6681f16-d083-444f-90cc-5dc2f0cf5291?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/49be6cac2180841c6db7394056298af1e1e2dd3a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0492acdb-456e-41ed-8052-3a123d308721) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/49be6cac2180841c6db7394056298af1e1e2dd3a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8ffd541b-f6a1-47a0-b3e8-a7fcd0cc749c) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.99ae1b35-a7e7-4aa9-858d-e1aaa15d842c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/5fbf72f5d40afaef02a4c51db033120dfa32c26f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/acb2c030-b7a3-4c6a-84b0-80d57b252e49) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/5fbf72f5d40afaef02a4c51db033120dfa32c26f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/17ff1a20-d252-4d77-a69d-229f7f27c63b) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5b37993f-384e-4209-b266-4737e924fd8f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/636faac8ba488b601c0c90e39a33ecc85ead189d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f93f5d04-adb4-4d1c-b00b-e17f49195fb2) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/636faac8ba488b601c0c90e39a33ecc85ead189d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7c37d400-7c33-4ee2-8138-8dcd2d0bb0a9) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f5ecc7db-939f-4569-9378-e9befe0689bd?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/27cb9a396b1306a411b431e267fc806510d7d5e1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0d8ff9e2-9df1-4216-98d2-a4650fd56cc6) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/27cb9a396b1306a411b431e267fc806510d7d5e1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ae1e8a53-4c12-4265-8c1a-04dfbebbded4) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.81a2678b-b252-463d-8887-588cabef1398?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/6ef2e496f8f548d43a47f02ccaea13653321ed19/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9ab6f906-cfc1-4f70-9f74-a652d637e54a) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/6ef2e496f8f548d43a47f02ccaea13653321ed19/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d0e5db3a-d450-450c-8f40-edd46026d179) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0d397a23-9cce-4dab-9bee-8b4044ab06ae?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/a920152d638c10cff76cc7ecca91e02295ebfcc5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/12e578e7-8323-4f09-b9d7-2ccc36a85c4b) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/a920152d638c10cff76cc7ecca91e02295ebfcc5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8f13c7a1-06c4-4076-ac62-c354c6a60361) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0ac47330-6145-4961-9a45-1040f13b5825?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/149ea7cbcfe82f65a1c607c88981bd34cd4b42cb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e0e73e19-385a-4820-93c2-6c637e20f10d) | 68  | 84  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/149ea7cbcfe82f65a1c607c88981bd34cd4b42cb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/43307ed0-29a0-43bc-8803-7e240a39356e) | 94  | 80  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ac48a4c5-6192-4227-b9be-4d4a5c633a5b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Pull request merged**
