### PR TITLE
OKTA-688716 - Revise token hook guide

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Improve the usability of the [Token inline hook guide](https://developer.okta.com/docs/guides/token-inline-hook/nodejs/main/) and address a few procedural gaps. 
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* [OKTA-688716](https://oktainc.atlassian.net/browse/OKTA-688716)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/6a92dbc2ba536465bbc806eca1098188dd67b6cd/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Findex.md) | 82 | 60 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/92434801-a4de-4a3d-b0f5-a02547fa7ab4) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.20ef52b4-7413-4b8f-8671-8db8dd096de3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/235325ddc27a72efb309bf7f1b13ec02202f501a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Findex.md) | 82 | 63 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0d5f2fef-b905-4da0-9855-85c7db907eac) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/nodejs/request.md](https://github.com/okta/okta-developer-docs/blob/235325ddc27a72efb309bf7f1b13ec02202f501a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Fnodejs%2Frequest.md) | 90 | 7 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/568cd7f1-c2b5-4026-bce5-351add6c96f1) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.ba6ca47c-3679-44d1-b48a-f838a22bf4fc?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by barbaravo-okta — APPROVED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/0a79c3cc1da43160c7409b9e16b56ca71b1112ad/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/86a0df3a-0ee4-45cd-b5da-9762d7b8f566) | 85  | 78  | 67  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/nodejs/request.md](https://github.com/okta/okta-developer-docs/blob/0a79c3cc1da43160c7409b9e16b56ca71b1112ad/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Fnodejs%2Frequest.md) | [90](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d7daf946-7997-4759-a69d-ef27050b4395) | 100  | 100  | 34  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.8e6c9504-a821-4785-9cec-c8a7fd9578c9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/b6c9a9f79008129948dcf4284c6459190e0b5899/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c939aed5-d6a3-449c-9d15-e37b10fac827) | 85  | 78  | 67  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/nodejs/request.md](https://github.com/okta/okta-developer-docs/blob/b6c9a9f79008129948dcf4284c6459190e0b5899/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Fnodejs%2Frequest.md) | [90](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fee88922-8b4c-425e-b5cb-d52cd438a93d) | 100  | 100  | 34  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a5765429-a916-457c-9409-5ba4bc91bbbd?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Pull request merged**
