### PR TITLE
Multiple IDs API guide

### PR DESCRIPTION
**Pull request by brentschaus-okta**
## Description:
- **What's changed?** Adds a multiple identifier API guide
- **Is this PR related to a Monolith release?** Yes. 2024.11.0

### Resolves:

* [OKTA-708004](https://oktainc.atlassian.net/browse/OKTA-708004)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/a721c0d2f70accac370216220ab1ecbec85396e8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/191171a1-7db1-4c96-9f90-0c1b7ab4f48a) | 50  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md](https://github.com/okta/okta-developer-docs/blob/a721c0d2f70accac370216220ab1ecbec85396e8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c9c8d987-2e33-49b2-9ec0-3060eaa59d66) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md](https://github.com/okta/okta-developer-docs/blob/a721c0d2f70accac370216220ab1ecbec85396e8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Fmain%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7acf6e90-3e17-4488-8946-78dcc2368eae) | 44  | 93  | 57  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a809b5ac-ef61-48d5-b978-94e015917fc7?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/555add4cdd86c3fb180c395b8720719062c6b49d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/643b012d-cc54-4342-9b2f-013cc9878cc9) | 50  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md](https://github.com/okta/okta-developer-docs/blob/555add4cdd86c3fb180c395b8720719062c6b49d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/598b2a38-f17f-4742-ba91-55143cdf3a25) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md](https://github.com/okta/okta-developer-docs/blob/555add4cdd86c3fb180c395b8720719062c6b49d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Fmain%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/483ba404-729a-4e00-a835-2cc4e91574f7) | 46  | 87  | 58  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.fd5b1dce-477e-415b-a64a-e6d680af2aec?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/32762958c4c48433a84d891ee0c4cbc3b34d6e78/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dcacc0e5-e3f1-40f1-8201-d1404d38c11a) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md](https://github.com/okta/okta-developer-docs/blob/32762958c4c48433a84d891ee0c4cbc3b34d6e78/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/25f66332-631e-436b-b610-65df306c5609) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md](https://github.com/okta/okta-developer-docs/blob/32762958c4c48433a84d891ee0c4cbc3b34d6e78/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Fmain%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bb433f79-b524-47b2-8796-5444e8cba0e7) | 46  | 87  | 58  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.1473a182-33ee-4254-a737-7bc6f17cb1ee?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/37aa3f5b2796f05aad33104d4e92c0aaf7af46a5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bc4b2518-b301-4d23-8ec9-3c8f0558397a) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md](https://github.com/okta/okta-developer-docs/blob/37aa3f5b2796f05aad33104d4e92c0aaf7af46a5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a1443d8b-6ad9-40c1-950d-ba60e63f1cdd) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md](https://github.com/okta/okta-developer-docs/blob/37aa3f5b2796f05aad33104d4e92c0aaf7af46a5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/860cfe5e-6593-4839-9e54-e37edaa7d44a) | 46  | 87  | 73  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b8910ca7-24e5-4dcb-ac86-5357f5b2d01e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/e220c72ea8e21ece1e1184b4eda730a2419245e6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/40e32cff-0cea-4b24-b17a-0b7a62cf7488) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md](https://github.com/okta/okta-developer-docs/blob/e220c72ea8e21ece1e1184b4eda730a2419245e6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e4dd7272-ecf7-45a5-a720-43a90038bfb5) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md](https://github.com/okta/okta-developer-docs/blob/e220c72ea8e21ece1e1184b4eda730a2419245e6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7a0c50cb-c42f-45de-b5af-1e15acc896e8) | 47  | 88  | 74  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.9b524d99-8387-4fa0-9a14-28e61dfefb0c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/c2ecd50302dc254d7ead4937822d1546b5c44780/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fef34632-7615-4613-9c7d-b8cb37926833) | 56  | 56  | 87  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/index.md](https://github.com/okta/okta-developer-docs/blob/c2ecd50302dc254d7ead4937822d1546b5c44780/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3477e183-b0ac-49a2-b9f3-0542f6cd45c4) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/multiple-identifiers/main/index.md](https://github.com/okta/okta-developer-docs/blob/c2ecd50302dc254d7ead4937822d1546b5c44780/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmultiple-identifiers%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/97a7d32e-a082-425a-8bff-b8cc6e8eb947) | 47  | 88  | 74  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0257208a-363c-4b05-a2fa-a97aff065c7d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Pull request merged**
