### PR TITLE
OKTA-822501 - Add account linking condition features

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Update automatic account linking for OIDC and SAML generic IdPs
- **Is this PR related to a Monolith release?** Yes, 2024.12.0

### Resolves:

* [OKTA-822501](https://oktainc.atlassian.net/browse/OKTA-822501)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/4f5a9fb44acd496903eac308dc803242c73b29fa/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1a9364c0-c812-4142-8595-ef45ce61eb0b) | 60  | 78  | 64  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/4f5a9fb44acd496903eac308dc803242c73b29fa/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/18f81b9a-35c6-40f4-a28a-eed14a49f218) | 51  | 71  | 65  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.9294e03c-5163-470a-96bf-3aa668a2e06d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/06ac1679ee67f53dcc5398347dea6cbe72107426/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d7672928-237f-4107-8db3-f879eb93605a) | 66  | 80  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/06ac1679ee67f53dcc5398347dea6cbe72107426/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fc9c050a-61c2-42be-9945-e28b4ca07812) | 60  | 78  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/06ac1679ee67f53dcc5398347dea6cbe72107426/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6c4c7b08-d341-49b5-a744-49dfe067cfb8) | 51  | 71  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ca2b7a18-0d25-41bd-af16-882ec022704c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — DISMISSED** [review]
LGTM

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/1a3568d13a083f95a1584545a4675c610058dd0a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a6ef5f8b-8a1f-4c58-860d-949469b68894) | 66  | 80  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/1a3568d13a083f95a1584545a4675c610058dd0a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4f2e897c-8e16-4299-b6a3-eb4eb64e98a2) | 60  | 78  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/1a3568d13a083f95a1584545a4675c610058dd0a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e55f0ee4-27ba-46c5-84f3-5dcbd41e1e4c) | 51  | 71  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.062df1b3-3435-4e8f-9d9e-1f06fe1cd657?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7c65d17ccfc292345ef2e0e97c02ce2fed9aef5e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fazure%2Fafterappidpinokta.md) | [96](https://okta.acrolinx.cloud/api/v1/checking/scorecards/019dfb9c-4c32-44bd-8765-3cdf0aeca975) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7c65d17ccfc292345ef2e0e97c02ce2fed9aef5e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fazure%2Fappidpinokta.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ecb6ef88-1520-44ef-aa6a-5d8984a45786) | 37  | 73  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7c65d17ccfc292345ef2e0e97c02ce2fed9aef5e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fafterappidpinokta.md) | [96](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0626a987-18b1-4c03-aa4c-64419800a940) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7c65d17ccfc292345ef2e0e97c02ce2fed9aef5e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cf6387ce-8207-4bba-8527-e8c6d60fa2aa) | 66  | 80  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7c65d17ccfc292345ef2e0e97c02ce2fed9aef5e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fafterappidpinokta.md) | [97](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f7c42a44-212d-44f5-be5e-7baf15801f0e) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7c65d17ccfc292345ef2e0e97c02ce2fed9aef5e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2ea085f6-aa1b-41dc-b92e-edb23226908b) | 60  | 78  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7c65d17ccfc292345ef2e0e97c02ce2fed9aef5e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2bd4c962-c9a5-43c5-8f3c-df7ffe82d687) | 51  | 71  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.abf0e2ee-6116-40cb-ae16-610615c60c32?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — COMMENTED** [review]
two comments

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/8b42e2db78871b6ddf9f4e6e531a1ddfafd432ba/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fazure%2Fafterappidpinokta.md) | [96](https://okta.acrolinx.cloud/api/v1/checking/scorecards/386a353a-ae9e-4a91-ac8e-3a8c0d1b605d) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/8b42e2db78871b6ddf9f4e6e531a1ddfafd432ba/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fazure%2Fappidpinokta.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a4679018-5158-4dfe-b67a-c184ec247c57) | 37  | 73  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/8b42e2db78871b6ddf9f4e6e531a1ddfafd432ba/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fafterappidpinokta.md) | [96](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dd61337c-965d-4008-ad0b-0df6517886e7) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/8b42e2db78871b6ddf9f4e6e531a1ddfafd432ba/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d6d05bde-112f-403a-bab1-9850f1bfb5f2) | 66  | 80  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/8b42e2db78871b6ddf9f4e6e531a1ddfafd432ba/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fafterappidpinokta.md) | [97](https://okta.acrolinx.cloud/api/v1/checking/scorecards/19720a62-3299-4cc0-ad72-d1849ed6b5d5) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/8b42e2db78871b6ddf9f4e6e531a1ddfafd432ba/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7152d246-eca6-4a5d-94a1-9997b9c6b8b6) | 60  | 78  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/8b42e2db78871b6ddf9f4e6e531a1ddfafd432ba/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2d033479-be28-4088-a729-eeaa861dbaf4) | 51  | 71  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.63f80aff-4bd4-4005-9f0e-f581dc853c9a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/2cd83964215f37f28b33a099c6b5fb042bc33a27/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fazure%2Fafterappidpinokta.md) | [96](https://okta.acrolinx.cloud/api/v1/checking/scorecards/39526039-ecf7-4b52-a2cb-100d59f5fcae) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/2cd83964215f37f28b33a099c6b5fb042bc33a27/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fazure%2Fappidpinokta.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/677799af-8fc9-4562-aefb-20fa909eee03) | 37  | 73  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/2cd83964215f37f28b33a099c6b5fb042bc33a27/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fafterappidpinokta.md) | [96](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6c93d924-3e82-4688-ad77-6a7a720270cb) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/2cd83964215f37f28b33a099c6b5fb042bc33a27/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/60a5dd63-99d9-47c2-bbf1-7683f9ab3a92) | 66  | 80  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md](https://github.com/okta/okta-developer-docs/blob/2cd83964215f37f28b33a099c6b5fb042bc33a27/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fafterappidpinokta.md) | [97](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2d87df40-9a30-4f29-8550-461730ca1aef) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/2cd83964215f37f28b33a099c6b5fb042bc33a27/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/792b6f96-a8eb-4512-b33f-201f411e5105) | 60  | 78  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/2cd83964215f37f28b33a099c6b5fb042bc33a27/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/457f8e81-9297-467b-ae16-d57058ef7814) | 51  | 71  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.91d6fe10-826f-49cd-a2e7-919ccd52552d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — APPROVED** [review]
lgtm

**Pull request merged**
