### PR TITLE
BD - Fix broken anchor link

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Fixed broken anchor link to Basic Auth
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* n/a

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md](https://github.com/okta/okta-developer-docs/blob/7c471f80291d46a56bfe94a03b7131f6f429317e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fevent-hook-hookdeck%2Fmain%2Findex.md) | [67](https://okta.acrolinx.cloud/api/v1/checking/scorecards/06434b55-0e16-45d1-ad27-7e70726104fe) | 95  | 25  | 43  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.2b8c598e-5630-442c-852d-9f4e233b8bb1?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md](https://github.com/okta/okta-developer-docs/blob/f74c229f80146615fd8931d59cb294fd59e6df57/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fevent-hook-hookdeck%2Fmain%2Findex.md) | [67](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1488672c-df0e-478b-aa1b-5177a23dc8ea) | 95  | 25  | 45  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.b9f2496a-d040-43fa-bdf1-d08b3b684695?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md](https://github.com/okta/okta-developer-docs/blob/171202c4446d7bd3661f0767a138a3c4eddd0b4b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fevent-hook-hookdeck%2Fmain%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/86211299-9c5f-4791-b894-808a41e6c2f5) | 95  | 28  | 72  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.c605c798-e3fe-41da-99a0-5bc58736a7ab?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by danielmaharry-okta — APPROVED** [review]
Looks good to me!

**Pull request merged**
