### PR TITLE
chore(docs): Update README

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Description:

Changes to the main repo README.

- **What's changed?** 
  - Removes a now-outdated TravisCI build status shield which was deprecated via https://github.com/okta/okta-developer-docs/pull/3816.  TravisCI hasn't been run in 2 years. Repo seems to have both CircleCI and Github Actions, so either build shields could be added back for those w/ write access to the repo and pipelines.
  - Removes the bad image which is coming from a CDN; not sure what to replace it with, but easy for anyone to add back if they know its source. (maybe company logo?)
- **Is this PR related to a Monolith release?** 
  - No.

Note: As an open source contributor, I've not signed the [Okta CLA ](https://developer.okta.com/cla/) but this should fall in the "obvious fix" category meaning that's not necessary.

### Screenshots

| Before | After |
| --- | --- |
|  image  |  image |

### CODE REVIEW

**Comment by adamdmharvey** [comment]
cc @joedelnano-okta

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [README.md](https://github.com/okta/okta-developer-docs/blob/fea65659de745b1a93b65a0e07b22c28952a2796/README.md) | [73](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5abfc7eb-e51a-40f1-bde0-8f6c40b95b31) | 63  | 100  | 36  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a8e14632-e601-4a4e-b5e5-1858bde5d078?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by brianduffield-okta** [comment]
@adamdmharvey Thanks for this update, as well. We should be able to merge this one.

**Review by emikhasyak-okta — APPROVED** [review]
LGTM!

**Pull request merged**
