### PR TITLE
Add note for scope size limitation while requesting offline_access

### PR DESCRIPTION
**Pull request by amirbeygi-okta**
## Description:
- Add a note for `scope` size limitation while request includes `offline_access` scope

### Resolves:

* [OKTA-423280](https://oktainc.atlassian.net/browse/OKTA-423280)

### CODE REVIEW

**Comment by amirbeygi-okta** [comment]
image

**Review by susanharper-okta — APPROVED** [review]
pulled down locally, built and took a look. then made some changes based on the content. I approve these changes. haha :)

**Comment by shantanusardal-okta** [comment]
should we also include the note here - https://developer.okta.com/docs/reference/api/oidc/#scopes or https://developer.okta.com/docs/reference/api/oidc/#subtle-behavior ?

**Review by shantanusardal-okta — APPROVED** [review]
🚢

**Pull request merged**
