### PR TITLE
[OKTA-727700] Fixed odyssey icons in dark theme

### PR DESCRIPTION
**Pull request by ishan-krishna-okta**
## Description:
- **What's changed?** Fixes odyssey icons in dark theme
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-727700](https://oktainc.atlassian.net/browse/OKTA-727700)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/0ce0b9a9f8281d22c6b76610d3491071931f64d9/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fc072291-1b7f-4f03-933f-fbb0a14933fb) | 86  | 90  | 69  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.eaf428f9-9f34-4e2a-b7c0-81137845245d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by emikhasyak-okta — COMMENTED** [review]
Great job and good approach!
One request is to remove `-odys` part from file names, so that files will match the source https://github.com/okta/odyssey/tree/main/packages/odyssey-icons/src/figma.generated

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/b0f5658817d36014f3c9aa77d4c9266f89d185f1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9f338514-b631-41e6-a749-2281bef76b6d) | 86  | 90  | 69  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e6e6df8b-2647-4179-b3dd-cf0e8fb31d1a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by ishan-krishna-okta** [comment]
> Great job and good approach! One request is to remove `-odys` part from file names, so that files will match the source https://github.com/okta/odyssey/tree/main/packages/odyssey-icons/src/figma.generated

Done.

**Review by emikhasyak-okta — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
