### PR TITLE
OKTA-645321 Revise registration inline hook guide

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Broke out three scenarios for ease of implementation.
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* [OKTA-645321 ](https://oktainc.atlassian.net/browse/OKTA-645321 )

### CODE REVIEW

**Comment by brianduffield-okta** [comment]
On hold to confirm UI/feature changes to SSR and PP

**Review by brentschaus-okta — APPROVED** [review]
LGTM!

A clear way to construct the guide with all that's involved in a reg inline hook

**Pull request merged**
