### PR TITLE
Added redesigned banner for Developer Day

### PR DESCRIPTION
**Pull request by AndriiDovhopolov-okta**
## Description:
- **What's changed?** Added redesigned banner
Mobile: 
image
Desktop: 
image

- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-414499](https://oktainc.atlassian.net/browse/OKTA-414499)

### CODE REVIEW

**Comment by volodymyrmakarchuk-okta** [comment]
Could you please prepare netlify build?

**Review by volodymyrmakarchuk-okta — COMMENTED** [review]
Could you please prepare netlify build?

**Review by albertchen-okta — CHANGES_REQUESTED** [review]
looks like Events team wants the text to be "Join us virtually for Developer Day
on August 24, 2021" to replace "Join us for a day of celebrating developers around the world."

**Review by albertchen-okta — APPROVED** [review]

**Review by chrisdmills-okta — COMMENTED** [review]
On the desktop/wide screen version, the "Register" link looks kinda small and crappy. Wouldn't it be better to make it a bit bigger, to increase the chance of people noticing it, and align it with the center of the text lines to the left of it?

**Review by alexdahl-okta — APPROVED** [review]

**Review by robertnicolo-okta — CHANGES_REQUESTED** [review]
A couple of items:

1.  On my 1920 x 1080 display the top right X is faded out and doesn't work.
image

2. When I shrink down the screen size the top right x appears but it doesn't seem to work.
image

3. The mockups (https://www.figma.com/file/Lg1ujrPOv08qKgc8QgRvGv/Developer-Day?node-id=469%3A1833) show a different rendering with okta/auth0 elements and other changes. I like to compare the banner with a mockup to gauge accuracy. Do you know which banner mockup you used?
4. Responsiveness issues: Resize down the screen (relevant for smaller displays and mobile clients) the right image flips upside down.
image

**Comment by AndriiDovhopolov-okta** [comment]
@robertnicolo-okta there is a Jira ticket in description. I've used provided designs. Thanks for pointing out to close button issue.

**Comment by shawyu-okta** [comment]
@AndriiDovhopolov-okta a few things:

1. I still see the flipping image issue when moving from desktop to mobile although that seems to be what is shown in the mocks, so maybe this is OK.
2. The 'X' changes from gray to white when moving from desktop to mobile
3. The 'X' should be smaller in mobile view, according to the mocks
2. It looks like the text is different between desktop and mobile. Can you make sure they are consistent?
3. The mocks show slightly different copy for the title. Tt says "Auth for All" instead of "Developer Day"
4. The mocks look like they show the "Register" link as a teal color, is that what it should be?

**Comment by AndriiDovhopolov-okta** [comment]
@shawyu-okta 
https://60fe857fc644f0e7952957bb--reverent-murdock-829d24.netlify.app

- Text is already corrected due to mocks. 
- "Developer Day" is made instead of "Auth for all" by request of @albertchen-okta 
- Will fix the X
- Not sure about teal color, looks white to me and colorpicker
image

**Comment by AndriiDovhopolov-okta** [comment]
Last Version
https://610013685074ef1bcf7457b3--reverent-murdock-829d24.netlify.app

**Comment by shawyu-okta** [comment]
Thanks for making changes -- Small nit but I think it will be nice to change: The "Register" text and the chevron can break across lines at a certain window size. If we use a `&nbsp;` between them instead of a space it will force them to stay together:
image

I also still see the copy between the mobile and desktop versions are different (see this image compared to the first one):
image

**Review by albertchen-okta — APPROVED** [review]

**Review by robertnicolo-okta — APPROVED** [review]
lgtm

**Review by shawyu-okta — APPROVED** [review]

**Pull request merged**
