### PR TITLE
Updating False Positives list

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Added two links to the false-positive list. No broken links.
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* n/a

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [falsepos.txt](https://github.com/okta/okta-developer-docs/blob/60347d84dc9f6d6eac46226b8eedfd66b66d6f6a/falsepos.txt) | 72 | 14 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/71d5c5bd-4773-4b48-9361-db3ec51c1836) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.2e4812c6-2850-49b6-9f37-fec3aec7cf6e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by emikhasyak-okta — APPROVED** [review]
LGTM!

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [falsepos.txt](https://github.com/okta/okta-developer-docs/blob/973ea2b463708463f675b4f99e0cdda56ff33524/falsepos.txt) | 71 | 13 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e7be3674-a334-43f3-ac03-90fa7edf0b21) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/sdksteps.md](https://github.com/okta/okta-developer-docs/blob/973ea2b463708463f675b4f99e0cdda56ff33524/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fandroid%2Fsdksteps.md) | 83 | 32 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/eaf4230a-656e-4d04-954c-70222aee48cf) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/sdksteps.md](https://github.com/okta/okta-developer-docs/blob/973ea2b463708463f675b4f99e0cdda56ff33524/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fios%2Fsdksteps.md) | 78 | 73 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/217ef649-414a-4fdc-a904-5d327889bc51) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 3 of 3 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.420eaaff-eac6-46ca-aa4f-a767ebce1935?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by brianduffield-okta** [comment]
Updated links to a more user-friendly URL; removed the url that was flagged as broken from falsepos.txt file.

**Pull request merged**
