### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by jprempeh**
Update misspelling

## Description:
- **What's changed?** A simple misspelling of `yourOktaDomian` to `yourOktaDomain`
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md](https://github.com/okta/okta-developer-docs/blob/d125c50f28abc8ed6fb186e3480e31b3e7164e47/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fauth-servers%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0fcd4502-7892-45bc-845b-0929356fbf4e) | 47  | 86  | 40  | 96  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.ad9764d0-4ec7-4130-a8fa-ddea35cb19fe?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by brianduffield-okta** [comment]
Thanks for catching that, @jprempeh

**Review by brianduffield-okta — APPROVED** [review]
LGTM!

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md](https://github.com/okta/okta-developer-docs/blob/d125c50f28abc8ed6fb186e3480e31b3e7164e47/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fauth-servers%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8cd0c496-9197-4e51-b5c9-62d6e3e7a594) | 47  | 86  | 40  | 96  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.9084afce-629d-41f3-befb-a5f3a61cb029?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Pull request merged**
