### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by martyngroberts**
## Description:
Replace addTokens() with tokenManager.add()

##Resolves
Solves current issue in sample code shown here - https://developer.okta.com/code/javascript/okta_sign-in_widget/#spa-or-native-application-using-pkce

### CODE REVIEW

**Comment by aarongranick-okta** [comment]
@martyngroberts What version of the widget are you using? The guide is written for the latest version of the widget, which is using a recent version of `okta-auth-js` for the `authClient`.  The tokens are returned by the widget, but saving them is the job of the authClient. The flow from the widget is similar to that shown here: https://github.com/okta/okta-auth-js#example

**Comment by martyngroberts** [comment]
@aarongranick-okta the error for setTokens appears when using the HTML sample code provided on the page.    There is a CDN ref to the latest sign-in widget (currently https://global.oktacdn.com/okta-signin-widget/5.1.5/js/okta-sign-in.min.js)

**Comment by aarongranick-okta** [comment]
The `setTokens` method exists on the `TokenManager`. `oktaAuth.tokenManager.setTokens(tokens)` should work.  We will get this fixed. Thanks for bringing it to our attention @martyngroberts !

internal ref: OKTA-381175

**Comment by brianduffield-okta** [comment]
The dev docs page appears to be updated with the required content: https://developer.okta.com/code/javascript/okta_sign-in_widget/#sign-in-and-display-user-s-email.  Will confirm and close PR.

**Comment by brianduffield-okta** [comment]
Closed as per @aarongranick-okta Thanks.

**Pull request closed without merging**
