### PR TITLE
OKTA-830415 Updates for migrated SCIM integrations

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?**Update OIN docs for migrated SCIM integrations
- **Is this PR related to a Monolith release?** Yes, after 2024.11.0. 2024-11-14: OK12 deployed with SCIM in OIN Wizard. 2024-11-15: OIN Ops reject new SCIM submissions.

### Resolves:

* [OKTA-830415](https://oktainc.atlassian.net/browse/OKTA-830415)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/2822e2dbb2a29fc8d1edd8444f1c46ec2f815c49/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1d436cae-3ff1-4cea-b37a-22ac808a5d77) | 63  | 95  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/2822e2dbb2a29fc8d1edd8444f1c46ec2f815c49/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/957be6b9-3e50-4781-b63c-afc4628c6c35) | 44  | 86  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/2822e2dbb2a29fc8d1edd8444f1c46ec2f815c49/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/840e6aa9-176e-494a-88b0-3f35d51bd000) | 73  | 83  | 73  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/2822e2dbb2a29fc8d1edd8444f1c46ec2f815c49/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/906d7468-a7c3-4550-a045-610d194029d8) | 76  | 86  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.bf71c416-5e37-4556-afce-b68e0fa16cb8?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/1937c3dc4c2824e74c576ef904e39c406897d610/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/edcbdf8e-5653-4a3f-9e44-e87879e293ad) | 63  | 95  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/1937c3dc4c2824e74c576ef904e39c406897d610/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/36debc5c-e99b-403d-8dec-63dc432b3284) | 44  | 86  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/1937c3dc4c2824e74c576ef904e39c406897d610/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7f071363-8d5b-4ab7-bc33-6e8a17dc3eb2) | 73  | 83  | 72  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/1937c3dc4c2824e74c576ef904e39c406897d610/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/069bb885-b1c4-46f9-ab41-0c25f31074d5) | 76  | 86  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.4cbcc2c0-fa6d-4069-9c86-6d50cf5a3542?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/8dff6b90cb386b820e71c6085793d3c98d8f76e6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/93032f0d-d0ab-4efc-8b09-1fce5c6bf6f7) | 63  | 95  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/8dff6b90cb386b820e71c6085793d3c98d8f76e6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ad2eb825-2579-4b47-b116-6c1dfad7e865) | 44  | 86  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/8dff6b90cb386b820e71c6085793d3c98d8f76e6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/31f34539-127e-4622-aa84-1b0fba049af3) | 74  | 83  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/8dff6b90cb386b820e71c6085793d3c98d8f76e6/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/652bf5fc-d34b-443e-b21f-230ae21025d9) | 76  | 86  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.67dc5b96-b980-48f2-b714-64c2efeb094c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/c423c8ef36f98b426cbefb75d3594df3f8c111bf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8c217af5-cc41-48d6-839f-4297a4ee747b) | 63  | 95  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/c423c8ef36f98b426cbefb75d3594df3f8c111bf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/26bdac1e-fb50-42ad-b565-64b38d57df62) | 44  | 86  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/c423c8ef36f98b426cbefb75d3594df3f8c111bf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3ddab115-93ba-491a-9f58-97778b116cb7) | 74  | 83  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/c423c8ef36f98b426cbefb75d3594df3f8c111bf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ac3a0662-6ef3-4dd9-9cff-6bfec956c2a0) | 76  | 86  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3ebe3ee9-7332-48db-bef1-4b16ac2b974a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/b4a68ef74341f421d74cdeee98da104dae8c684f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6d45ccf3-8c0c-490c-b82d-c881c08a4eaf) | 63  | 95  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/b4a68ef74341f421d74cdeee98da104dae8c684f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b70f15b5-6307-449c-972b-9ff01fbfd2ad) | 44  | 86  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/b4a68ef74341f421d74cdeee98da104dae8c684f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e1361e92-a828-4c3d-af40-c5f5a5e3d265) | 74  | 83  | 73  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/b4a68ef74341f421d74cdeee98da104dae8c684f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0fda3b86-a250-4e6c-8a55-644c1e2577cc) | 76  | 86  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e46c5bd9-3cdb-4cf1-975d-002c8f1f4468?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/f6256e4c8b3e7a6e971334e0951a273a8fdf58b1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2ec0b2b6-41a9-4054-b75a-5824e89ea924) | 63  | 95  | 68  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/f6256e4c8b3e7a6e971334e0951a273a8fdf58b1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9be5cd55-b7bd-462d-9c33-c5926b5a9b23) | 44  | 86  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/f6256e4c8b3e7a6e971334e0951a273a8fdf58b1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9df924ba-b326-42f9-8534-fddadcc476ad) | 74  | 83  | 73  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/f6256e4c8b3e7a6e971334e0951a273a8fdf58b1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6ddbbf88-5b9e-49ac-81f4-b34aeb462c69) | 76  | 86  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.2ab94c80-4694-4fb9-847d-edc312f96eb1?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Pull request merged**
