### PR TITLE
Release 2023.05.2

### PR DESCRIPTION
**Pull request by susanharper-okta**
## Description:
- **What's changed?** Release 2023.05.2
- **Is this PR related to a Monolith release?** Yes. Release 2023.05.2

### Resolves:

* [OKTA-611819](https://oktainc.atlassian.net/browse/OKTA-611819)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/173ecad40924fa963950ed9d261529a5aaf4524a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/58dc8e66-b12d-4908-b52d-c15a8505004d) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/173ecad40924fa963950ed9d261529a5aaf4524a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a2946f20-2d74-4f7e-bec7-d31714e07a95) | 80  | 73  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/173ecad40924fa963950ed9d261529a5aaf4524a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/405971f6-70bf-4bba-aec7-2d411379f27a) | 61  | 76  | 61  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/173ecad40924fa963950ed9d261529a5aaf4524a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/520d55d6-3b5b-41e8-bd9c-2c9aced475a3) | 42  | 77  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/idps/index.md](https://github.com/okta/okta-developer-docs/blob/173ecad40924fa963950ed9d261529a5aaf4524a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fidps%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a431346f-68fb-4378-a067-7a0363a92a9e) | 52  | 79  | 71  | 75  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md](https://github.com/okta/okta-developer-docs/blob/173ecad40924fa963950ed9d261529a5aaf4524a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023-okta-identity-engine%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/64ac8a73-c87a-4eff-983c-8ccdf68f5197) | 40  | 80  | 48  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023/index.md](https://github.com/okta/okta-developer-docs/blob/173ecad40924fa963950ed9d261529a5aaf4524a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023%2Findex.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b03bebb2-8fc5-43fb-99e2-505ef548d040) | 46  | 83  | 46  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.3b5aa3a2-e968-400f-9d49-58226b310fca?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by vanngo-okta — APPROVED** [review]
Do we need to add feature Jira ticket as a comment for new features? 
Otherwise, LGTM 🚢

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/1212708d73003c3a83280f30ad7f0e852ffd5652/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7e85a32d-8e4c-4576-8078-921a6384918f) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/1212708d73003c3a83280f30ad7f0e852ffd5652/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c98a53e0-8fd3-4fb6-be8f-fcc969700b10) | 80  | 73  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/1212708d73003c3a83280f30ad7f0e852ffd5652/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a839c389-128b-418b-b292-ea188befc2f6) | 61  | 76  | 61  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/1212708d73003c3a83280f30ad7f0e852ffd5652/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3f8edd19-f19e-4f33-a3c0-543ddf04eb64) | 42  | 77  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/idps/index.md](https://github.com/okta/okta-developer-docs/blob/1212708d73003c3a83280f30ad7f0e852ffd5652/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fidps%2Findex.md) | [68](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d8862851-32e0-4e5a-8bae-ad3bf43b6dfd) | 52  | 79  | 71  | 75  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md](https://github.com/okta/okta-developer-docs/blob/1212708d73003c3a83280f30ad7f0e852ffd5652/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023-okta-identity-engine%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1d1f3c78-3337-4bf8-9e96-5eed4b389a48) | 40  | 80  | 48  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023/index.md](https://github.com/okta/okta-developer-docs/blob/1212708d73003c3a83280f30ad7f0e852ffd5652/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023%2Findex.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2282920d-a1d0-4d40-be1e-5ca6de72c3c5) | 46  | 83  | 46  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.af5d2bc1-280e-4801-9cd1-32f521501b3c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/ba5f13979168a39e40db3a9367ce9bd34850dcb8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/279c6288-2f1f-4e49-ab50-97886d26122c) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/ba5f13979168a39e40db3a9367ce9bd34850dcb8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/65ae0b9c-f175-432b-8504-ca777ca1ada9) | 80  | 73  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/ba5f13979168a39e40db3a9367ce9bd34850dcb8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/35ec516a-6ae8-4b75-81a5-c7c471ea846f) | 61  | 76  | 61  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/ba5f13979168a39e40db3a9367ce9bd34850dcb8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2fe6585b-34ed-42e6-a1d5-957501c5d430) | 42  | 77  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/idps/index.md](https://github.com/okta/okta-developer-docs/blob/ba5f13979168a39e40db3a9367ce9bd34850dcb8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fidps%2Findex.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/487a4378-d290-40f9-8db1-7dfa17e78ffb) | 53  | 80  | 77  | 75  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md](https://github.com/okta/okta-developer-docs/blob/ba5f13979168a39e40db3a9367ce9bd34850dcb8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023-okta-identity-engine%2Findex.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c5b461f5-becb-407a-be6f-634a89bd93fd) | 40  | 83  | 49  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2023/index.md](https://github.com/okta/okta-developer-docs/blob/ba5f13979168a39e40db3a9367ce9bd34850dcb8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023%2Findex.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/acdd6fd2-9646-4863-9023-15855149bee2) | 46  | 83  | 46  | 100  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.b4cd8612-813a-41d2-b0a9-4af39acdddda?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Pull request merged**
