### PR TITLE
OKTA-571460 Updates to User Types API

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** As per slack/jira discussions, made the following updates:
   - Added request parameters for Create User Type operation, including expanded definition for `name` parameter.
   - Split out Update User Type operations (PUT/POST) into two separate operations, each with explicit request parameters and examples
   - Updated response examples to match requests

- **Is this PR related to a Monolith release?** n/a

### Resolves:

* [OKTA-571460](https://oktainc.atlassian.net/browse/OKTA-571460)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/user-types/index.md](https://github.com/okta/okta-developer-docs/blob/c0ebf8076f3dd7759fef4f33e9b7cc52af0b8a1e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fuser-types%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/425805e3-d482-4e4b-82d9-03251f386927) | 92  | 79  | 74  | 68  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.751a9229-4334-4119-9894-b7c81c068a45?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/api/user-types/index.md](https://github.com/okta/okta-developer-docs/blob/a1b7617d135eae8a610a0323abd1df994f8b4553/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fuser-types%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/82243cf5-9054-4fd9-bd0a-a750919cac6a) | 92  | 79  | 74  | 68  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.b00bf8ea-ae13-4af3-b995-032f2dd9c402?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by mingchili-okta — APPROVED** [review]

**Review by brentschaus-okta — COMMENTED** [review]
LGTM!

nicely done

**Pull request merged**
