### PR TITLE
OKTA-809675 Remove SCIM from OIN Manager

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Remove SCIM content from OIN Manager docs after the SCIM tab is removed from OIN Manager.
- **Is this PR related to a Monolith release?** No. Publish when the OKTA-829667 task is done.

### Resolves:

* [OKTA-809675](https://oktainc.atlassian.net/browse/OKTA-809675)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/index.md](https://github.com/okta/okta-developer-docs/blob/c7175acef541a58dd9252ba6e8274298d93c2476/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3725f2ac-b3c1-488a-ba38-f17cf0025634) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/c7175acef541a58dd9252ba6e8274298d93c2476/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9bd997e5-1a07-495f-8337-be9328fd2925) | 75  | 89  | 74  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3bfb0c79-0976-4f9b-9ffb-afd80cbbd50f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/5ad4a9ffe7fe1670bf5fdc6a99081e2b7b018341/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/900647b8-42a6-4f1b-b486-b9a60a3d1a19) | 81  | 87  | 62  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/index.md](https://github.com/okta/okta-developer-docs/blob/5ad4a9ffe7fe1670bf5fdc6a99081e2b7b018341/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4189508d-7ba3-410f-bc27-816e668574fb) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/5ad4a9ffe7fe1670bf5fdc6a99081e2b7b018341/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/39475a3f-eb84-4bd1-b62f-d5be23624997) | 81  | 88  | 74  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/wfconnector/protocol-name.md](https://github.com/okta/okta-developer-docs/blob/5ad4a9ffe7fe1670bf5fdc6a99081e2b7b018341/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Fwfconnector%2Fprotocol-name.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/94778b90-a971-40b6-b091-1a3e547bf07e) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.efd3b4fe-4bc3-4838-977e-2adf8d848c06?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/ab30f70294e1adf3c2a52c88e5792c3b6ded77f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2037e479-4d1e-45cc-a160-13d43a8d4745) | 81  | 87  | 62  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/index.md](https://github.com/okta/okta-developer-docs/blob/ab30f70294e1adf3c2a52c88e5792c3b6ded77f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d4fd0db2-09ee-4c70-91a6-36b472bdc1a7) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/ab30f70294e1adf3c2a52c88e5792c3b6ded77f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/85bad3b5-3c3e-4f14-ac0c-befa1e9bf53b) | 84  | 88  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/wfconnector/protocol-name.md](https://github.com/okta/okta-developer-docs/blob/ab30f70294e1adf3c2a52c88e5792c3b6ded77f5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Fwfconnector%2Fprotocol-name.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/913a770a-e6c4-43b8-bc09-05447b58ddc1) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a333db05-0ff5-4df9-a17b-66d486bce07a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/5dc7485b4d31c32f7ba98549f1ac06c6ea6d0271/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4b3e678a-9d73-4528-a4be-41aa67c18bb2) | 81  | 87  | 62  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/index.md](https://github.com/okta/okta-developer-docs/blob/5dc7485b4d31c32f7ba98549f1ac06c6ea6d0271/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/860b9a54-a874-40bf-80be-b0270de735eb) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/5dc7485b4d31c32f7ba98549f1ac06c6ea6d0271/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c87918cc-dfa2-47dc-b3a8-7ea5b8029369) | 84  | 88  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/wfconnector/protocol-name.md](https://github.com/okta/okta-developer-docs/blob/5dc7485b4d31c32f7ba98549f1ac06c6ea6d0271/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Fwfconnector%2Fprotocol-name.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6fee40cc-1720-4288-b186-da3a76a4d71d) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.bd7a336e-517c-4e9c-afcb-86315115917d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by vanngo-okta** [comment]
PM approved on Slack.

**Review by grahamsmith-okta — APPROVED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/23da803da89da339d046b805c925f678cac7e17c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/51d44d50-b47e-494c-ab50-3dd50f82457c) | 81  | 87  | 62  | 99  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/index.md](https://github.com/okta/okta-developer-docs/blob/23da803da89da339d046b805c925f678cac7e17c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/eca3131e-3cce-488f-b176-5afc4215aae9) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/23da803da89da339d046b805c925f678cac7e17c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ef1d06dc-5482-448b-8de2-d1d4917096df) | 84  | 88  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/wfconnector/protocol-name.md](https://github.com/okta/okta-developer-docs/blob/23da803da89da339d046b805c925f678cac7e17c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Fwfconnector%2Fprotocol-name.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7d9964ea-c7f1-4b9a-b500-b2e57a268bdd) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.fea8324c-cee9-4fb9-bb64-23b054a5d079?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Pull request merged**
