### PR TITLE
Move arch center to top nav

### PR DESCRIPTION
**Pull request by danielmaharry-okta**
## Description:
- **What's changed?** 
Test to move arch center to top nav

### Partially Resolves:

* [OKTA-604145](https://oktainc.atlassian.net/browse/OKTA-604145)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/companyx/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fcompanyx%2Findex.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e6a601be-57c9-4eed-915b-e0c000f00e5e) | 59  | 78  | 47  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/45dec32c-a113-4c5a-81f8-099b14432644) | 61  | 92  | 50  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab-azure-ad/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab-azure-ad%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/90579e2e-e120-4375-8f04-3532de2f0cec) | 59  | 72  | 74  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab-generic-database/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab-generic-database%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1172aaca-6575-4bf1-b1a0-420b36098306) | 51  | 61  | 64  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab-ldap-server/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab-ldap-server%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9408ceac-bba4-4bb1-9a8b-9120cf7d8437) | 63  | 70  | 61  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/99e3d033-7e7b-4b55-9e52-4639756d7b78) | 72  | 60  | 100  | 94  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3b34b7eb-2ace-47da-9171-a46f0572a8fa) | 100  | 67  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ae8fab70-307c-48e6-91b9-af326ccb777f) | 100  | 100  | 68  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-1-configure-terraform-cloud/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-1-configure-terraform-cloud%2Findex.md) | [75](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a42c9b13-9997-45a7-8a6f-1c7cd09d8f82) | 55  | 58  | 59  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-2-create-resources/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-2-create-resources%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/158637dd-361d-4156-896d-1b3d30168f47) | 75  | 94  | 46  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-3-rename-a-group/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-3-rename-a-group%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/874f6117-978f-4439-87b8-290ae2756c78) | 79  | 100  | 100  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-4-deploy-changes-to-production/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-4-deploy-changes-to-production%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d3f731ba-dc7d-4314-90ab-f4d07e18ce7a) | 47  | 74  | 85  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-5-detect-drift/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-5-detect-drift%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9b862058-7792-4817-9bea-1aa372d51911) | 100  | 100  | 55  | 91  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-6-synchronize-environments-daily/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-6-synchronize-environments-daily%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/456fa07c-82e3-4504-9f7f-2d7e258f900d) | 66  | 74  | 66  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab/index.md](https://github.com/okta/okta-developer-docs/blob/4f8c7875fe8787582a39f6e9daad5cbe11bcd281/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/89d05086-e0ce-48ed-845d-a806eb213f6e) | 69  | 69  | 58  | 95  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.2d29b55f-cb5a-4d16-99fc-8ac79a07c6f9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/companyx/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fcompanyx%2Findex.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/36a7b641-95d6-487c-a73f-e4792d957a89) | 59  | 78  | 47  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/directory-coexistence/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fdirectory-coexistence%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4b899b46-a2c0-4ac3-8990-513e53ebb1a9) | 61  | 92  | 50  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/directory-coexistence/lab-azure-ad/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fdirectory-coexistence%2Flab-azure-ad%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/617dfdf2-a131-44e5-a3dc-6356e06f0f9b) | 59  | 72  | 74  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/directory-coexistence/lab-generic-database/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fdirectory-coexistence%2Flab-generic-database%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b7c9f3e8-f880-4ebb-974e-0b2a8f149c95) | 51  | 61  | 64  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/directory-coexistence/lab-ldap-server/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fdirectory-coexistence%2Flab-ldap-server%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b5c2ddb4-ab88-488e-910d-6442fba2402f) | 63  | 70  | 61  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/directory-coexistence/lab/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fdirectory-coexistence%2Flab%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/82eee4e0-028b-42bb-a320-8e46d9f2a6b1) | 72  | 60  | 100  | 94  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a3add8d6-649f-40bb-bb49-518ff91306d1) | 100  | 67  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f4ead8c0-be8d-40fc-8b44-b0bc33d8d2ca) | 100  | 100  | 68  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/lab-1-configure-terraform-cloud/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Flab-1-configure-terraform-cloud%2Findex.md) | [75](https://okta.acrolinx.cloud/api/v1/checking/scorecards/35b41534-0e2b-48a1-a74e-81270a425a78) | 55  | 58  | 59  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/lab-2-create-resources/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Flab-2-create-resources%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f1a85448-ce38-4171-9cd0-df1ec30904eb) | 75  | 94  | 46  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/lab-3-rename-a-group/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Flab-3-rename-a-group%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/30601f2b-f97e-4c5e-b6d8-67b2da96cb40) | 79  | 100  | 100  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/lab-4-deploy-changes-to-production/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Flab-4-deploy-changes-to-production%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b9cfcdae-9d99-4bd0-9fc2-4e3291cac1a0) | 47  | 74  | 85  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/lab-5-detect-drift/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Flab-5-detect-drift%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1953128e-62c5-4553-bbf9-a932ba15f64f) | 100  | 100  | 55  | 91  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/lab-6-synchronize-environments-daily/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Flab-6-synchronize-environments-daily%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/70b11fe0-e6d5-4633-9f2c-ee420e481f7c) | 66  | 74  | 66  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/ac22/multiple-environments/lab/index.md](https://github.com/okta/okta-developer-docs/blob/adf18bdfea3f4a482b41cbe4d2e222db75cfca9b/packages%2F%40okta%2Fvuepress-site%2Fac22%2Fmultiple-environments%2Flab%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/04c433b8-54a5-437d-8212-44a64e13269f) | 69  | 69  | 58  | 95  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.3a386048-e8ac-4c64-8561-47eb0d86d503?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score **DRAFT 06.01.22**
 
A minimum Acrolinx Score of **40** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, ex. Correctness. Your article will be clearer and more consistent with Microsoft standards.
 
| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 40 | Correctness<br />(Spelling, grammar)<br />Preferred: 40 | Clarity<br />(Readability)<br />Preferred: 10 | Inclusive language<br />(+ accesibility)<br />Preferred: 10 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/companyx/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fcompanyx%2Findex.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/991fecaa-12b0-49b8-9642-06fc840b6fa7) | 59  | 78  | 47  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4b5d49b1-cf43-46ec-bfaa-0a8e0021fb38) | 61  | 92  | 50  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab-azure-ad/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab-azure-ad%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9bb2e680-2c2a-4879-a2ec-3da74d6264cf) | 59  | 72  | 74  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab-generic-database/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab-generic-database%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3f16c68e-0279-4206-ba76-6a44524a9ee6) | 51  | 61  | 64  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab-ldap-server/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab-ldap-server%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b588ffa5-dbee-406e-b258-4c5ff456859e) | 63  | 70  | 61  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/directory-coexistence/lab/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fdirectory-coexistence%2Flab%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f3bd5b42-e0a8-4747-a617-600f59d78e82) | 72  | 60  | 100  | 94  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/127858bf-9e5f-4da5-a5b5-dbe399ee599f) | 100  | 67  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/aab914ea-a8d0-4854-9e59-61ebddbf0911) | 100  | 100  | 68  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-1-configure-terraform-cloud/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-1-configure-terraform-cloud%2Findex.md) | [75](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1c692880-0ca7-4387-9e29-318495ffe117) | 55  | 58  | 59  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-2-create-resources/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-2-create-resources%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9c2e405b-e18b-45e1-9cce-a44b4ee52a16) | 75  | 94  | 46  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-3-rename-a-group/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-3-rename-a-group%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/20619493-ac09-4f24-9617-b972ebdbb0c8) | 79  | 100  | 100  | 88  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-4-deploy-changes-to-production/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-4-deploy-changes-to-production%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e179832a-d4ed-4e2b-b223-c8d44154c972) | 47  | 74  | 85  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-5-detect-drift/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-5-detect-drift%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b1d1872b-391c-4de9-a25e-ec8965234f31) | 100  | 100  | 55  | 91  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab-6-synchronize-environments-daily/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab-6-synchronize-environments-daily%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2d2c7669-92f7-4d02-8ca6-25998758bc24) | 66  | 74  | 66  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/architecture-center/multiple-environments/lab/index.md](https://github.com/okta/okta-developer-docs/blob/e8ef142134b23c218f05b5a25eae2caa81532808/packages%2F%40okta%2Fvuepress-site%2Farchitecture-center%2Fmultiple-environments%2Flab%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bce7790a-3fe6-4a1d-b981-fc70eba40fe7) | 69  | 69  | 58  | 95  |

  - The results from this response were procced by the [hugo-targets1.solution.acrolinx.sh](https://hugo-targets1.solution.acrolinx.sh) Acrolinx Cloud Host.
  - Scorecard links by default are only good for 7 days. [Link for this commit's Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.0e58e477-f40a-4ffa-abad-32b4745ad43a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by danielmaharry-okta** [comment]
Closing - end of test

**Comment by danielmaharry-okta** [comment]
Undeleted branch for as this is beign used by JIRA bug report https://oktainc.atlassian.net/browse/OKTA-611978

**Pull request closed without merging**
