### PR TITLE
Fixing sitemap link 

### PR DESCRIPTION
**Pull request by kamaldeepcheema-okta**
## Description:
- **What's changed?** 
> Fixing the sitemap link. Previously we were displaying the sitemap under the 'docs-sitemap' alias.

- **Is this PR related to a Monolith release?**
> No

### Resolves:

* [OKTA-362166](https://oktainc.atlassian.net/browse/OKTA-362166)

**Netlify Build

https://6016f373b01495f73debdbe0--reverent-murdock-829d24.netlify.app/sitemap.xml

### CODE REVIEW

**Review by francoislehoux-okta — COMMENTED** [review]
Please verify with Hamza, this will most likely break `Coveo`. It expects to have a a `docs-sitemap` file for docs related pages, and other for the other categories.

I think you need to keep that one sitemap as is and generate more for non doc related pages.

**Comment by hamzaessaoui-okta** [comment]
@kamaldeepcheema-okta @francoislehoux-okta docs can't use /sitemap.xml since it's being used by blog.
Is there a reason we want to rename it?

In all cases, this wouldn't break Coveo since it uses https://developer.okta.com/sitemap_index.xml. If we do rename the docs sitemap, we need to update the sitemap_index file.

**Comment by francoislehoux-okta** [comment]
> @kamaldeepcheema-okta @francoislehoux-okta docs can't use /sitemap.xml since it's being used by blog.
> Is there a reason we want to rename it?
> 
> In all cases, this wouldn't break Coveo since it uses https://developer.okta.com/sitemap_index.xml. If we do rename the docs sitemap, we need to update the sitemap_index file.

This is what I was looking for. To sum it up:
- `sitemap.xml` is the blog's sitemap
- `pages-sitemap.xml` is the current drupal's sitemap (developer pages, non-docs)
- `docs-sitemap.xml` is the current vuepress' sitemap (docs pages)

Short term, drupal will be going out and most of these pages have been migrated over to vuepress. If I understand correctly, we need to have a `pages-sitemap.xml` generated on the vuepress site for any page that is not documentation, so pricing, oin, etc? @hamzaessaoui-okta

**Comment by kamaldeepcheema-okta** [comment]
> > @kamaldeepcheema-okta @francoislehoux-okta docs can't use /sitemap.xml since it's being used by blog.
> > Is there a reason we want to rename it?
> > In all cases, this wouldn't break Coveo since it uses https://developer.okta.com/sitemap_index.xml. If we do rename the docs sitemap, we need to update the sitemap_index file.
> 
> This is what I was looking for. To sum it up:
> 
> * `sitemap.xml` is the blog's sitemap
> * `pages-sitemap.xml` is the current drupal's sitemap (developer pages, non-docs)
> * `docs-sitemap.xml` is the current vuepress' sitemap (docs pages)
> 
> Short term, drupal will be going out and most of these pages have been migrated over to vuepress. If I understand correctly, we need to have a `pages-sitemap.xml` generated on the vuepress site for any page that is not documentation, so pricing, oin, etc? @hamzaessaoui-okta
> 
> Where is sitemap_index.xml generated/hosted from? @hamzaessaoui-okta

I've compared the current https://developer.okta.com/docs-sitemap.xml VS https://developer.okta.com/pages-sitemap.xml and I can see that our docs-sitemap.xml already has a lot of the files listed in pages-sitemap.xml. The ones that it does not are paths that don't exist anymore. So in fact it looks like the pages-sitemap.xml file is outdated and our docs-sitemap.xml is the more current version.

In regards to the contents of the blog's sitemap.xml - that isn't included at all in our docs-sitemap.xml.

**Comment by hamzaessaoui-okta** [comment]
@francoislehoux-okta @kamaldeepcheema-okta if the goal is to take over the sitemap, I would recommend:
- creating a static file sitemap_index.xml with two links (docs sitemap - the name doesn't matter) + blog sitemap - sitemap.xml)
- docs sitemap should include all pages

**Comment by kamaldeepcheema-okta** [comment]
> @francoislehoux-okta @kamaldeepcheema-okta if the goal is to take over the sitemap, I would recommend:
> 
> * creating a static file sitemap_index.xml with two links (docs sitemap - the name doesn't matter) + blog sitemap - sitemap.xml)
> * docs sitemap should include all pages

I've updated the PR now to include a static sitemap_index.xml file that lists both docs-sitemap.xml (which includes all the files) and sitemap.xml (which is the blog's sitemap).

@francoislehoux-okta @hamzaessaoui-okta

**Comment by shawyu-okta** [comment]
Do we need to update the generation of `robots.txt` so that it points to the `sitemap_index.xml` now?

**Review by francoislehoux-okta — APPROVED** [review]

**Comment by kamaldeepcheema-okta** [comment]
> Do we need to update the generation of `robots.txt` so that it points to the `sitemap_index.xml` now?

Yeah that's a good idea, it would make more sense.

**Comment by hamzaessaoui-okta** [comment]
@kamaldeepcheema-okta yes please, it would be great if both changes go live together

**Review by shawyu-okta — APPROVED** [review]

**Comment by kamaldeepcheema-okta** [comment]
> @kamaldeepcheema-okta yes please, it would be great if both changes go live together

Yep I just updated the PR for this change

**Comment by hamzaessaoui-okta** [comment]
Awesome! could you please ping me when this is live? I'll update Coveo

**Pull request merged**
