### PR TITLE
updates for new default label content

### PR DESCRIPTION
**Pull request by susanharper-okta**
## Description:
- **What's changed?** updates for new default label content
- **Is this PR related to a Monolith release?** Yes 2020.09.0

### Resolves:

* [OKTA-523379](https://oktainc.atlassian.net/browse/OKTA-523379)

### CODE REVIEW

**Review by nakuljoshi-okta — APPROVED** [review]
LGTM

**Comment by nakuljoshi-okta** [comment]
sorry I just realized, we would need to add `default` property in this table as well. This new property indicates if the server is default or not. 
https://developer.okta.com/docs/reference/api/authorization-servers/#authorization-server-properties

**Review by venkatviswanathan-okta — APPROVED** [review]

**Review by nakuljoshi-okta — APPROVED** [review]
LGTM

**Review by brentschaus-okta — APPROVED** [review]
LGTM

**Pull request merged**
