### PR TITLE
Replace the header's login text and link

### PR DESCRIPTION
**Pull request by francoislehoux-okta**
## Description:
- **What's changed?** Replace the header's login text and link
- **Is this PR related to a Monolith release?** No

### Resolves:
* [OKTA-362766](https://oktainc.atlassian.net/browse/OKTA-362766)

### Screenshots:
Screen Shot 2021-01-25 at 3 35 11 PM

### CODE REVIEW

**Review by shawyu-okta — APPROVED** [review]

**Review by kamaldeepcheema-okta — APPROVED** [review]

**Comment by jakubvul-okta** [comment]
This feels like a regression to something that we changed because it was confusing readers, i.e. that they thought they were authenticating for a "logged-in" documentation experience.

**Comment by francoislehoux-okta** [comment]
> This feels like a regression to something that we changed because it was confusing readers, i.e. that they thought they were authenticating for a "logged-in" documentation experience.

@albertchen-okta @alexdahl-okta

**Comment by jakubvul-okta** [comment]
For consistency with our style guide AND clarity, why not have the button say "Sign in to Okta"?

**Review by alexdahl-okta — CHANGES_REQUESTED** [review]
+1 to @jakubvul-okta. The link change is great, but the "login" will likely cause future pain.

I'd be fine with trying "Sign in to Okta". It's a little bit vague, and in our system model there's no longer such a thing (you always have an application target, such as the Admin Console), but it probably matches our user's mental model.

**Comment by francoislehoux-okta** [comment]
Screen Shot 2021-01-26 at 10 09 03 AM

**Review by alexdahl-okta — APPROVED** [review]
🎉

**Pull request merged**
