### PR TITLE
OIE Policy types test release

### PR DESCRIPTION
**Pull request by jakubvul-okta**
## Description:
- **What's changed?** Testing out OIE-related update 
- **Is this PR related to a Monolith release?** No

### Resolves:

* N/A

### CODE REVIEW

**Comment by wdawson** [comment]
Sweet! I didn't look closely at the main doc since I already reviewed and looks like no changes since July. ⛵

**Comment by wdawson** [comment]
@jakubvul we may want to do this too if possible: https://support.google.com/webmasters/answer/93710

**Comment by jakubvul-okta** [comment]
> @jakubvul we may want to do this too if possible: https://support.google.com/webmasters/answer/93710

Going to try it with `robots.txt` first. If that doesn't work we can try other approaches.

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Pull request merged**
