### PR TITLE
Align scopes with samples for React and Angular

### PR DESCRIPTION
**Pull request by alisaduncan**
## Description:
- **What's changed?** Aligning requested scopes for Angular and Vue quickstart guides to match samples
- **Is this PR related to a Monolith release?** No

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md](https://github.com/okta/okta-developer-docs/blob/15c6adbb8f854c56d4c371e17190f04225e9b2d9/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-into-spa-redirect%2Fmain%2Fangular%2Fconfigmid.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/06a83bda-73b5-499c-8756-4ed81de29bcd) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md](https://github.com/okta/okta-developer-docs/blob/15c6adbb8f854c56d4c371e17190f04225e9b2d9/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-into-spa-redirect%2Fmain%2Freact%2Fconfigmid.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7275a6ae-48d9-4de6-a9d4-4b147f1de6ac) | 43  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.751021f7-3f49-41b7-b69e-cc775d06fa38?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by brianduffield-okta — APPROVED** [review]
LGTM!

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md](https://github.com/okta/okta-developer-docs/blob/11c0234c8f7996f222c042b46274e3a4b0986221/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-into-spa-redirect%2Fmain%2Fangular%2Fconfigmid.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9eee0a6b-c55c-4256-8ddd-b236dab847ca) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md](https://github.com/okta/okta-developer-docs/blob/11c0234c8f7996f222c042b46274e3a4b0986221/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-into-spa-redirect%2Fmain%2Freact%2Fconfigmid.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/70c30056-468e-4d66-ab15-6c5628e23383) | 43  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.8cc990b1-333c-4cae-baca-b2a1692ed018?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by alisaduncan** [comment]
@barbaravo-okta @brianduffield-okta I think (hope) I amended my commit to be signed per signing rules

**Comment by alisaduncan** [comment]
@brianduffield-okta recreated to meet merging rules.

**Pull request closed without merging**
