### PR TITLE
Implementation of include component

### PR DESCRIPTION
**Pull request by ulyanash**
## Description:
- Adds ability to include one markdown in another. 
- The code is 
`!!!include test.md!!!`
This will include [test.md](http://test.md/) file from vuepress-site/includes directory

### Resolves:

* [4.Implementation of include component](https://trello.com/c/akhaNuMy/5-4implementation-of-include-component)

### CODE REVIEW

**Comment by ulyanash** [comment]
@chrisdmills-okta This markdown extension doesn't support passing variables. This will require extending this script with features. I didn't find a way to make a component that includes file by its path too.

**Comment by chrisdmills-okta** [comment]
@ulyanash ok, no worries.

**Comment by danielmaharry-okta** [comment]
@chrisdmills-okta Basic includes seem to work fine but there are a couple of issues. 

1. Includes aren't picked up for hot-reloading. You have to recompile the whole site in order to see changes in your include files.
2. Headings don't get link anchors if they aren't at the top of an include file. So if I have a file test.md that looks like this

```
# ARRRGGGGHHHHHH
Some text
```

You can link to this heading from elsewhere. But if you swap them around as follows, you can't. For whatever reason, the heading isn't anchored.

```
Some text
# ARRRGGGGHHHHHH
```

I didn't test how far you can nest includes but I went to three levels down and they all seemed fine.

**Comment by vanngo-okta** [comment]
@chrisdmills-okta, @janethu-okta - LGTM 👍  
The **markdown-it-include** plugin works well and renders html similar to our current Vuepress behaviour. I've tested the following in the snippets:
* numbering (you can insert an ordered list snippet in the middle of an ordered list and the resulting numbers line up)
* headings (H2, H3 show up in the right-nav)
* inline text (you can insert an inline string)
* code snippets (code snippets render ok, but you will need a newline after the snippet to end the code block)
* note snippets (you will need a newline after the note snippet to end the note block)

Other considerations for this feature:
* You need to install the dependencies after you pull the files: `yarn install`
* You will need to rebuild the site to see any updates: `yarn dev`
* In the style guide, we need to distinguish when to use [Reusable text snippets](https://github.com/okta/okta-developer-docs/wiki/Style-Guide#reusable-text-snippets) and when to use Markdown-it-include (as a convention)
* This plugin is flexible to include other snippets not in the `includes` root directory. For example: `!!!include(../docs/guides/add-an-external-idp/main/apple/idp.md)!!!`

**Comment by vanngo-okta** [comment]
@chrisdmills-okta : We need one of the developers from dev platform to review the plugin? (Shaw/Francois?) I don't know if there is a vetting process for new plugin or tools? Do we need to ask BT? We also need to discuss this feature with the writing team.

**Comment by danielmaharry-okta** [comment]
@chrisdmills-okta 

- Any guidelines on whether includes should be language agnostic or if they can be language specific?
- File-naming convention (can we make it obvious what common material they contain?)
- Where we keep these (a site-wide folder?)
- Include date and author? Makes it easier to compare whether the info it contains might be out of date or not.

My sense of includes is that we could suddenly have a lot of these very quickly and managing them could get quite unwieldy straight away. Maybe not as bad a redirects but still....

**Pull request closed without merging**
