### PR TITLE
Update apps api and .well-known api for DPoP

### PR DESCRIPTION
**Pull request by nakuljoshi-okta**
## Description:
- **What's changed?** 
Update apps api and .well-known api for DPoP
- **Is this PR related to a Monolith release?**  `2023.03.1`

### Resolves:

* [OKTA-578939](https://oktainc.atlassian.net/browse/OKTA-578939)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/api/apps/index.md](https://github.com/okta/okta-developer-docs/blob/bbab1c55149fb6622456df2dc86a31a99b2fce7e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fapps%2Findex.md) | 73 | 512 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c6d43f5b-33ba-4033-a251-521a806d856a) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/api/oidc/index.md](https://github.com/okta/okta-developer-docs/blob/bbab1c55149fb6622456df2dc86a31a99b2fce7e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Foidc%2Findex.md) | 74 | 420 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2816e967-523a-4f65-9164-5ce8385b76c1) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.fa429fdd-042c-4c2a-abfd-92b5aca4be47?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/api/apps/index.md](https://github.com/okta/okta-developer-docs/blob/cbb462b7e77657b4a3c5e203121cca30f017f8f4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fapps%2Findex.md) | 73 | 510 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/49634b56-07b8-40ca-911c-1b1ed304183a) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/api/oidc/index.md](https://github.com/okta/okta-developer-docs/blob/cbb462b7e77657b4a3c5e203121cca30f017f8f4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Foidc%2Findex.md) |   |   | [→]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

Successfully checked 1 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.c5913a63-4d92-44b9-933f-217931cdcf26?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/api/apps/index.md](https://github.com/okta/okta-developer-docs/blob/81b3f05679f7f527e3bc76a285aeb20dc1f02523/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fapps%2Findex.md) |   |   | [→]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [packages/@okta/vuepress-site/docs/reference/api/oidc/index.md](https://github.com/okta/okta-developer-docs/blob/81b3f05679f7f527e3bc76a285aeb20dc1f02523/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Foidc%2Findex.md) | 75 | 419 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9df946d2-0798-47af-a045-38f0ec74c090) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 2 documents.
See summary in [Content Analysis Dashboard]()

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/api/apps/index.md](https://github.com/okta/okta-developer-docs/blob/81b3f05679f7f527e3bc76a285aeb20dc1f02523/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fapps%2Findex.md) | 73 | 508 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/22123a91-70c0-4b6d-835f-78ec09c577a8) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/api/oidc/index.md](https://github.com/okta/okta-developer-docs/blob/81b3f05679f7f527e3bc76a285aeb20dc1f02523/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Foidc%2Findex.md) | 75 | 419 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/deff5d66-7eaa-463f-9965-5cadf8b3a226) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.106f7559-b00c-47cf-ba70-422731089d75?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/api/apps/index.md](https://github.com/okta/okta-developer-docs/blob/6cb4ef52368dbf0c8c07a0f37994ca1e020e612a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fapps%2Findex.md) | 73 | 507 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/43646313-e707-4dfc-b22f-017b5ec012e6) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/api/oidc/index.md](https://github.com/okta/okta-developer-docs/blob/6cb4ef52368dbf0c8c07a0f37994ca1e020e612a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Foidc%2Findex.md) | 75 | 419 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d55c20e7-0d47-47d1-849d-74a1d8e14915) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.f0db9240-f95a-4ef8-a59a-5dca38891aee?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by brianduffield-okta** [comment]
Merging into release branch

**Pull request merged**
