### PR TITLE
okta-521171 Updated isv submission flow diagram

### PR DESCRIPTION
**Pull request by danielmaharry-okta**
## Description:
- **What's changed?** Updated the ISV Submission flow diagram on https://developer.okta.com/docs/guides/submit-app/openidconnect/main/ to reflect the new diagram style and added metadata for the new image.
- **Is this PR related to a Monolith release?** no

### Resolves:

* [OKTA-521171](https://oktainc.atlassian.net/browse/OKTA-521171)

### CODE REVIEW

**Review by chrisdmills-okta — CHANGES_REQUESTED** [review]
The new image is looking really nice!

Few bits of feedback on it, nothing serious:

1. The titles for each step (e.g. "Code Review") should be in sentence case, as per our guidelines. Same for the labels on each part of the diagram?
2. The "YES" label on the arrow below "Sign in to OIN Manager" isn't needed, afaict. There's no decision there; it's just the next step.
3. Do you think the Email circles need some kind of label along the lines of "Email feedback to ISV" on them. OR, do you think the "Check Errors" boxes could be updated to "Read feedback, fix issues"? Not all feedback will be out and out errors? I'm not 100% sure here, it feels obvious enough what is happening, but some just feels slightly off about the error paths.

**Comment by danielmaharry-okta** [comment]
@chrisdmills-okta I've updated the diagram based on PM's feedback. Hope you're OK with it.

**Review by vanngo-okta — COMMENTED** [review]
Looks good Dan! A few nits:
1) Typo: "Receieve and review submission"
2) A dangling right arrow from the first email icon?

**Comment by danielmaharry-okta** [comment]
@vanngo-okta Arrgh!  How did I miss those?  Thanks for the spots. Have corrected them.

**Review by vanngo-okta — APPROVED** [review]
LGTM! 🚀

**Review by chrisdmills-okta — APPROVED** [review]

**Pull request merged**
