### PR TITLE
Stack selector fix

### PR DESCRIPTION
**Pull request by ulyanash**
- Update stack-selector styles/behaviour
- Adding a Stack selector menu to the side menu

Resolves:

[Fixing stack selector and putting the changes live](https://trello.com/c/Yoi8h24u/1-1-fixing-stack-selector-and-putting-the-changes-live)

### CODE REVIEW

**Review by robertnicolo-okta — APPROVED** [review]
Everything looks good though I did notice the "noSelector" attribute still being used. It's a deprecated attribute and its use should not cause any issues.

**Review by chrisdmills-okta — APPROVED** [review]
If @robertnicolo-okta is happy, then I'm happy. I think the `noSelector` usage is something we need to clear up in the content, so that's OK to leave for now.

@vanngo-okta , did you have any more comments here? I want to get your sign-off on behalf of Janet's team before merging, so I'll set you as a reviewer. Thanks!

**Review by vanngo-okta — APPROVED** [review]
Moving the stack-selector to the right navigation panel looks good! 🚀 

I'm approving this PR, but just want to comment on a small nit: there is an extra line (space) after wrapped text. For example:
Screen Shot 2022-02-02 at 11 15 31 AM

Also, there is more urgency for us to add stack selector icons because the gap before the stack-selector text is off without the icon. This is especially true for the social IdP pages now that the selector is visible on the right-nav:
Screen Shot 2022-02-02 at 11 10 57 AM

**Comment by chrisdmills-okta** [comment]
Thanks @vanngo-okta ! @ulyanash , can you look into the issue that Van has brought up this week? I'd love to get this change published by the end of the week.

**Comment by ulyanash** [comment]
@chrisdmills-okta Done, please check the updates in PR

**Comment by chrisdmills-okta** [comment]
Superb, thanks @ulyanash . @robertnicolo-okta and @vanngo-okta , one last check? ;-)

**Review by robertnicolo-okta — APPROVED** [review]
Van's latest feedback seems to have been resolved regarding an extra space in the multi-line dropdown items. I also took a quick gander around the site again and everything checks out.

**Pull request merged**
