### PR TITLE
Release notes for weekly

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Adding docs and release notes for weekly release
- **Is this PR related to a Monolith release?** `2024.10.1`

### Resolves:

* [OKTA-794288](https://oktainc.atlassian.net/browse/OKTA-794288)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md](https://github.com/okta/okta-developer-docs/blob/473880baf045ecb73fb19edba70789c13afb8cdc/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fidentity-providers%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/33e3a051-eae2-4a8e-890e-8c6d1a4b2108) | 63  | 95  | 100  | 97  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ecc2ae5a-e900-4791-b7a9-f88ec711ea7b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md](https://github.com/okta/okta-developer-docs/blob/cf0f761622b8a44db28dc38ad112735371d33f6a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fidentity-providers%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e8bbfef0-81a0-4685-8b19-5d76cc01a3ce) | 63  | 95  | 100  | 97  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.592df813-78ff-4765-bd85-3def473e7ebd?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md](https://github.com/okta/okta-developer-docs/blob/1430a791dee9f894aa61a221552a054891fcd00d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fidentity-providers%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1371ea3d-d851-4665-b020-8e2b4ae9dc64) | 63  | 95  | 100  | 97  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.13ea76fd-b67b-48a8-a48b-67671134e3bf?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by brentschaus-okta — APPROVED** [review]
LGTM!

**Pull request merged**
