### PR TITLE
OKTA-683713 Add ITP EA entry

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Add ITP EA entry in 2024.01.2 
- **Is this PR related to a Monolith release?** Yes, TBD

### Resolves:

* [OKTA-683713](https://oktainc.atlassian.net/browse/OKTA-683713)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md](https://github.com/okta/okta-developer-docs/blob/fc518823aad86d743ba52d402122efc80e795f90/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024-okta-identity-engine%2Findex.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/66764a91-9168-48aa-8501-0d8312bf8bf1) | 52  | 55  | 58  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c97d8a19-e09d-4c33-8713-5d9a334b2287?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — DISMISSED** [review]
LGTM

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md](https://github.com/okta/okta-developer-docs/blob/b7239b4204b401ecded82d58060218d4d9dd776a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2024-okta-identity-engine%2Findex.md) | [73](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a62ecbae-e52b-496f-8d83-8cb822c926e0) | 52  | 55  | 58  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7e452cfc-d158-4b46-83e4-15ec9fe4cd01?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by vanngo-okta** [comment]
Cancel rn

**Pull request closed without merging**
