### PR TITLE
OKTA-675383 - Add missing rate limit subtype

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Adding missing subtype from the operations limit table: https://developer.okta.com/docs/reference/rl-system-log-events/#operation-rate-limits
- **Is this PR related to a Monolith release?** n/a

### Resolves:

* [OKTA-675383 ](https://oktainc.atlassian.net/browse/OKTA-675383 )

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md](https://github.com/okta/okta-developer-docs/blob/53593d8b5ee1daf039056681b00bbef4293d797e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Frl-system-log-events%2Findex.md) | 75 | 62 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1e5e399e-051f-44ba-b992-03636c7af8b5) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.568233fb-fdea-43e8-9e64-7dd8ca4db3b7?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md](https://github.com/okta/okta-developer-docs/blob/91d3cf91faa98a25eab53f73d6f7776874c9e771/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Frl-system-log-events%2Findex.md) | 75 | 62 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/142dbc9c-54ef-473e-ae69-b99bc3587bda) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.ad17dcde-1e26-45a0-9491-118c12091261?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Comment by brianduffield-okta** [comment]
SMEs approved in JIRA/Slack

**Pull request merged**
