### PR TITLE
OKTA-575227 Add Redocly API Service Integrations API link

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Add Redocly API Service Integrations API link from the Reference overview.
- **Is this PR related to a Monolith release?** Yes, 2023.03.0 (this API is already public, but a complete version of this API will be released on 2023.03.0, so we should publish this at the same time)

### Resolves:

* [OKTA-575227](https://oktainc.atlassian.net/browse/OKTA-575227)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/beta-only/index.md](https://github.com/okta/okta-developer-docs/blob/b894efe5579032af1b5dcc2577347d6484a5c63a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fbeta-only%2Findex.md) | 66 | 16 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/461b67a5-c9ef-4c7b-9214-36d0ff2e8622) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/b894efe5579032af1b5dcc2577347d6484a5c63a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) | 71 | 24 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8135be10-941e-4ad3-9f84-cc4e2da7fb6c) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.9b710df8-065c-434f-8d51-4580c8f8ab8b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/beta-only/index.md](https://github.com/okta/okta-developer-docs/blob/016450f397cc6b8f849fc036443c36ce125ea634/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fbeta-only%2Findex.md) | 69 | 15 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2ec33c88-dcf1-4c44-b6ad-980a42a24390) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/016450f397cc6b8f849fc036443c36ce125ea634/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) | 71 | 24 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e278864b-d491-4eab-8241-233a3557e5e9) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.424550fb-5e67-4f97-b900-075babd790d3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by isaacdurham-okta — APPROVED** [review]

**Review by janethu-okta — APPROVED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/conductor.yml](https://github.com/okta/okta-developer-docs/blob/25b656d79c5258ce4d7907078c8a3a240e32a57e/packages%2F%40okta%2Fvuepress-site%2Fconductor.yml) |   |   | [→]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/25b656d79c5258ce4d7907078c8a3a240e32a57e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) |   |   | [→]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

Successfully checked 0 of 2 documents.
See summary in [Content Analysis Dashboard]()

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/conductor.yml](https://github.com/okta/okta-developer-docs/blob/adee6fdd259f74fc773d808640a8341f381a4c70/packages%2F%40okta%2Fvuepress-site%2Fconductor.yml) |   |   | [→]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/adee6fdd259f74fc773d808640a8341f381a4c70/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) | 71 | 24 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/42d26813-d0a2-49d8-93e7-2d2804f82eab) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 2 documents.
See summary in [Content Analysis Dashboard]()

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/beta-only/index.md](https://github.com/okta/okta-developer-docs/blob/9e0a094b055cc2676c30a0e780ee9aa9d1558664/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fbeta-only%2Findex.md) | 69 | 15 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/79c0699b-9fd1-412a-b4d1-cc7c33ece18b) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/9e0a094b055cc2676c30a0e780ee9aa9d1558664/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) | 71 | 24 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6a250e07-08f2-4f1e-8512-b3e545c5904f) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.3990986e-5ffb-4f1f-92d2-703417d656ab?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/beta-only/index.md](https://github.com/okta/okta-developer-docs/blob/9e0a094b055cc2676c30a0e780ee9aa9d1558664/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fbeta-only%2Findex.md) | 69 | 15 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/38cda101-6588-48c1-b305-4e4de4838c3d) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/index.md](https://github.com/okta/okta-developer-docs/blob/9e0a094b055cc2676c30a0e780ee9aa9d1558664/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Findex.md) | 71 | 24 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/20e2ba24-b540-435f-8f0d-9ff3f842ca08) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 2 of 2 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.a3bfa15c-185f-4a47-91f6-cbaa97833f14?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by janethu-okta — APPROVED** [review]

**Pull request merged**
