### PR TITLE
[OKTA-725058] Fix Aerial page

### PR DESCRIPTION
**Pull request by ishan-krishna-okta**
## Description:
- **What's changed?** Fixed broken Aerial page
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-725058](https://oktainc.atlassian.net/browse/OKTA-725058)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/3b3e593e3a32969ab792ec339bd22e2380d974ab/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/163c6a24-ab80-4155-905a-fd45f4d6d7c9) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a62ac877-0adf-4e47-91c4-4680b99f4988?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/a55aa647cdd2ac415368153266cd4bdcc656606a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/11cca870-c44e-4dff-a0fb-f540b29e9e94) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/a55aa647cdd2ac415368153266cd4bdcc656606a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6b611bd3-92aa-4f18-b782-52431403eedc) | 81  | 100  | 81  | 97  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3e921b4f-9376-4b8e-800d-fa5b7cdaa18e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/57f1bffe20c09e51b42a72e5d3014a596d368d97/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/91da9b8f-4863-4b34-836d-8d13dafa0fb3) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/57f1bffe20c09e51b42a72e5d3014a596d368d97/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6bf519f7-6015-4c75-9fcd-a21cf19d31f3) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ebe69b87-1fa8-4583-879c-7d63fd523de2?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/9d844120897229d2d6d2163dc44beda787dd33a0/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/065eaca8-6162-413a-9732-18c886c33ec9) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/9d844120897229d2d6d2163dc44beda787dd33a0/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/984405ad-0b54-4fef-b35e-4667673c99e5) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b1f24ea7-f60a-4d18-a771-0448869e9cca?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/12a3865ac1f6f7f9706cec655e9abd2de01620fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cdbb9778-90e9-4c5f-a116-385fa9a2b10c) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/12a3865ac1f6f7f9706cec655e9abd2de01620fb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dc0ff5d7-2a13-458c-9b89-7f211ebf9419) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.d5f89a90-f75e-42bf-a1d0-2c22242070c7?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/07776fac2934c48332c897cf3bc63212315c280f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6674ca9c-5b37-4b96-afab-05bb57b8e94a) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/07776fac2934c48332c897cf3bc63212315c280f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d9c97ae3-f62c-4200-b53e-c8aa0e14e0b2) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c1b75270-ef5f-4f78-9eed-b782b5a5f2ca?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/d386d8c9c2d7f2e5c59ba1b282f9e00b930e52f4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c8c89ad3-d7a1-4888-bda1-ffc808442d38) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/d386d8c9c2d7f2e5c59ba1b282f9e00b930e52f4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6ad584fe-98d6-44f6-a104-d26c93ed683b) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.03ce09bc-6001-47e1-8bb6-23a110f0606d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/0500c28232ddbf088ee1e71644702329d9247280/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0d7d4a2d-874a-4c0a-b1c5-09d38d7a9657) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/0500c28232ddbf088ee1e71644702329d9247280/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/119039b2-c1e3-4892-a35d-d7ced73aa0a7) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.26bb815a-ee48-4645-b30a-c74eb9e2fada?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/2639081e0e1b9160a14b9ed58e0d19f048004b8a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3265da91-e140-41a6-bac3-41254effe8dd) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/2639081e0e1b9160a14b9ed58e0d19f048004b8a/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fcb79901-dd54-4f04-883f-bc46343b6912) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3e0c161e-4dbe-4afe-b928-1154169219be?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/a4bdad019a261f742e842f9e02c21cc062237edf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d3d3de60-0281-4e30-9046-8befab87c7d8) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/a4bdad019a261f742e842f9e02c21cc062237edf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c0812011-ec84-4630-a14a-16c2a2420c0c) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.312bad08-2220-426c-895c-8f8e4692d811?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/d568dd3462ceba1971a5414d9cdd7d015e8743d4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dbaaded8-c588-4675-91ee-e1648b4e0e03) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/d568dd3462ceba1971a5414d9cdd7d015e8743d4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3c0074ad-40e6-47b6-9f89-43954ea21d7a) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.1a2ac4f3-ae40-46bc-923f-0d3b88f77339?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/b113720e947add1be9e51e5e6744fc461d5988a5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/543ea33a-5b7b-4daf-9822-07554c7638f5) | 100  | 100  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.24d23c5a-bce5-4cef-9428-311e885d1651?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/index.md](https://github.com/okta/okta-developer-docs/blob/d83167a5689348689590cfb5a24f528d60d88940/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9682187f-9f52-4afc-97e3-22f07766fa61) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md](https://github.com/okta/okta-developer-docs/blob/d83167a5689348689590cfb5a24f528d60d88940/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fmanage-orgs-okta-aerial%2Fmain%2Findex.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/46a555fd-db74-471b-9c2e-b8e4162cc4ef) | 94  | 79  | 100  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0a00e06d-c89f-4a76-a8b7-f77ad5d836f0?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by emikhasyak-okta — APPROVED** [review]
Great job! 🚢

**Pull request merged**
