### PR TITLE
Upgrade webpack to 4.46.0

### PR DESCRIPTION
**Pull request by francoislehoux-okta**
## Description:
- **What's changed?** Upgrade webpack to 4.46.0

### Resolves:
* [OKTA-481884](https://oktainc.atlassian.net/browse/OKTA-481884)

### CODE REVIEW

**Review by TiffanyNg-okta — COMMENTED** [review]
I guess there are no breaking changes to be fixed? Do you need to do any of these: https://webpack.js.org/migrate/4/ ?

**Comment by shawyu-okta** [comment]
https://6255f2460e89ed03559a4b05--reverent-murdock-829d24.netlify.app

**Review by gaurigattani-okta — APPROVED** [review]

**Review by shawyu-okta — APPROVED** [review]
lgtm. i was surprised also that there were no changes we needed to apply for v3 -> v4 migration but looks like the vuepress-cli is already ready for v4 as far as configs go.

i had been mostly concerned about the `mode` flag addition but it appears to be in the [configs already](https://github.com/vuejs/vuepress/blob/38e98634af117f83b6a32c8ff42488d91b66f663/packages/%40vuepress/core/lib/node/webpack/createBaseConfig.js#L33-L40) and I also checked that the `yarn dev` version locally still has development sourcemaps, while the `yarn build` version hosted in the Netlify site does not have the sourcemaps (production mode).

**Comment by francoislehoux-okta** [comment]
`Vuepress` can handle `webpack` 4 at most. `vuepress-next` will work with 5

**Pull request merged**
