### PR TITLE
Copy edit and a few tweaks to make it work in existing guide

### PR DESCRIPTION
**Pull request by susanharper-okta**
## Description:
- **What's changed?** Copy edit and a few tweaks to make it work in existing guide
- **Is this PR related to a Monolith release?** No

### CODE REVIEW

**Comment by susanharper-okta** [comment]
@mraible check out the changes, please!

**Review by albertchen-okta — APPROVED** [review]
lgtm, thanks @susanharper-okta and @mraible !

**Comment by mraible** [comment]
Looking...

**Comment by mraible** [comment]
@susanharper-okta I took a look. I love how the Cloudflare guide is the main entry point for custom domains! I'm not sure if you want that though. The Cloudflare guide links to "Next steps" at the end, which I think is reasonable.

However, the Overview links to the Cloudflare guide at the bottom and you can never get to the other steps unless you click on them in the nav. I think Overview should link to "Gather Information" as its next steps at the bottom.

**Comment by susanharper-okta** [comment]
> @susanharper-okta I took a look. I love how the Cloudflare guide is the main entry point for custom domains! I'm not sure if you want that though. The Cloudflare guide links to "Next steps" at the end, which I think is reasonable.
> 
> However, the Overview links to the Cloudflare guide at the bottom and you can never get to the other steps unless you click on them in the nav. I think Overview should link to "Gather Information" as its next steps at the bottom.

@mraible and @albertchen-okta - I think this is an issue with how the guides are set up - guide buttons go to the next section. I went back and forth on where to put this content - because it does seem disruptive to the natural flow of the manual process. I think I'm going to move this to right before Next Steps.

**Comment by albertchen-okta** [comment]
works for me, thanks

**Comment by mraible** [comment]
Looks great - thanks @susanharper-okta! 🎊

**Pull request merged**
