### PR TITLE
OKTA-327732: Increase width of page to 1600px

### PR DESCRIPTION
**Pull request by oleksandrpravosudko-okta**
## Description:
- **What's changed?** 
  * ~switch to dart-sass to enable `@use` syntax~
  * override [3p](https://github.com/eduardoboucas/include-media/blob/master/dist/_include-media.scss#L32) breakpoints with custom [values](https://github.com/okta/okta-developer-docs/pull/1519/files#diff-5834700ee9371c12c79e57255f29b1c0R5)
  * increase containers' max-width for large screens (>=1600px) 
- **Is this PR related to a Monolith release?** 
  No

Before change:
Screenshot 2020-10-02 at 18 56 42

After change:
Screenshot 2020-10-02 at 18 55 23

### Resolves:

* [OKTA-327732](https://oktainc.atlassian.net/browse/OKTA-327732)

### CODE REVIEW

**Comment by oleksandrpravosudko-okta** [comment]
@albertchen-okta, @alexdahl-okta - can you please take a look when you have a chance?

**Review by albertchen-okta — APPROVED** [review]
after screenshot looks great, in fact, much much better!

**Review by bretterer — COMMENTED** [review]
We already had mixins.. why do we need to switch here?

**Comment by oleksandrpravosudko-okta** [comment]
@bretterer the intent behind placing new [media-max-width mixin](https://github.com/okta/okta-developer-docs/pull/1519/files#diff-600d90d1a96fe69f945ebecf6517596cR319) is to re-use breakpoints [constants](https://github.com/okta/okta-developer-docs/blob/master/packages/@okta/vuepress-theme-prose/assets/css/okta/base/variables.scss#L210) available under css/okta and seemingly [not being used](https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-theme-prose/layouts/Layout.vue#L114) at the moment

including module contents with `@use` enables more granular(namespace-based) approach to referencing variables/functions as opposed to `@import` overriding existing definitions - I wasn't sure whether it's safe to import all the content of [mixins](https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-theme-prose/assets/css/okta/base/mixins.scss) and [variables](https://github.com/okta/okta-developer-docs/blob/31140c0de776e08c8d8f4cba6ee05b6d4d64eb78/packages/%40okta/vuepress-theme-prose/assets/css/okta/base/variables.scss) from css/okta into [prose stylesheet](https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-theme-prose/assets/css/prose.scss) and decided to give `@use` a go

**Comment by alexdahl-okta** [comment]
Visual change looks great to me, thanks!

I recall that we have legacy css with breakpoints defined in multiple ways and places.
I would support centralizing breakpoint definitions in a single authoritative source – as a direction, even if we don't include refactoring in scope here – but defer to engineering for the details!

**Comment by oleksandrpravosudko-okta** [comment]
thanks for the feedback @albertchen-okta, @alexdahl-okta
@bretterer new mixin and `@use` syntax were removed in favour of breakpoints values [override](https://github.com/okta/okta-developer-docs/pull/1519/files#diff-5834700ee9371c12c79e57255f29b1c0L5)

**Review by bretterer — COMMENTED** [review]
LGTM!  Thanks!

**Pull request merged**
