### PR TITLE
OKTA-790239 Deprecate Apps API sections on VuePress

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Deprecating sections of the Apps API on VuePress and linking them to the version on Redocly
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-790239](https://oktainc.atlassian.net/browse/OKTA-790239)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/f785bb8baf7c2b4279eaedb4aa6fb8bc2107ec83/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/438e9f0e-37cb-4e7f-b50e-cb0d32e91b1f) | 100  | 60  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md](https://github.com/okta/okta-developer-docs/blob/f785bb8baf7c2b4279eaedb4aa6fb8bc2107ec83/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fokta-data-model%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4c93ad7d-fce3-41a0-b7f2-df98e8c3d40e) | 100  | 68  | 60  | 87  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.79c0773a-761d-463b-946c-15ac14e8b23a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/63cf17e9abe8d5dcee1492777b6d3d2a999560f1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0cd1eb16-81c6-4857-aaf1-f9bed16e93f9) | 100  | 60  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md](https://github.com/okta/okta-developer-docs/blob/63cf17e9abe8d5dcee1492777b6d3d2a999560f1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fokta-data-model%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c08fa5c2-00d8-440b-bc47-989df0b8b1f4) | 100  | 68  | 60  | 87  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.32e1f5d7-f6ae-4e9c-b9d1-2f3f43f66b76?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/7b6eddb8de7b3a1bb22bdc06c8ffb3c02f0af5ee/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2653f5cd-f3f8-429e-a54a-7edbb5449b3d) | 100  | 60  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md](https://github.com/okta/okta-developer-docs/blob/7b6eddb8de7b3a1bb22bdc06c8ffb3c02f0af5ee/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fokta-data-model%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/124cf353-2c6e-4033-bc3c-59eb2e9e0766) | 100  | 68  | 60  | 87  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.6774299e-a2b8-44bc-acf5-083b3b712100?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/0381c3d1fb72d48e3444a59c27b37684fa45a25e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/15d4ca68-903d-4680-ba2a-025a788a85a7) | 100  | 60  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md](https://github.com/okta/okta-developer-docs/blob/0381c3d1fb72d48e3444a59c27b37684fa45a25e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fokta-data-model%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/50b056eb-1be6-4c5d-ab2d-8029077b5320) | 100  | 68  | 60  | 87  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c1cfeb93-20e7-4dd5-90d4-74601b2a9a76?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/611edc434db511e61c975797edb54acf02632725/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/722cb661-3ad0-4d4f-b955-b0818b7f3c5d) | 100  | 60  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md](https://github.com/okta/okta-developer-docs/blob/611edc434db511e61c975797edb54acf02632725/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fokta-data-model%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cf566ffe-1937-41f7-9df2-82ceeca79991) | 100  | 68  | 60  | 87  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.8bc4f2b6-93b8-4bad-98d7-0c8e3af45ae3?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/a64132e9909881addca0dc0213ca4212de5929f1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a7d015e4-99e0-408b-ae13-ede3504abb28) | 100  | 60  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md](https://github.com/okta/okta-developer-docs/blob/a64132e9909881addca0dc0213ca4212de5929f1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fokta-data-model%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/76675106-5bbb-4b81-a024-d390206e01a9) | 100  | 68  | 60  | 87  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.957379c9-f57d-497f-b0b0-31a25533d185?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/b12dbe3eb6864c46d41bad67a4d2d1e4101c2c75/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/22fcba48-4d9d-408b-909b-b0605bb9e171) | 100  | 60  | 43  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md](https://github.com/okta/okta-developer-docs/blob/b12dbe3eb6864c46d41bad67a4d2d1e4101c2c75/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fokta-data-model%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/285cf249-50c6-408b-8d43-8ad92f450d73) | 100  | 68  | 60  | 87  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.0b5d1516-8dcb-4e1a-86d2-af7ceffbf474?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md](https://github.com/okta/okta-developer-docs/blob/ba5ff1a5e3270ebbcac1e50f8e42c6b94589cdf4/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fkey-rotation%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cacd6a8d-be71-4be4-bb2a-a6cd295edb82) | 100  | 60  | 43  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.431ddc71-c4d9-44c4-a83c-1965cb752678?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by vanngo-okta** [comment]
Closing bad preview PR

**Pull request closed without merging**
