### PR TITLE
[OKTA 806255/805433] Expression language fixes

### PR DESCRIPTION
**Pull request by annejuan-okta**
## Description:
- **What's changed?**  Some acrolinx fix, some notes added, clarifying text
- **Is this PR related to a Monolith release?**  N/A

### Resolves:

* [OKTA-805433](https://oktainc.atlassian.net/browse/OKTA-805433)
* [OKTA-806255](https://oktainc.atlassian.net/browse/OKTA-806255)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/5694c4a5006f6b6768e9d1dde30246bd4b4ab93c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0dc28b13-b4fb-4db9-b601-b45be3cffbf1) | 82  | 52  | 95  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.13631c3b-43ca-4dba-b8e9-7ed4b77d8168?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/ebef29afb1b6af7476094c774d69d2d6d2d02e77/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/100d5ace-506f-4ab1-8d5e-c1dff6325db7) | 82  | 52  | 95  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.5c6c337a-172d-4d23-86e3-a0c81224fe76?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/63db51f2449c7fa804c4e539f8cd38a9f8346120/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/43ca7952-77a5-4d07-b954-73dbd28d7e89) | 82  | 52  | 95  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.e25fdd18-4206-4e38-8255-78eceeb133fc?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md](https://github.com/okta/okta-developer-docs/blob/4dc2330dc9d0a444f321abf0a41ce57594210b40/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fokta-expression-language%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9f4d63de-f759-4a9a-8366-8b8c67c24ce6) | 82  | 52  | 95  | 99  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3b3886b3-96da-4ebd-aad3-e200406823f0?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Pull request merged**
