### PR TITLE
OKTA-740742 Update Role description and link

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Update Role description and link in IAM terminology and in Concepts.
- **Is this PR related to a Monolith release?** No.

### Updates:
image
image

### Resolves:

* [OKTA-740742](https://oktainc.atlassian.net/browse/OKTA-740742)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/iam-overview-iam-terminology/index.md](https://github.com/okta/okta-developer-docs/blob/09411830e872e0cd031ac378b5f68bfcac450faf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fiam-overview-iam-terminology%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/94234938-08e9-485a-a940-725df1db4cf7) | 58  | 58  | 37  | 89  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/09411830e872e0cd031ac378b5f68bfcac450faf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0128d63c-2bac-4170-bbcb-1a5ec7b8e372) | 80  | 39  | 83  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a8b06efb-7135-462a-8107-61dc934e4188?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/iam-overview-iam-terminology/index.md](https://github.com/okta/okta-developer-docs/blob/2033260c176b27111df4034d811e961949543ffa/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fiam-overview-iam-terminology%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1359c723-d06e-4e10-9118-f1b371f35b41) | 58  | 58  | 37  | 89  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/2033260c176b27111df4034d811e961949543ffa/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/237a9be0-ed7b-44f6-b520-78ae6db1e445) | 80  | 38  | 82  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.aab2eac3-feec-4a56-8c82-b937af963fad?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/iam-overview-iam-terminology/index.md](https://github.com/okta/okta-developer-docs/blob/732f1905d3b3ee63a0263f84e431f7a584f7e86b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fiam-overview-iam-terminology%2Findex.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e172cc2e-9b46-40ed-8565-6a00329143d8) | 64  | 74  | 41  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/732f1905d3b3ee63a0263f84e431f7a584f7e86b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8007b09d-39f2-4f5d-ac5a-79ecaceecdc0) | 80  | 38  | 82  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.9c1459c1-bfa5-4523-8978-667acb1b5737?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/iam-overview-iam-terminology/index.md](https://github.com/okta/okta-developer-docs/blob/4276df3b7ada08853472867a69c6e3c7e25f510e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fiam-overview-iam-terminology%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2b7e0355-5e61-4b60-b3a8-dd67eb6910b0) | 64  | 87  | 43  | 98  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/4276df3b7ada08853472867a69c6e3c7e25f510e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/44e04ff6-0fbc-4392-8501-870238681743) | 80  | 38  | 82  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.bfad66a5-a198-4e11-8266-cfaa1f807576?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Review by alimohammadi-okta — APPROVED** [review]

**Pull request merged**
