### PR TITLE
Removing AMR blurb

### PR DESCRIPTION
**Pull request by susanharper-okta**
## Description:
- **What's changed?** Removing AMR blurb
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-794656](https://oktainc.atlassian.net/browse/OKTA-794656)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/ca1824ea6b519b4bcba5b12135c44fc38106e67c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/83653f07-b23a-4732-9e2c-073e500b25dc) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/ca1824ea6b519b4bcba5b12135c44fc38106e67c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a0707eb8-2159-45be-ae78-ffbce8241c62) | 91  | 76  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/ca1824ea6b519b4bcba5b12135c44fc38106e67c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6c711a4e-1286-423a-a0bd-84c0c40e7860) | 57  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/ca1824ea6b519b4bcba5b12135c44fc38106e67c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3f348d77-6c14-4589-bb2b-f2ccc2559a04) | 51  | 68  | 76  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f679301f-0a43-455c-a823-d527eb4201cd?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/959468de8533b34b72c070c907774c2bae2e32d8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7019e531-60fe-490a-9a8a-6d18164821fd) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/959468de8533b34b72c070c907774c2bae2e32d8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/259f849e-71f6-41f7-a09d-6eea42fc844c) | 91  | 76  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/959468de8533b34b72c070c907774c2bae2e32d8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8bfbfaa4-e7c3-4205-ae5f-38ffd2ea3a43) | 57  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/959468de8533b34b72c070c907774c2bae2e32d8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c4c8dd94-ae29-46c5-9a1d-203d5b0f9037) | 51  | 68  | 76  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/959468de8533b34b72c070c907774c2bae2e32d8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/019bd83f-396c-4033-b8c2-1d5bae6df5ee) | 22  | 100  | 93  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f0fe37b9-0f33-4d60-939f-23f1f3d57694?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7a461c001614052bc454e0f3cf2132a3acfe953c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d272d0f7-45f5-434c-8ece-c08f7ec58e28) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7a461c001614052bc454e0f3cf2132a3acfe953c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3aaca854-879b-48b3-b855-9f6338ec918c) | 91  | 76  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/7a461c001614052bc454e0f3cf2132a3acfe953c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/de1bf631-f128-4146-8e4d-e849e42678bf) | 57  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/7a461c001614052bc454e0f3cf2132a3acfe953c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/034d3a55-10c6-4522-80bb-77d6c027747b) | 51  | 68  | 76  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/7a461c001614052bc454e0f3cf2132a3acfe953c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bfab94ac-1b9d-447e-8f7c-cb22b9bc489b) | 24  | 100  | 93  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ae7eb5ec-54b1-46c9-aa44-882019d70e67?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/c660c0be98b4f2616efa5234c9971a708be87f4d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b2852d0-3596-4011-9c31-ce1e1ced67d5) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/c660c0be98b4f2616efa5234c9971a708be87f4d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/033519c0-432c-4f5d-bfd9-2903e9b53c47) | 91  | 76  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/c660c0be98b4f2616efa5234c9971a708be87f4d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f1159a2e-6597-46ab-8bb0-6825933e7f78) | 57  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/c660c0be98b4f2616efa5234c9971a708be87f4d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bc57c614-0a5e-4823-b0df-331e92c9d4d7) | 51  | 76  | 76  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/c660c0be98b4f2616efa5234c9971a708be87f4d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e556089b-8094-4978-9152-5216f671cfed) | 22  | 100  | 93  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.dc439c04-84a2-4b61-95e0-d1cdadbee21a?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/c88078c57393e2461762bfc13d1a33a844dafcee/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Foktatookta%2Fappidpinokta.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2a06dc08-d978-4520-8a7c-1bb39b2b91e4) | 78  | 78  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/c88078c57393e2461762bfc13d1a33a844dafcee/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fopenidconnect%2Fappidpinokta.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bd0c1cbe-0431-480d-b0c8-a5f09457416f) | 91  | 76  | 71  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md](https://github.com/okta/okta-developer-docs/blob/c88078c57393e2461762bfc13d1a33a844dafcee/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappatidp.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/efa3f74a-c48f-4e0a-89b3-959ef3e18764) | 57  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md](https://github.com/okta/okta-developer-docs/blob/c88078c57393e2461762bfc13d1a33a844dafcee/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fadd-an-external-idp%2Fmain%2Fsaml2%2Fappidpinokta.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2672fd07-0a15-43ac-bf78-7f28dc8a3f32) | 51  | 76  | 76  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/c88078c57393e2461762bfc13d1a33a844dafcee/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b92a7930-096c-4275-a8c8-c3c938e976ef) | 24  | 100  | 93  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.bbeb787d-80d7-4d2e-8f3b-94c9974a865c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
