### PR TITLE
OKTA-710607 Deprecate SSO in OIN Manager

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Update text to deprecate edit SSO in OIN Manager use case
- **Is this PR related to a Monolith release?** 2024.09.0 (no RN ticket was produced, devdoc work delayed)

### Resolves:

* [OKTA-710607](https://oktainc.atlassian.net/browse/OKTA-710607)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/bf2d1cabc2b0eb02b0ec8aea4433da87c30b85eb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7303fea4-01a3-472b-a096-04f2ad8152e1) | 75  | 95  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/bf2d1cabc2b0eb02b0ec8aea4433da87c30b85eb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4daa0424-f336-4e08-ac09-cd21a9bd421b) | 85  | 85  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/bf2d1cabc2b0eb02b0ec8aea4433da87c30b85eb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7e4b8de7-f696-43b0-a951-7c04bc4c8cb8) | 79  | 88  | 72  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.eb26358e-ad11-47b8-9935-0e0fd53fe03e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/015cddee61af7e3d061e48a8ec7d83bca50af541/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/75b54e98-c7bf-4690-86f8-abf9944861a1) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/015cddee61af7e3d061e48a8ec7d83bca50af541/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/95f5569d-8918-43f1-ac67-c70c8020ca2b) | 55  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/015cddee61af7e3d061e48a8ec7d83bca50af541/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bb84f62b-b957-4c7c-bd9e-dca1b6d3f324) | 75  | 95  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/015cddee61af7e3d061e48a8ec7d83bca50af541/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9655edf2-2eab-48e1-8630-2c6a530b64b0) | 75  | 83  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/015cddee61af7e3d061e48a8ec7d83bca50af541/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f4830add-6ed5-42c0-88a1-d492df5d82f6) | 85  | 85  | 80  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/015cddee61af7e3d061e48a8ec7d83bca50af541/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/897d93aa-e72c-45a7-a207-02e6a7afc230) | 79  | 88  | 72  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.75d530e0-c799-41a9-9451-be77ddf99b6b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/cfec40924bdc4ae2e6983ab99104ef15ce2a615e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/288defb9-5f09-40b1-9988-3b3d1f2d54c4) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/cfec40924bdc4ae2e6983ab99104ef15ce2a615e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f44f2068-56a3-4c99-9097-30eff4e4b577) | 55  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/cfec40924bdc4ae2e6983ab99104ef15ce2a615e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/25502979-506a-4447-83bb-75702e979029) | 75  | 96  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/cfec40924bdc4ae2e6983ab99104ef15ce2a615e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c1aaca01-4d23-492a-89fd-2fadc4795855) | 75  | 83  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/cfec40924bdc4ae2e6983ab99104ef15ce2a615e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/96506795-9601-45a9-a2c0-7c39141a8e3c) | 85  | 85  | 79  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/cfec40924bdc4ae2e6983ab99104ef15ce2a615e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/213f84f1-772f-4540-8b4d-bf714e2592c7) | 79  | 88  | 72  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7ec927a7-198f-4c0e-befd-171afac982cd?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — DISMISSED** [review]
LGTM

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/1b6c6781223367c7505a04b114cfe5cf7b60427c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/94dbb804-737b-4fda-a75c-f696388c559c) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/1b6c6781223367c7505a04b114cfe5cf7b60427c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e984a556-088f-4254-b9c6-66aca20b752a) | 55  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/1b6c6781223367c7505a04b114cfe5cf7b60427c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/08f9e875-af65-46eb-8e41-8d3f45457011) | 75  | 96  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/1b6c6781223367c7505a04b114cfe5cf7b60427c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a70758b8-a546-4a4c-aa4e-1f79dc01431e) | 75  | 83  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/1b6c6781223367c7505a04b114cfe5cf7b60427c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a2d2db13-709d-48c0-80c6-918d8094c4aa) | 85  | 85  | 79  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/index.md](https://github.com/okta/okta-developer-docs/blob/1b6c6781223367c7505a04b114cfe5cf7b60427c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3217209e-e61a-42b4-895d-59ac79fd55e4) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/1b6c6781223367c7505a04b114cfe5cf7b60427c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6823d7c3-12ef-413a-82ba-25dbc61bfab8) | 79  | 88  | 72  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.d5d67fd4-53c6-483f-821d-85918c288187?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/87fa0dec6f02137d1381e0b9bce50219a569ca67/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e865630f-e489-4702-bc6b-225df17bfc75) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md](https://github.com/okta/okta-developer-docs/blob/87fa0dec6f02137d1381e0b9bce50219a569ca67/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-overview%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1689d050-b8c4-4b00-bf67-9de01ab3a3f8) | 75  | 96  | 67  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md](https://github.com/okta/okta-developer-docs/blob/87fa0dec6f02137d1381e0b9bce50219a569ca67/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app-prereq%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/01877f7d-26a6-4931-85a7-0f4edbc79e07) | 75  | 83  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/87fa0dec6f02137d1381e0b9bce50219a569ca67/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c8c2af30-cc2d-4b96-8f8f-1a26d6df72e1) | 85  | 85  | 79  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/index.md](https://github.com/okta/okta-developer-docs/blob/87fa0dec6f02137d1381e0b9bce50219a569ca67/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/285bc9fc-bd7a-4aea-960e-38d26e62da9f) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/87fa0dec6f02137d1381e0b9bce50219a569ca67/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Findex.md) | [86](https://okta.acrolinx.cloud/api/v1/checking/scorecards/927450bb-ce73-46f9-9a3f-533706f0ee9d) | 79  | 88  | 72  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b99d3681-6a21-4623-9226-8da71b5be6c4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Comment by vanngo-okta** [comment]
Approved by SME on Jira: https://oktainc.atlassian.net/browse/OKTA-710607?focusedCommentId=6181270

**Pull request merged**
