### PR TITLE
Fix-it-day placeholders for OIN section (Van)

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Fix-it-day task: update placeholders for docs under OIN section
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-729831](https://oktainc.atlassian.net/browse/OKTA-729831)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **30** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:30** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/d94c1249ace8d69645c360841df745484e6ea847/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/30c83cce-718b-4563-9820-1dd3c64fbf59) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/d94c1249ace8d69645c360841df745484e6ea847/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f3c4f5b8-4fdd-4763-a17e-9be54a6b8502) | 94  | 82  | 58  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md](https://github.com/okta/okta-developer-docs/blob/d94c1249ace8d69645c360841df745484e6ea847/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-prepare%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d5541ee8-4f96-44ef-b425-115462dba04d) | 93  | 52  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.613b8410-1845-426c-a44c-f95504a272ec?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **30** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:30** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/5eca8daa3de348ce1966f2841c4fa1ea80287d99/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d0a0c9e8-579c-4e95-baf1-d0b3c4440648) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/5eca8daa3de348ce1966f2841c4fa1ea80287d99/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/207aa4e8-266d-4cc2-8889-12ae0f8ed42b) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md](https://github.com/okta/okta-developer-docs/blob/5eca8daa3de348ce1966f2841c4fa1ea80287d99/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foin-universal-logout-overview%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3e2ea32a-380b-41ed-bec1-9bc78440adc9) | 54  | 94  | 64  | 94  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/5eca8daa3de348ce1966f2841c4fa1ea80287d99/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ec649dd9-b27e-4952-b491-b367fcc36278) | 94  | 82  | 58  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md](https://github.com/okta/okta-developer-docs/blob/5eca8daa3de348ce1966f2841c4fa1ea80287d99/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-prepare%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/73789084-b123-467b-932e-6d364b7b5258) | 93  | 52  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/backward-compatible-eg.md](https://github.com/okta/okta-developer-docs/blob/5eca8daa3de348ce1966f2841c4fa1ea80287d99/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fsaml2%2Fbackward-compatible-eg.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cae80791-fd03-44af-b04c-7f9ca1abf0ee) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md](https://github.com/okta/okta-developer-docs/blob/5eca8daa3de348ce1966f2841c4fa1ea80287d99/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fsaml2%2Fprotocol-properties.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0a6762d4-3f77-4f64-9a21-84a0286d1ec7) | 100  | 78  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.7be5580a-9634-49c0-8438-bbb360b58d9e?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **30** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:30** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/0d17a0fa1c522a831c3493d3a920fcdc4b3eba43/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/46b18aa9-2dcc-4176-a9bb-0d0cb3f9ed65) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/0d17a0fa1c522a831c3493d3a920fcdc4b3eba43/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3d87f7a4-03be-443b-abd0-969c31c5d59c) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md](https://github.com/okta/okta-developer-docs/blob/0d17a0fa1c522a831c3493d3a920fcdc4b3eba43/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foin-universal-logout-overview%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6b664330-9ebf-40d2-847c-d87c9847f30f) | 54  | 94  | 64  | 94  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/0d17a0fa1c522a831c3493d3a920fcdc4b3eba43/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/af229385-ec0a-414b-be10-456ba9f7d4b7) | 94  | 82  | 58  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md](https://github.com/okta/okta-developer-docs/blob/0d17a0fa1c522a831c3493d3a920fcdc4b3eba43/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-prepare%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/41f3e1fc-41ca-4c88-9126-bfb8216865c7) | 93  | 52  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md](https://github.com/okta/okta-developer-docs/blob/0d17a0fa1c522a831c3493d3a920fcdc4b3eba43/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fsaml2%2Fprotocol-properties.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cd46620c-4191-4093-bee6-0299a07c8daf) | 100  | 78  | 78  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.18b182b8-e479-4132-a34f-cc45e157b150?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **30** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:30** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d3a25290-e588-4645-9dfd-1e3dbdc777c1) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b508fb6a-6337-4934-b593-e527b61e3e15) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foin-universal-logout-overview%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ebca814c-cb07-4740-8d89-b8778825c0cc) | 54  | 94  | 64  | 94  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bfcce309-6f64-46e7-9d5e-27894e4b7284) | 94  | 82  | 58  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-prepare%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3ed155b3-75c9-4071-a768-b832c7b586a0) | 93  | 52  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/scim/submit.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Fscim%2Fsubmit.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3d3876ef-907b-4ab7-8c38-aac074ff71f4) | 75  | 40  | 50  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fsaml2%2Fprotocol-properties.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/84152f6a-b04d-4ae9-b124-ec301c7531ab) | 100  | 78  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/openidconnect/submit.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Fopenidconnect%2Fsubmit.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/747fb36f-a1d5-4f93-8453-b2b0408bb181) | 65  | 52  | 50  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/saml2/submit.md](https://github.com/okta/okta-developer-docs/blob/3695ba8db45fb5dadab64ef2ec17a6f4d0129204/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Fsaml2%2Fsubmit.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/bb84526d-5f7d-43fe-bf96-92f9721d68d7) | 73  | 44  | 52  | 84  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.d435ae61-de55-42c7-a515-3c6cabfc1e55?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **30** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:30** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-api-integration%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/47634cd2-1375-4db4-aebc-7910d06817c5) | 93  | 73  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fbuild-sso-integration%2Fmain%2Fopenidconnect%2Fprep.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b138ea06-5612-4c7d-aecd-f8b0a37129d2) | 64  | 79  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Foin-universal-logout-overview%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9db04413-ca0c-4c24-acc3-2c9ca52f3051) | 54  | 94  | 64  | 94  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-connect%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/50eef948-98f7-433e-822d-ac564d5ef2d3) | 94  | 82  | 58  | 96  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fscim-provisioning-integration-prepare%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ba8909bc-b370-4885-8b71-2f48e13919ad) | 93  | 52  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-app/main/scim/submit.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-app%2Fmain%2Fscim%2Fsubmit.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d3313845-4036-44af-977e-62948c7ed4d0) | 75  | 40  | 50  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/variable-desc.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fopenidconnect%2Fvariable-desc.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4a00bdb5-61c9-47de-ad9e-5b5e3e3eeafc) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/variable-desc.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Fsaml2%2Fvariable-desc.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e005b21f-4ae2-4735-b8e2-fc9c13613e61) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/openidconnect/submit.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Fopenidconnect%2Fsubmit.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ec2dd30f-3d83-4bf8-96ad-3fe35de51f6f) | 65  | 52  | 50  | 92  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/saml2/submit.md](https://github.com/okta/okta-developer-docs/blob/af312fa8326ba724baf6b00d6b09440777b46255/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-sso-app%2Fmain%2Fsaml2%2Fsubmit.md) | [70](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e8255f80-2675-4b82-933a-cc37d8327e8d) | 73  | 44  | 52  | 84  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.2e9e239c-8b5e-40b3-943a-4d6f6e916a6d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by barbaravo-okta — APPROVED** [review]

**Pull request merged**
