### PR TITLE
OKTA-688752 App provisioning connection with Okta APIs

### PR DESCRIPTION
**Pull request by vanngo-okta**
## Description:
- **What's changed?** Add **Set up an app provisioning connection** guide
- **Is this PR related to a Monolith release?** Yes, 2024.03.0 (trex fixed)

### Preview:

https://65e0a60203b95517085ae428--reverent-murdock-829d24.netlify.app/docs/guides/app-provisioning-connection/main/

### Resolves:

* [OKTA-688752](https://oktainc.atlassian.net/browse/OKTA-688752)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md](https://github.com/okta/okta-developer-docs/blob/03665a9a43c6d77fba155e81755253af82cae2c5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/677c9426-6862-4ac6-8670-0d73f1788f74) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/03665a9a43c6d77fba155e81755253af82cae2c5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/340bd140-773e-4f6f-bec0-c5bb1bb96e24) | 93  | 49  | 55  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/03665a9a43c6d77fba155e81755253af82cae2c5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0a04afe2-ca6a-4657-9ffa-18309b393e36) | 55  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3b9701e3-0d58-434b-9881-452f03ad917b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md](https://github.com/okta/okta-developer-docs/blob/90f2bad666b2d0f086ec9e4c9c775a376a8f3db8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/360a0801-63ca-410c-afca-dac1459adbf0) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/90f2bad666b2d0f086ec9e4c9c775a376a8f3db8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b95a50e9-a2eb-4d97-bf87-7ed1b01c51d1) | 93  | 55  | 55  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/90f2bad666b2d0f086ec9e4c9c775a376a8f3db8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/948897b9-8290-40ad-8372-4009be3b6279) | 55  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.cbe4235a-0b1c-4393-be36-3ef5ff76ebaf?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md](https://github.com/okta/okta-developer-docs/blob/b7d52091b84b2530a21fdc8394f10c915fa79543/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/923ebf6b-de30-4a2f-b2b9-6382c822a8fb) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/b7d52091b84b2530a21fdc8394f10c915fa79543/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7ea471aa-b9f9-49f7-8692-75d93468b9eb) | 93  | 55  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/b7d52091b84b2530a21fdc8394f10c915fa79543/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/49fe3b20-bf19-4d50-a106-b78b5dd75c54) | 55  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.ee462926-0af5-4efa-8285-7229cc798774?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md](https://github.com/okta/okta-developer-docs/blob/5b9b3cacd2d6b37d2c89b3724087821d1dd8a932/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c696bb6f-237f-4d95-94dc-ebe85e0185bc) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/5b9b3cacd2d6b37d2c89b3724087821d1dd8a932/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c7709447-c661-4239-b886-98d997ca358b) | 87  | 55  | 63  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/5b9b3cacd2d6b37d2c89b3724087821d1dd8a932/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a4c59778-9488-483c-a862-5b95914fab61) | 55  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3b2d6afb-2d83-428f-bc50-2385950d1e20?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md](https://github.com/okta/okta-developer-docs/blob/88d99e0be6f8b053aef230e9de8f40bc8ea7510e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c1cc7332-1b15-49c1-b356-ed5c34f70665) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/88d99e0be6f8b053aef230e9de8f40bc8ea7510e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/6cb24491-75b5-4f80-9575-902a4c8a9259) | 87  | 55  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/88d99e0be6f8b053aef230e9de8f40bc8ea7510e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/aec025bd-c373-4b42-92e6-94e420a2b028) | 55  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.bf727b99-5ff5-4424-a77f-24ba4ceb94c8?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by vanngo-okta** [comment]
Approved by SMEs on Slack and Google doc (JeffT, SurajS, MeghnaD, StephanieS)

**Review by grahamsmith-okta — DISMISSED** [review]

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md](https://github.com/okta/okta-developer-docs/blob/31775a4620213feb4843a83cab4fd049180d2491/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Findex.md) | [100](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b789d2e-2a42-4b52-bd8f-38cbce92ed33) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md](https://github.com/okta/okta-developer-docs/blob/31775a4620213feb4843a83cab4fd049180d2491/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fapp-provisioning-connection%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/38d7c191-6caf-4984-8931-6f3d9a16f123) | 87  | 55  | 66  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/31775a4620213feb4843a83cab4fd049180d2491/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c1f869c3-5047-431c-9256-fd3a1a68b504) | 55  | 55  | 86  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.42e3d219-5dc5-4b2f-8c75-fe1ab98eb444?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
