### PR TITLE
OKTA-672041 - Monthly Release

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Doc updates and release notes for the December monthly release
- **Is this PR related to a Monolith release?** 2023.12.0

### Resolves:

* [OKTA-672041](https://oktainc.atlassian.net/browse/OKTA-672041)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/reference/api/policy/index.md](https://github.com/okta/okta-developer-docs/blob/631d336a8dbeca0317e02edaba9a04f9d3b3ae54/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fpolicy%2Findex.md) | 69 | 511 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/43e34569-fa2c-4d80-9421-52c585b9e772) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.f6f6154c-f3db-4b15-9b02-511f13e18769?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/data/error-codes.json](https://github.com/okta/okta-developer-docs/blob/b184a89458a15ae1b8781c2b6341303b258cf239/packages%2F%40okta%2Fvuepress-site%2Fdata%2Ferror-codes.json) | 52 | 1208 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dfd70cc7-dc8b-42ea-8f8a-1bbdfefdb320) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/data/event-types.json](https://github.com/okta/okta-developer-docs/blob/b184a89458a15ae1b8781c2b6341303b258cf239/packages%2F%40okta%2Fvuepress-site%2Fdata%2Fevent-types.json) |   |   | [→]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [packages/@okta/vuepress-site/data/oauth2-error-codes.json](https://github.com/okta/okta-developer-docs/blob/b184a89458a15ae1b8781c2b6341303b258cf239/packages%2F%40okta%2Fvuepress-site%2Fdata%2Foauth2-error-codes.json) | 58 | 1360 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3ea36ef4-d277-40bc-b1dc-253e9fc90650) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/reference/api/policy/index.md](https://github.com/okta/okta-developer-docs/blob/b184a89458a15ae1b8781c2b6341303b258cf239/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Freference%2Fapi%2Fpolicy%2Findex.md) | 69 | 511 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/db078d13-a743-4843-85c7-82eee290cd7e) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md](https://github.com/okta/okta-developer-docs/blob/b184a89458a15ae1b8781c2b6341303b258cf239/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023-okta-identity-engine%2Findex.md) | 72 | 519 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/62d54e5a-d033-48b3-9148-0cec413f067b) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/docs/release-notes/2023/index.md](https://github.com/okta/okta-developer-docs/blob/b184a89458a15ae1b8781c2b6341303b258cf239/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Frelease-notes%2F2023%2Findex.md) | 74 | 361 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f9404c3e-dd04-4203-8ca7-ae2454e5b277) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 5 of 6 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.8ce6a02e-15a9-4efd-b748-b8746df04c2c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by susanharper-okta — COMMENTED** [review]
couple things

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Comment by brianduffield-okta** [comment]
Closing to try and fix Acorlinx error

**Pull request closed without merging**
