### PR TITLE
Import Nim SCSS

### PR DESCRIPTION
**Pull request by alexdahl-okta**
## Description:

Nim is Okta's work-in-progress design system.

- Adds Nim as a theme package dependency
- Imports Nim's SCSS
- Tweaks some markup to prevent major visual changes
- Updates theme readme

There are some minor visual changes:
- typography, spacing, etc
- new external link icon
- new visited link color

But overall this should **not** affect layouts or look-and-feel. Adoption of Nim styles by our components is still to come.

links

front-example

### CODE REVIEW

**Comment by alexdahl-okta** [comment]
@bretterer @brettritter-okta, could I get a review (and merge, if good) when one of you has a chance?

FYI @nbarbettini

**Comment by alexdahl-okta** [comment]
While this is still open, bumping to a new Nim version. This will add a couple visual changes – external link icons and visited link color.

**Comment by nbarbettini** [comment]
@alexdahl-okta You're good to update and merge.

**Comment by alexdahl-okta** [comment]
@nbarbettini 🙇‍♂️ Conflict resolved – only lock file change here now is addition of `@okta/nim`, which feels right?

I don't have merge authorization, so assuming CI passes, would appreciate a click. 🤓

**Pull request merged**
