### PR TITLE
Push Providers API: deprecate VuePress page, etc.

### PR DESCRIPTION
**Pull request by brentschaus-okta**
## Description:
- **What's changed?** Deprecates the Push Providers API content in VuePress.
- **Is this PR related to a Monolith release?** No.

### Resolves:

* [OKTA-740804](https://oktainc.atlassian.net/browse/OKTA-740804)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/fda086b4bc4ef7ba07574bdb884a31c84b1cd313/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fandroid%2Fnotifserviceadminconsole.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e92e5824-9377-41be-a3f9-565cab11e4b8) | 45  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/fda086b4bc4ef7ba07574bdb884a31c84b1cd313/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fios%2Fnotifserviceadminconsole.md) | [64](https://okta.acrolinx.cloud/api/v1/checking/scorecards/869320b6-2821-4b21-b06d-763b06db9b2a) | 42  | 52  | 68  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.c0ef964d-ddb2-464e-9831-c09ae8448174?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/f088af6c8c0194c9085376171784d2dd86f8cc20/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fandroid%2Fnotifserviceadminconsole.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/68107d10-d79d-4073-a2a9-e2e3d8ec656a) | 45  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/f088af6c8c0194c9085376171784d2dd86f8cc20/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fios%2Fnotifserviceadminconsole.md) | [64](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a2075b06-483c-4e11-a5e1-4510dfc230b2) | 42  | 52  | 68  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.173c5d73-4874-41e0-a18d-a6796e550462?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/5d0c954bbf981f931940a1326e072120f22451ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fandroid%2Fnotifserviceadminconsole.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9cfcdc38-6511-4e36-aac7-67d20c1f42f2) | 43  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/5d0c954bbf981f931940a1326e072120f22451ac/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fios%2Fnotifserviceadminconsole.md) | [64](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b50cea0-e017-46dc-830c-790c3c23fc3d) | 42  | 52  | 68  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f487dbd1-4f62-4d38-94d5-c9070e94526c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/b3b1c382ce97db7d0c117be8f89f35843611a3db/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fandroid%2Fnotifserviceadminconsole.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ec7c7db0-ee7a-4abe-bd10-eb3bdef6545c) | 43  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/b3b1c382ce97db7d0c117be8f89f35843611a3db/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fios%2Fnotifserviceadminconsole.md) | [77](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e5b3103d-83a9-405d-8bb2-a1a238c1d797) | 41  | 68  | 68  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.6de8e56f-9be6-4f33-a744-c29ac9d412de?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/c3d66e51d122ed8f690bf0583b730999bc588a82/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fandroid%2Fnotifserviceadminconsole.md) | [83](https://okta.acrolinx.cloud/api/v1/checking/scorecards/dabdece6-0698-4bb6-8ad8-4b85373fd8c9) | 43  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/notifserviceadminconsole.md](https://github.com/okta/okta-developer-docs/blob/c3d66e51d122ed8f690bf0583b730999bc588a82/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fauthenticators-custom-authenticator%2Fmain%2Fios%2Fnotifserviceadminconsole.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2218b592-2309-483b-93cb-a034362c1974) | 100  | 41  | 67  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.8b47b70d-d4ad-446c-aeec-88b2f7762961?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Pull request merged**
