### PR TITLE
SIW3 Odyssey updates

### PR DESCRIPTION
**Pull request by brentschaus-okta**
## Description
- **What's changed?** Odyssey has released v1.0 which changes how SIW3 handles customizations.
- **Is this PR related to a Monolith release?** Yes. 2024.03.0

## Netlify preview
https://65e77d7b66c37a6cbea07402--reverent-murdock-829d24.netlify.app/docs/guides/custom-widget-gen3/main/

### Resolves
* [OKTA-702856](https://oktainc.atlassian.net/browse/OKTA-702856)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md](https://github.com/okta/okta-developer-docs/blob/5570de0a01a6c39cad84505b1ff0267b033f148c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-widget-gen3%2Fmain%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ca687276-0b98-40f2-8824-e5752d12bcaf) | 82  | 25  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b525a25f-779b-49d6-8d65-0ffe85d2c76d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md](https://github.com/okta/okta-developer-docs/blob/4e4d697bf84603fc676d8bc938ef2b8b26fc88b1/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-widget-gen3%2Fmain%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e7e8fb1e-3511-45c7-ae8c-0a0bca3b18a9) | 82  | 25  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.3732f4b6-4ff5-4053-b099-b67f97215c5d?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md](https://github.com/okta/okta-developer-docs/blob/8dd4aab08242b72587278b675a50848567803aa2/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-widget-gen3%2Fmain%2Findex.md) | [76](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1b620b41-2ef0-449e-a27d-489fc895767e) | 82  | 25  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.fcdda2fc-0dbc-47c2-9d26-c9c40a23f72f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md](https://github.com/okta/okta-developer-docs/blob/fcb5f7797e5a8f9bf4d80fd3cfd6594f9c92d135/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustom-widget-gen3%2Fmain%2Findex.md) | [78](https://okta.acrolinx.cloud/api/v1/checking/scorecards/88f63fe4-2ffb-4ba1-80f8-df40b5a7dde2) | 73  | 31  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.08daf908-aacc-4fec-8241-2ddb87d442ca?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
