### PR TITLE
Add security headers for Netlify

### PR DESCRIPTION
**Pull request by mraible**
Currently, we have an F on securityheaders.com for developer.okta.com. This PR aims to fix that, but will only work on Netlify. 

Screen Shot 2021-09-09 at 4 10 40 PM

https://securityheaders.com/?q=developer.okta.com&followRedirects=on

## Description:
- **What's changed?** Add security headers so we get a better score on securityheaders.com
- **Is this PR related to a Monolith release?** No

### Resolves:

* Security issues

### CODE REVIEW

**Comment by mraible** [comment]
Now it's an A!

Screen Shot 2021-09-09 at 5 30 12 PM

https://securityheaders.com/?q=https%3A%2F%2Ftender-feynman-e0f54c.netlify.app%2F&followRedirects=on

**Comment by mraible** [comment]
@albertchen-okta @chrisdmills-okta You can find a preview of this PR with A-rated security headers at https://tender-feynman-e0f54c.netlify.app/. I don't see any errors in my developer console with this PR's content security policy. 

Are there any pages on d.o.c that have inline scripts, CSS, or XHR calls? If so, we'll want to QA those and see if there are any issues this CSP (Content Security Policy) causes.

**Comment by chrisdmills-okta** [comment]
Thanks @mraible , this is really cool.  guess it would be good to start by getting one of our platform developers to look at this and provide comment. @shawyu-okta do you have any time to look into this?

**Comment by shawyu-okta** [comment]
We definitely have XHR (w/ CORS) in the signup forms. Not 100% sure about inline scripts or CSS but I _do_ think there is at least one within documentation for testing CORS configuration. We could ideally QA this change in the `staging` environment before merging.

**Comment by mraible** [comment]
@shawyu-okta Is the staging environment on Netlify? This change to add security headers will only work on Netlify.

**Comment by shawyu-okta** [comment]
Hey @mraible I should have realized earlier but our prod site isn't deployed on Netlify and instead deployed on AWS S3 behind a CloudFront distribution, so this change wouldn't improve anything as far as the security headers go there. Netlify is only used for temporary PR deploys, so should never be used by end-users.

**Comment by mraible** [comment]
@shawyu-okta You are correct. However, I talked to @albertchen-okta last week and he said he was open to moving everything to Netlify.

**Comment by shawyu-okta** [comment]
Ok, understood. 

I failed to answer your original question: `staging` is not on Netlify, but a parallel AWS environment.

**Comment by mraible** [comment]
@shawyu-okta I tried that and it didn't work, so I integrated Netlify with my fork and this branch. You can find the result at https://tender-feynman-e0f54c.netlify.app/. The signup page seems to be free from errors now.

**Pull request closed without merging**
