### PR TITLE
fix(docs): Typos and vendor proper capitalization

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Description:
- **What's changed?** 
  - Fixes a few minor typos in the doc caught with `mdspell`.
  - Also properly cases GitHub and HashiCorp to align to how those vendors/products are marketed. (Trivial, but drives consistency)
- **Is this PR related to a Monolith release?** 
  - No.

### Resolves:

* [OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)

Note: I've not signed the Okta CLA, but believe this falls into the "obvious fix" category.

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/books/api-security/sanitizing/attack-vectors/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fbooks%2Fapi-security%2Fsanitizing%2Fattack-vectors%2Findex.md) | [66](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7a73ab7d-bdda-477d-9206-e2d40813ac2f) | 72  | 50  | 46  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/dotnet/aspnet/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fdotnet%2Faspnet%2Findex.md) | [66](https://okta.acrolinx.cloud/api/v1/checking/scorecards/494874d8-42c1-4dd4-ba1b-224fd88397cd) | 43  | 60  | 39  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/ios/quickstart-appauth-swift/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fios%2Fquickstart-appauth-swift%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/338f049c-f776-47e4-8c48-94f636141596) | 49  | 63  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/java/spring_security_saml/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fjava%2Fspring_security_saml%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b5343b78-ca5e-41e3-914c-55b4ad635040) | 66  | 60  | 58  | 93  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fjavascript%2Fokta_auth_sdk%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/309b86fc-1580-4bb6-8bdb-2038d8d3f756) | 82  | 64  | 65  | 90  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/python/pysaml2/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fpython%2Fpysaml2%2Findex.md) | [60](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8bbb088a-3826-4e19-bb10-86e25ac01f76) | 49  | 60  | 57  | 68  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsaml-inline-hook%2Fmain%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1ad3432c-dd52-4db1-ba35-8f8931a53788) | 30  | 78  | 61  | 95  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/download-sample.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Fangular%2Fdownload-sample.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/98c907b2-85a1-4975-8be3-366eb27d87c1) | 37  | 54  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/useaccesstoken.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-into-spa-redirect%2Fmain%2Fvue%2Fuseaccesstoken.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0ace3afb-1504-489e-97ef-d6aec7aec1fe) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a274b151-128a-404e-9f73-4e6389f6b306) | 75  | 87  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-design-access-security/main/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-design-access-security%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fa7589b2-3ba1-42f5-a735-fa05a2425977) | 100  | 60  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-enable-org-access%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b37c6b98-5c11-4a7f-97d3-f81692e1238e) | 94  | 59  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-overview%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5609c71d-adc4-4a34-9900-a72dc94c5ddf) | 100  | 84  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/3842556dd535b8e98899156f108453338c1fbdfb/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a2b8b9f8-8a56-42a4-8916-cf427823c572) | 85  | 80  | 67  | 97  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a80fcd15-7edc-4bae-bc30-2751cabeb543?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/books/api-security/sanitizing/attack-vectors/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fbooks%2Fapi-security%2Fsanitizing%2Fattack-vectors%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d3c6b43c-96b5-4db1-ae30-d14a5bab2392) | 71  | 55  | 50  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/dotnet/aspnet/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fdotnet%2Faspnet%2Findex.md) | [66](https://okta.acrolinx.cloud/api/v1/checking/scorecards/cbf8eaf6-0c4b-447d-b8ae-030446b06ddd) | 43  | 60  | 39  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/ios/quickstart-appauth-swift/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fios%2Fquickstart-appauth-swift%2Findex.md) | [69](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ebd2648d-f950-4154-838c-97d47235be1a) | 49  | 63  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/java/spring_security_saml/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fjava%2Fspring_security_saml%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/baf5a070-4a72-496b-bd32-cd73f22f1360) | 66  | 60  | 58  | 93  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fjavascript%2Fokta_auth_sdk%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b0f39daf-f02b-4497-9236-3f8d04213bc5) | 82  | 64  | 65  | 90  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/python/pysaml2/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fpython%2Fpysaml2%2Findex.md) | [62](https://okta.acrolinx.cloud/api/v1/checking/scorecards/790bb047-e6ad-43c3-8a5d-6f2e571d7fda) | 50  | 64  | 58  | 68  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsaml-inline-hook%2Fmain%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/62455cff-4ea5-4fd1-a1e2-b2b0fa3e803f) | 30  | 78  | 61  | 95  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/download-sample.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Fangular%2Fdownload-sample.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/27de6146-d961-4f36-a9a5-f798da8fbaee) | 37  | 54  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/useaccesstoken.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-into-spa-redirect%2Fmain%2Fvue%2Fuseaccesstoken.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/0a5ed589-317c-42c9-ade3-2b3f0b258e11) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4e007154-f8b0-4383-a1f7-0e5e5821841f) | 75  | 87  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-design-access-security/main/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-design-access-security%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/617b7e02-5c60-4aeb-bb29-bbab71018c9f) | 100  | 60  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-enable-org-access%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b6d0e013-b266-4c2b-9ebe-eff33ebc8b5f) | 94  | 59  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-overview%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4dd1669c-e04e-4cab-b397-568b4478dde6) | 100  | 84  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/3183b80db198882e084528f8b4f62ba5bb51bedf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8c31e1bb-9924-4bef-aa99-e6193bffd059) | 85  | 80  | 67  | 97  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.af5c21aa-f9ad-4798-a1dc-4c54a25236b4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:70** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/books/api-security/sanitizing/attack-vectors/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fbooks%2Fapi-security%2Fsanitizing%2Fattack-vectors%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e93f050b-f6d5-4cde-9a8b-9530545cb447) | 71  | 55  | 50  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/dotnet/aspnet/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fdotnet%2Faspnet%2Findex.md) | [65](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fb67a1bf-4d4e-4e69-a0ea-00139e745cfd) | 43  | 60  | 39  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/ios/quickstart-appauth-swift/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fios%2Fquickstart-appauth-swift%2Findex.md) | [72](https://okta.acrolinx.cloud/api/v1/checking/scorecards/40da10bb-188c-47af-bd42-e0b168e7f79a) | 49  | 77  | 69  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/java/spring_security_saml/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fjava%2Fspring_security_saml%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1170a1ea-e51b-43b1-b70d-0cc92624c3a9) | 66  | 60  | 58  | 93  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fjavascript%2Fokta_auth_sdk%2Findex.md) | [74](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e8a879d3-58ad-49e8-a8e6-7539d0ae7147) | 82  | 64  | 65  | 90  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/code/python/pysaml2/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fcode%2Fpython%2Fpysaml2%2Findex.md) | [62](https://okta.acrolinx.cloud/api/v1/checking/scorecards/183dfa8c-d349-4e50-af1e-ec7206404f9e) | 49  | 64  | 57  | 68  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsaml-inline-hook%2Fmain%2Findex.md) | [71](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9f68a81a-91c1-4bb9-bed5-f7d39d2c4357) | 30  | 78  | 61  | 95  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/download-sample.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Fangular%2Fdownload-sample.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7148603a-578f-423c-a2cf-6370ffc3271f) | 37  | 54  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/useaccesstoken.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-into-spa-redirect%2Fmain%2Fvue%2Fuseaccesstoken.md) | [81](https://okta.acrolinx.cloud/api/v1/checking/scorecards/8b7a3117-db62-4e86-bbaa-ea1606fc4cd1) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsubmit-oin-app%2Fmain%2Findex.md) | [85](https://okta.acrolinx.cloud/api/v1/checking/scorecards/81fa54e9-7619-4d62-b821-8c7583f5a0ad) | 75  | 87  | 77  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-design-access-security/main/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-design-access-security%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7914a1ab-2226-4692-a18f-06be552fce1d) | 100  | 60  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-enable-org-access%2Fmain%2Findex.md) | [84](https://okta.acrolinx.cloud/api/v1/checking/scorecards/97ee3a57-2ea1-4b38-b693-f65b3964bddc) | 94  | 59  | 83  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/terraform-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fterraform-overview%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/99e22df3-9be1-4cf2-9cae-9b9ba21dc10d) | 100  | 84  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md](https://github.com/okta/okta-developer-docs/blob/c9859f42399e24f0d284eef63c9503eb552f95d5/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Ftoken-inline-hook%2Fmain%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e4a8fce8-c668-4eda-97f5-4fed2fcdceb0) | 85  | 80  | 67  | 97  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.2ea37a3e-ba4d-4cee-9c5a-c185389d9936?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by brianduffield-okta** [comment]
Many thanks for raising this PR, @adamdmharvey . It's somewhat disconcerting to see this many typos, but clearly highlights we need to be doing a repo-wide check. And we're on it. We'll raise another PR to address the typos/format updates, but we'll need our engineering team to review some of your code updates. Thanks again.

**Comment by adamdmharvey** [comment]
Great!  Indeed, I only intended to supply some of the wording fixes, but the Acrolinx wasn't happen with a number of pages.  Alternatively, I'm happy to revert my editorial commits to return this to a purely typo PR if you and other maintainers are happy w/ Acrolinx job failing ( below the 70 threshold).

Let me know!

**Comment by brianduffield-okta** [comment]
@adamdmharvey Thanks again. I opened a new PR as I had to modify a few of the items you flagged in keeping with our house style and found a few other items. I thought there were a few code updates in your PR but as I went through it I noticed it was more formatting, so, no need for an engineering review. I've merged this PR: [https://github.com/okta/okta-developer-docs/pull/4687](https://github.com/okta/okta-developer-docs/pull/4687), which addresses the majority of the items you flagged. If it's okay, I'll close your PR. 

Again, many thanks for improving the docs! Feel free to open another PR or issue if you see anything else.

**Pull request closed without merging**
