### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
fix error

### CODE REVIEW

**Comment by brianduffield-okta** [comment]
Thanks @gabrielsroka Will confirm this update with engineering. Reproduced on my side as well.

**Review by apoorvadeshpande-okta — APPROVED** [review]

**Review by brianduffield-okta — APPROVED** [review]
LGTM

**Comment by brianduffield-okta** [comment]
Travis blocking this update. Reproduced in https://github.com/okta/okta-developer-docs/pull/3832. Will close this PR when new one merged.

**Comment by brianduffield-okta** [comment]
Closing this PR. Update merged in https://github.com/okta/okta-developer-docs/pull/3832 Thanks again, @gabrielsroka

**Pull request closed without merging**
