### PR TITLE
Roles API deprecation

### PR DESCRIPTION
**Pull request by annejuan-okta**
## Description:
- **What's changed?**  Roles deprecation on Vuepress
- **Is this PR related to a Monolith release?**  none

### Resolves:

* [OKTA-804327](https://oktainc.atlassian.net/browse/OKTA-804327)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/f918a6e5fd1249fb90dfa3b731ce3f50d1a05b4e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5168a49a-874f-4f0e-85ea-a754c6c20592) | 80  | 38  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/f918a6e5fd1249fb90dfa3b731ce3f50d1a05b4e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/06e60242-dced-470d-9faa-0a1a57771f8b) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/f918a6e5fd1249fb90dfa3b731ce3f50d1a05b4e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9ce0c4e1-ff0b-4c4a-9c6d-54c8ef47acb7) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.d38ea731-4896-4c5d-92a0-3fd0686e617b?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by vanngo-okta — DISMISSED** [review]
A few nits. Everything else looks good! Thanks for doing this @annejuan-okta ! 🙏

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/d3a07f3fda300fca967370e91deb789a02e19f37/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a082e053-23b2-4c0a-8859-f5b2d41d9b09) | 80  | 38  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/d3a07f3fda300fca967370e91deb789a02e19f37/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/827e002a-f0a9-471d-8fbd-d8b7698d596f) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/d3a07f3fda300fca967370e91deb789a02e19f37/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ccc94e5f-1191-4cd5-baae-1c9efb6afc3f) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.80dca932-5adc-4972-b36a-7ece2cd27bbb?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/1a4ed911493d49a2ab08ec625c21c9fd058f762f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [79](https://okta.acrolinx.cloud/api/v1/checking/scorecards/2eeedc54-11aa-49ee-8b20-c717fc28dc05) | 80  | 38  | 78  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/1a4ed911493d49a2ab08ec625c21c9fd058f762f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/60c05974-0c28-4d46-9a38-20e10ccbdfc5) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/1a4ed911493d49a2ab08ec625c21c9fd058f762f/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c98cdd6e-66fa-496f-ae6c-a813965c60d6) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.088d3e82-7e53-476a-bdb0-ff29708eae73?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — COMMENTED** [review]
couple edits

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/a405009abbebe49baad21e9838640759c2e17f4c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/51ec7cee-594f-458f-9802-6c7862405758) | 80  | 38  | 85  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/a405009abbebe49baad21e9838640759c2e17f4c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/fd6a9844-7134-4368-a066-4d75a456c92a) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/a405009abbebe49baad21e9838640759c2e17f4c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f24a1781-c2e4-47d1-bc79-b35b06a2ae0b) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.912e6866-5d14-4485-9685-ed7aaf1760d4?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/21ab178ba9362d756e5c9db5818bb1b780917e9e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b889fca7-87b4-4d6d-9799-804021d120d0) | 80  | 38  | 85  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/21ab178ba9362d756e5c9db5818bb1b780917e9e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/172f84e0-34bb-46b4-999b-8599ef58ca64) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/21ab178ba9362d756e5c9db5818bb1b780917e9e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/83d0487f-6eac-4003-bfcb-79452b9f2f11) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.f03e62f3-7bf8-4c43-922f-1433d70930b2?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/df55758fd7129924eaed96fd8d17deadc0f5182c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/820e4af6-e91e-44fc-8f88-f459b3135b00) | 80  | 38  | 85  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/df55758fd7129924eaed96fd8d17deadc0f5182c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/37ca5223-def7-424f-ba2e-961987fd2c50) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/df55758fd7129924eaed96fd8d17deadc0f5182c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ba9cd233-2296-47b9-affd-aff65b75627a) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.70c0e703-9ea9-4780-a240-4ab5089fc7e8?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/0c6d3244a99054c852c75f794ce01af66db9e918/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/aecdfa92-5d3a-4c22-9878-f0f840d76aa5) | 80  | 38  | 85  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/0c6d3244a99054c852c75f794ce01af66db9e918/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/e925039d-c18f-4c14-afc6-57ed210b4113) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/0c6d3244a99054c852c75f794ce01af66db9e918/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f9260669-f989-4994-8ba5-92aea1a10fdb) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.a610f9c9-ebb9-4c8c-91b6-c52aa7c1bc62?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md](https://github.com/okta/okta-developer-docs/blob/f4b200ca31769da03bb4f208bf18e61c7ef4510b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Frole-assignment%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/27ebfd80-c4e8-466f-a495-c46de5fa2ec7) | 80  | 38  | 85  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md](https://github.com/okta/okta-developer-docs/blob/f4b200ca31769da03bb4f208bf18e61c7ef4510b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fimplement-oauth-for-okta-serviceapp%2Fmain%2Findex.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/29608d37-74d1-4428-86b5-509510fe4886) | 100  | 76  | 100  | 97  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md](https://github.com/okta/okta-developer-docs/blob/f4b200ca31769da03bb4f208bf18e61c7ef4510b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsecure-oauth-between-orgs%2Fmain%2Findex.md) | [89](https://okta.acrolinx.cloud/api/v1/checking/scorecards/ead4056c-96df-43f8-b280-8e77fb382b7d) | 96  | 93  | 81  | 91  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.740eee5e-b927-44c8-b9e4-e1477367aac6?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Pull request merged**
