### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
fix typo

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md](https://github.com/okta/okta-developer-docs/blob/026399b4e6ff7147b775b6ea3dbf96bd05c48566/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fcustomize-tokens-static%2Fmain%2Findex.md) | 71 | 145 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/c3314cec-187a-4f1d-8cf9-be27c5adb397) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.1881e49c-e067-4c40-9421-b8be80ecabce?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by brianduffield-okta** [comment]
Thanks for the PR, Gabriel. Happy New Year. We'll get this reviewed and merged shortly.

**Review by timhowie-okta — APPROVED** [review]
lgtm

**Review by MarkCowan-okta — APPROVED** [review]
lgtm

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
