### PR TITLE
OKTA-735460 - Update CAE content in Policies Concept

### PR DESCRIPTION
**Pull request by brianduffield-okta**
## Description:
- **What's changed?** Changing name of Continuous auth evaluation to Post auth session evaluation
- **Is this PR related to a Monolith release?** 2024.07.0

### Resolves:

* [OKTA-735460](https://oktainc.atlassian.net/browse/OKTA-735460)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/3ec3e4975c6e4f0ed8d1f8ef13e2b974bc9ea88d/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/7597e850-3436-47ca-a2c2-1c200f133c70) | 67  | 84  | 66  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.319d12e6-d3d8-40ae-848b-0faf5ef505ef?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/concepts/policies/index.md](https://github.com/okta/okta-developer-docs/blob/350776b3832669a841983c19abb7855d729b2440/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fconcepts%2Fpolicies%2Findex.md) | [82](https://okta.acrolinx.cloud/api/v1/checking/scorecards/5b378196-2914-4aee-8ad9-20b28d836070) | 67  | 84  | 66  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.8aa4724f-1cd5-46e7-b932-22961a9f6a4f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Comment by brianduffield-okta** [comment]
@lalithapidaparthi-okta thumbs up online

**Pull request merged**
