### PR TITLE
OKTA 694578 Delete archived topic

### PR DESCRIPTION
**Pull request by thomascavanagh-okta**
## Description:
- **What's changed?** 
   - Deleted the **Sign in to SPA with embedded Widget** page
   - Removed references to the page
   - Updated the conductor.yml file
   - Updated the left hand nav .js file
- **Is this PR related to a Monolith release?** No

### Resolves:

* [OKTA-694578](https://oktainc.atlassian.net/browse/OKTA-694578)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/3eb8a966d2e9f90caf141fb507cd37f52b2ac143/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-overview%2Fmain%2Findex.md) | [65](https://okta.acrolinx.cloud/api/v1/checking/scorecards/644fe5a0-6f7f-4a1b-b804-94aebae7370f) | 31  | 76  | 19  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/3eb8a966d2e9f90caf141fb507cd37f52b2ac143/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4a8b49e6-1a4c-48f6-bf9e-7c3f7b20913a) | 55  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/nutrition.md](https://github.com/okta/okta-developer-docs/blob/3eb8a966d2e9f90caf141fb507cd37f52b2ac143/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Fangular%2Fnutrition.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/427a0365-454d-4be3-97f3-be159f096df5) | 100  | 56  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/nutrition.md](https://github.com/okta/okta-developer-docs/blob/3eb8a966d2e9f90caf141fb507cd37f52b2ac143/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Freact%2Fnutrition.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a434d844-601e-4889-aa71-35ef09466d9c) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/nutrition.md](https://github.com/okta/okta-developer-docs/blob/3eb8a966d2e9f90caf141fb507cd37f52b2ac143/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Fvue%2Fnutrition.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1e235f32-5eee-4dd9-9f3d-0a9bcc1aae8c) | 100  | 63  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.b01f831d-d0a3-49c6-b107-068513a2a64c?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx score

A minimum Acrolinx Score of **80** is required. The total score is an average of the subscores.

Select **Total score** to review the Acrolinx scorecard for your article. Try to increase your individual scores, for example: Correctness. Your content will be clearer and more consistent.

| Article | **Total score**<br />**Required:80** | Word and phrases<br />(Brand, terms)<br />Preferred: 80 | Correctness<br />(Spelling, grammar)<br />Preferred: 80 | Clarity<br />(Readability)<br />Preferred: 80 | Inclusive language<br />(+ accesibility)<br />Preferred: 80 |
|---------|:------------------------------------:|:--------------------------------------------------------:|:--------------------------------------------------------:|:---------------------------------------------:|:------------------------------------------------------------:|
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/archive-overview/main/index.md](https://github.com/okta/okta-developer-docs/blob/afcd59cfa1bf2f938caa2d777f91950dc68b466e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Farchive-overview%2Fmain%2Findex.md) | [65](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f576b2fc-309f-431c-8164-29881d73b1ac) | 31  | 76  | 19  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/index.md](https://github.com/okta/okta-developer-docs/blob/afcd59cfa1bf2f938caa2d777f91950dc68b466e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Findex.md) | [80](https://okta.acrolinx.cloud/api/v1/checking/scorecards/db675826-e66a-4b79-86b8-b29e3fc6f531) | 55  | 55  | 86  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/nutrition.md](https://github.com/okta/okta-developer-docs/blob/afcd59cfa1bf2f938caa2d777f91950dc68b466e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Fangular%2Fnutrition.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/f9727b87-71dc-4550-baec-974089ba0f4a) | 100  | 56  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/nutrition.md](https://github.com/okta/okta-developer-docs/blob/afcd59cfa1bf2f938caa2d777f91950dc68b466e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Freact%2Fnutrition.md) | [88](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d881d0ae-e388-4d57-a443-dacb80e6b47d) | 100  | 100  | 100  | 100  |
| [:white_check_mark:](# "Successfully processed") [packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/nutrition.md](https://github.com/okta/okta-developer-docs/blob/afcd59cfa1bf2f938caa2d777f91950dc68b466e/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fsign-in-to-spa-embedded-widget%2Fmain%2Fvue%2Fnutrition.md) | [87](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4d275663-9efd-46cd-9ca5-b75791d74916) | 100  | 63  | 100  | 100  |

  - Scorecard links, by default, are only good for 7 days. [Link for this commit's Content Analysis Report](https://okta.acrolinx.cloud/api/batch/gen.github.86fa98aa-fd36-4968-8d02-23eb2e6996c0?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

**Review by susanharper-okta — APPROVED** [review]
LGTM

**Review by brianduffield-okta — APPROVED** [review]
LGTM!

**Pull request merged**
