### PR TITLE
OKTA-681515: Changed okta branding logo to new logo

### PR DESCRIPTION
**Pull request by ishan-krishna-okta**
## Description:
- **What's changed?** Changed Okta branding logo to new logo

### Resolves:

* [OKTA-681515](https://oktainc.atlassian.net/browse/OKTA-681515)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/.vuepress/public/favicon/browserconfig.xml](https://github.com/okta/okta-developer-docs/blob/c4990763da8bbd8892a75e6a85bd906cc8221d84/packages%2F%40okta%2Fvuepress-site%2F.vuepress%2Fpublic%2Ffavicon%2Fbrowserconfig.xml) | 100 | 6 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/4c9eb1f6-3f80-4e97-ab24-a55a6385737a) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/.vuepress/public/favicon/favicon.svg](https://github.com/okta/okta-developer-docs/blob/c4990763da8bbd8892a75e6a85bd906cc8221d84/packages%2F%40okta%2Fvuepress-site%2F.vuepress%2Fpublic%2Ffavicon%2Ffavicon.svg) | 86 | 8 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/1b9b5a32-a06f-4abc-8c3d-9cb761face86) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/.vuepress/public/favicon/manifest.json](https://github.com/okta/okta-developer-docs/blob/c4990763da8bbd8892a75e6a85bd906cc8221d84/packages%2F%40okta%2Fvuepress-site%2F.vuepress%2Fpublic%2Ffavicon%2Fmanifest.json) | 76 | 8 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/b361255a-4999-4686-a5e9-48898067feeb) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 3 of 3 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.653421b5-4e47-4db8-a12e-a8efee7f529f?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/.vuepress/public/favicon/browserconfig.xml](https://github.com/okta/okta-developer-docs/blob/b43ef3d9afdfdd4bbfa56a3a7c297f84d7105bf6/packages%2F%40okta%2Fvuepress-site%2F.vuepress%2Fpublic%2Ffavicon%2Fbrowserconfig.xml) | 100 | 6 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/775d1b59-9536-4923-b0ec-5de153d08c17) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/.vuepress/public/favicon/favicon.svg](https://github.com/okta/okta-developer-docs/blob/b43ef3d9afdfdd4bbfa56a3a7c297f84d7105bf6/packages%2F%40okta%2Fvuepress-site%2F.vuepress%2Fpublic%2Ffavicon%2Ffavicon.svg) | 86 | 8 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/a7f934ad-59ae-47c1-bfb3-ed885aa854a4) | [:white_check_mark:](# "Successfully processed") |
| [packages/@okta/vuepress-site/.vuepress/public/favicon/manifest.json](https://github.com/okta/okta-developer-docs/blob/b43ef3d9afdfdd4bbfa56a3a7c297f84d7105bf6/packages%2F%40okta%2Fvuepress-site%2F.vuepress%2Fpublic%2Ffavicon%2Fmanifest.json) | 76 | 8 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/12243716-108b-47ee-babc-961ec9023edc) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 3 of 3 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.5505deb7-9cb6-4246-876f-db970a567fb7?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by ishan-krishna-okta** [comment]
Preview link - https://65a4f69f1e60c11f7e297836--reverent-murdock-829d24.netlify.app

**Review by emikhasyak-okta — APPROVED** [review]

**Review by emikhasyak-okta — APPROVED** [review]
Thanks!

**Pull request merged**
