### PR TITLE
OKTA-567461 Cred Platform - Review Trusted Origins API filter parameter

### PR DESCRIPTION
**Pull request by gabrielsroka**
fix quotes

also, the filter example doesn't seem to work:
https://developer.okta.com/docs/reference/api/trusted-origins/#list-trusted-origins-with-a-filter

you can't filter by id, but you can filter by name. are there other fields that can be used in the filter?

### CODE REVIEW

**Comment by brianduffield-okta** [comment]
Thanks for the PR, @gabrielsroka. I'll forward to the team for review.

**Comment by brianduffield-okta** [comment]
Created internal ticket to track: https://oktainc.atlassian.net/browse/OKTA-567461

**Comment by shamil-okta** [comment]
We support filtering by `name`, `origin`, `status` and `scopeType`.

**Comment by gabrielsroka** [comment]
`?filter=scopeType eq "REDIRECT"` said `invalid search criteria`, but `?filter=type eq "REDIRECT"` seems to work

`?filter=status eq "ACTIVE"` said `Internal Server Error`

name and origin seem to work

**Comment by brianduffield-okta** [comment]
Confirmed testing by @gabrielsroka . I'll go back to the team with these details and open another branch to update the API reference, which currently has no info on properties you can filter on (as well as OAS3 version.)

**Review by brianduffield-okta — APPROVED** [review]
LGTM

**Review by brianduffield-okta — APPROVED** [review]
LGTM

**Review by hassanmahmood-okta — APPROVED** [review]
LGTM

**Comment by brianduffield-okta** [comment]
Closing this PR. The updates included in this PR, as well as the filter parameters updates will be made in this PR: https://github.com/okta/okta-developer-docs/pull/4235. The `status` parameter was a bug and will be fixed for next release.

**Pull request closed without merging**
