### PR TITLE
Adding amr supported values table

### PR DESCRIPTION
**Pull request by susanharper-okta**
## Description:
- **What's changed?** Adding amr supported values table
- **Is this PR related to a Monolith release?** No

netlify link: https://65aedf016530be55b118c7de--reverent-murdock-829d24.netlify.app/docs/guides/configure-amr-claims-mapping/main/#supported-amr-values-by-authenticator-type

### Resolves:

* [OKTA-686029](https://oktainc.atlassian.net/browse/OKTA-686029)

### CODE REVIEW

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/db2686319ff04370f62a49ae239d58f387f93d46/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | 71 | 58 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/969d81dc-7cc7-430f-acf2-db7c323c0f5b) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.d3d650ab-04a1-4a55-b17e-9f06cb7eb7ee?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/32bf21b18013bde1037aad9e70bc99839d631caf/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | 71 | 61 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/732554be-d52c-4878-b24d-096c38497ce9) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.d2b9cf87-676a-4c3d-9a5d-13bb22906209?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by susanharper-okta** [comment]
approved by Kunal Ghosh in Slack.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/e78554eb075cfb4b180a0b75fd5680ce2dd180e8/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | 71 | 61 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/3cfb71b3-4aaf-42fb-8607-cb7a8f6b895e) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.74988a01-e286-4dca-9f27-e6cf6b83d720?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/a173518483ab3fbbcc3caa8b74ca33a90449a42c/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | 72 | 60 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/d88beb6e-ce13-4e23-825b-464aab79e33e) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.f64ec8d5-c8fc-4d5b-8cbc-dbf09730a8a9?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Comment by acrolinxdevdocs-okta** [comment]
## Acrolinx Scorecards

Acrolinx checked the content changed here.

Please review the scorecards for each file and make the recommended
improvements.

| Article | Score | Issues | Scorecard | Status |
| ------- | ----- | ------ | --------- | ------ |
| [packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md](https://github.com/okta/okta-developer-docs/blob/6174fb92b0b5b7f69eb6d821c5822d0fe6204d4b/packages%2F%40okta%2Fvuepress-site%2Fdocs%2Fguides%2Fconfigure-amr-claims-mapping%2Fmain%2Findex.md) | 72 | 61 | [→](https://okta.acrolinx.cloud/api/v1/checking/scorecards/9621ef7e-e2b2-452e-b977-a6121fb824e7) | [:white_check_mark:](# "Successfully processed") |

Successfully checked 1 of 1 documents.
See summary in [Content Analysis Dashboard](https://okta.acrolinx.cloud/api/batch/gen.github.bac2d23b-461f-404e-ae65-cb8c9e454009?csBaseUrl=https%3A%2F%2Fokta.acrolinx.cloud&X-Acrolinx-Client-Locale=en)

Reopen the pull request or push new changes to check again.

Depending on the Acrolinx server configuration, the
links expire after some time and you must have a login for the
Acrolinx server to access them again.

**Review by grahamsmith-okta — APPROVED** [review]

**Pull request merged**
