### PR TITLE
Fix pages on mobile screens

### PR DESCRIPTION
**Pull request by volodymyrmakarchuk-okta**
## Description:
- **What's changed?** 
- **Is this PR related to a Monolith release?** 

### Resolves:

* [OKTA-362652](https://oktainc.atlassian.net/browse/OKTA-362652)

### CODE REVIEW

**Comment by volodymyrmakarchuk-okta** [comment]
netlify deploy: https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app/code/

**Comment by shawyu-okta** [comment]
@volodymyrmakarchuk-okta It looks like the breadcumb disappeared from the top of the page in mobile: https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app//docs/guides/quickstart/cli/register-app/

**Comment by shawyu-okta** [comment]
There is still some content overflowing the right side of the page here:
https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app/docs/guides/request-user-consent/-/build-the-request/
image

**Comment by shawyu-okta** [comment]
I realize for some parts of the page we have to allow breaks in the middle of words for long URLs and code examples, but can we avoid it for headings and normal paragraph text? It looks pretty bad:
image

**Comment by volodymyrmakarchuk-okta** [comment]
> There is still some content overflowing the right side of the page here:
> https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app/docs/guides/request-user-consent/-/build-the-request/
> image

**Comment by volodymyrmakarchuk-okta** [comment]
> There is still some content overflowing the right side of the page here:
> https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app/docs/guides/request-user-consent/-/build-the-request/
> image

it's not overflowing, that link has property  overflow-x: scroll

**Comment by shawyu-okta** [comment]
> it's not overflowing, that link has property overflow-x: scroll

Ah okay, you're right.

**Comment by francoislehoux-okta** [comment]
> @volodymyrmakarchuk-okta It looks like the breadcumb disappeared from the top of the page in mobile: https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app//docs/guides/quickstart/cli/register-app/

Looks like the header's menu also will not open on this page

**Comment by volodymyrmakarchuk-okta** [comment]
> @volodymyrmakarchuk-okta It looks like the breadcumb disappeared from the top of the page in mobile: https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app//docs/guides/quickstart/cli/register-app/

hmm I think it was something wrong with deploy, after re-deploy that issue has gone

**Comment by volodymyrmakarchuk-okta** [comment]
> > @volodymyrmakarchuk-okta It looks like the breadcumb disappeared from the top of the page in mobile: https://60108f5fe426f415d203646b--reverent-murdock-829d24.netlify.app//docs/guides/quickstart/cli/register-app/
> 
> Looks like the header's menu also will not open on this page

redeploy fixed that issue

**Comment by volodymyrmakarchuk-okta** [comment]
> I realize for some parts of the page we have to allow breaks in the middle of words for long URLs and code examples, but can we avoid it for headings and normal paragraph text? It looks pretty bad:
> image

@shawyu-okta  I've realized that I use `word-break: break-all` and that's why it breaks words even if it was just enough to put it into a new line, we can use `word-break: break-word;` instead, and seems it will break the word only when it's  too long

**Comment by shawyu-okta** [comment]
@volodymyrmakarchuk-okta nice, let's try that

**Comment by shawyu-okta** [comment]
FYI I've moved the base branch to `sy-developer-docs-4`

**Review by jakubvul-okta — APPROVED** [review]

**Review by shawyu-okta — APPROVED** [review]

**Pull request merged**
